#!/usr/bin/env python3
"""Generate VAPT quiz questions — command-type, scenario, theory. 100+ per category."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "questions"
OUTPUT_DIR.mkdir(exist_ok=True)

def q(id,topic,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

# ===================== RECONNAISSANCE (20) =====================
RECON=[
q("vq-recon-01","reconnaissance","command","easy","What nmap command performs a SYN scan on all ports?",["nmap -sS -p- target","nmap -sS -p-","-sS -p-"],"contains_any",[],"nmap -sS -p- performs a SYN (half-open) scan on all 65535 ports. Requires root.",["SYN scan flag + all ports flag"]),
q("vq-recon-02","reconnaissance","command","medium","What nmap command detects service versions and runs default scripts?",["nmap -sV -sC","nmap -sC -sV","-sV -sC","-sC -sV"],"contains_any",[],"nmap -sV -sC combines version detection (-sV) with default NSE scripts (-sC).",["Two flags: version + scripts"]),
q("vq-recon-03","reconnaissance","command","medium","What tool discovers subdomains passively using certificate transparency?",["subfinder","amass","crt.sh","certsh"],"contains_any",[],"subfinder and amass use certificate transparency logs, DNS databases, and other passive sources for subdomain discovery.",["Passive subdomain tools"]),
q("vq-recon-04","reconnaissance","scenario","hard","You're on a red team engagement and need to scan a target without triggering IDS. What nmap timing template and technique would you use?",["T1","T2","slow","scan-delay","decoy","-T1","-T2"],"contains_any",[],"Use -T1 or -T2 (sneaky/polite) with --scan-delay to slow down probes. Consider -D for decoys or --source-port 53 to mimic DNS traffic.",["Slow timing templates"]),
q("vq-recon-05","reconnaissance","theory","medium","What is the difference between a SYN scan and a Connect scan?",["half-open","full connection","three-way","doesn't complete","stealth"],"contains_any",[],"SYN scan sends SYN, receives SYN-ACK (port open) or RST (closed), then sends RST — never completes the handshake. Connect scan completes the full TCP handshake. SYN is stealthier and faster.",["One completes the handshake, one doesn't"]),
q("vq-recon-06","reconnaissance","command","medium","What command uses masscan to scan a /24 network for web ports at 1000 packets/sec?",["masscan","masscan -p80,443","--rate 1000","-p80,443,8080"],"contains_any",[],"masscan -p80,443,8080 10.0.0.0/24 --rate 1000 scans web ports across the subnet.",["masscan with ports and rate"]),
q("vq-recon-07","reconnaissance","scenario","hard","During recon you find a company's GitHub repository with a .env file in commit history. What information might this reveal and how do you access old commits?",["credentials","api keys","passwords","git log","git show","history"],"contains_any",[],"Old commits may contain API keys, database passwords, or cloud credentials. Use 'git log --all' and 'git show <commit>' to view historical file contents.",["Git history preserves deleted secrets"]),
q("vq-recon-08","reconnaissance","command","easy","What tool generates a custom wordlist by spidering a target website?",["cewl"],"contains_any",[],"CeWL (Custom Word List generator) spiders a website and builds a wordlist from page content — catches company-specific passwords.",["Spiders websites for words"]),
q("vq-recon-09","reconnaissance","theory","medium","Why should you always check for IPv6 during reconnaissance?",["overlooked","not firewalled","forgotten","dual-stack","less protected"],"contains_any",[],"Many organizations apply strict firewall rules to IPv4 but forget IPv6. Dual-stack hosts may be fully accessible via IPv6 with no filtering.",["Often forgotten by admins"]),
q("vq-recon-10","reconnaissance","scenario","hard","You discover a target runs a web application on a non-standard port (8443). Standard directory brute-force returns nothing. What alternative enumeration would you try?",["vhost","virtual host","host header","fuzz host","parameter","api"],"contains_any",[],"Try virtual host fuzzing (different Host headers), API endpoint discovery (/api/, /swagger/, /graphql), technology-specific paths, and parameter discovery.",["Look beyond standard directories"]),
q("vq-recon-11","reconnaissance","command","medium","What subfinder command discovers subdomains and saves to a file?",["subfinder -d","subfinder -d domain.com -o","-o subs.txt"],"contains_any",[],"subfinder -d target.com -o subdomains.txt discovers subdomains passively and saves results.",["subfinder with -d and -o flags"]),
q("vq-recon-12","reconnaissance","theory","hard","Explain the concept of 'attack surface' and how reconnaissance maps it.",["all entry points","exposed services","every way in","ports services apps","total exposure"],"contains_any",[],"Attack surface = all possible entry points an attacker can target. Recon maps it by discovering: exposed ports/services, subdomains, web apps, APIs, cloud resources, email addresses, and leaked credentials.",["Everything that's exposed"]),
q("vq-recon-13","reconnaissance","command","medium","What nmap script checks for common vulnerabilities?",["--script vuln","nmap --script vuln","--script=vuln"],"contains_any",[],"nmap --script vuln runs all vulnerability detection scripts against discovered services.",["--script vuln category"]),
q("vq-recon-14","reconnaissance","scenario","medium","You need to identify all live hosts on a /24 network quickly without port scanning. What do you use?",["ping sweep","nmap -sn","arp-scan","fping","-sn"],"contains_any",[],"Use nmap -sn (ping sweep) or arp-scan (if on same subnet) for fast host discovery without port scanning.",["Host discovery without port scan"]),
q("vq-recon-15","reconnaissance","command","hard","What command uses nmap to scan through a SOCKS proxy?",["proxychains nmap","proxychains","--proxies socks4"],"contains_any",[],"Use 'proxychains nmap -sT -Pn target' (must use -sT connect scan through proxy, not SYN scan).",["proxychains + connect scan"]),
q("vq-recon-16","reconnaissance","theory","easy","What is OSINT?",["open source intelligence","publicly available","public information"],"contains_any",[],"OSINT (Open Source Intelligence) is information gathered from publicly available sources — social media, DNS, job postings, public records, etc.",["Publicly available information"]),
q("vq-recon-17","reconnaissance","command","medium","What tool takes screenshots of discovered web services at scale?",["aquatone","eyewitness","gowitness"],"contains_any",[],"Aquatone, EyeWitness, or gowitness take screenshots of web services from a list of URLs for visual reconnaissance.",["Visual recon tools"]),
q("vq-recon-18","reconnaissance","scenario","hard","A company's job posting mentions 'experience with Kubernetes, AWS EKS, and Terraform.' How does this help your pentest?",["technology stack","attack surface","kubernetes vulns","cloud","infrastructure"],"contains_any",[],"Job postings reveal technology stack. Now you know to look for: exposed Kubernetes dashboards, misconfigured EKS clusters, Terraform state files in S3, and cloud misconfigurations.",["Job postings reveal tech stack"]),
q("vq-recon-19","reconnaissance","command","easy","What is the default nmap scan if you just run 'nmap target'?",["top 1000 ports","syn scan","1000","top 1000"],"contains_any",[],"Default nmap scans the top 1000 most common ports with a SYN scan (if root) or Connect scan (if unprivileged).",["Not all ports — just the common ones"]),
q("vq-recon-20","reconnaissance","theory","medium","When would you use a UDP scan and why is it slow?",["dns","snmp","dhcp","no response","timeout","stateless"],"contains_any",[],"UDP scan finds services like DNS(53), SNMP(161), DHCP(67). It's slow because open UDP ports don't respond — nmap must wait for timeout on each port to determine if it's open or filtered.",["No response = might be open"]),
]

# ===================== ACTIVE DIRECTORY (20) =====================
AD=[
q("vq-ad-01","active_directory","command","medium","What impacket tool performs Kerberoasting from Linux?",["GetUserSPNs.py","GetUserSPNs","impacket-GetUserSPNs"],"contains_any",[],"GetUserSPNs.py -request -dc-ip <DC> domain/user:pass extracts TGS hashes for offline cracking.",["GetUser...SPNs"]),
q("vq-ad-02","active_directory","command","hard","What command performs a DCSync attack using secretsdump?",["secretsdump.py","secretsdump","impacket-secretsdump"],"contains_any",[],"secretsdump.py domain/admin:pass@DC_IP dumps all domain hashes via DCSync (replication).",["secretsdump from impacket"]),
q("vq-ad-03","active_directory","scenario","hard","You have a domain user account but need Domain Admin. BloodHound shows a path through a user who has GenericAll on the Domain Admins group. What do you do?",["add to group","modify membership","net group","add user to domain admins"],"contains_any",[],"GenericAll on a group = full control. Add your compromised user (or a new user) to Domain Admins using net group or PowerView.",["GenericAll = full control over the object"]),
q("vq-ad-04","active_directory","command","medium","What tool collects BloodHound data from a Linux machine?",["bloodhound-python","bloodhound.py"],"contains_any",[],"bloodhound-python -u user -p pass -d domain.local -ns DC_IP -c all collects all AD data for BloodHound.",["Python version of SharpHound"]),
q("vq-ad-05","active_directory","theory","medium","What is Kerberoasting and why is it effective?",["request tgs","service account","offline crack","no detection","spn"],"contains_any",[],"Kerberoasting requests TGS tickets for service accounts (which have SPNs). The ticket is encrypted with the service account's password hash — crack offline with no failed login attempts or detection.",["Offline cracking of service account passwords"]),
q("vq-ad-06","active_directory","scenario","hard","You captured an NTLMv2 hash with Responder but can't crack it. SMB signing is disabled on a file server. What's your next move?",["relay","ntlmrelayx","ntlm relay","relay to file server"],"contains_any",[],"Relay the captured authentication to the file server using ntlmrelayx.py. Since SMB signing is disabled, the relay will succeed and give you a shell.",["Don't crack — relay instead"]),
q("vq-ad-07","active_directory","command","medium","What Rubeus command performs AS-REP roasting?",["Rubeus.exe asreproast","rubeus asreproast","asreproast"],"contains_any",[],"Rubeus.exe asreproast finds accounts without pre-authentication and extracts crackable AS-REP hashes.",["Rubeus asreproast"]),
q("vq-ad-08","active_directory","theory","hard","Explain the difference between a Golden Ticket and a Silver Ticket.",["krbtgt vs service","tgt vs tgs","all access vs one service","dc vs no dc"],"contains_any",[],"Golden Ticket forges a TGT using krbtgt hash — gives access to EVERYTHING and touches the DC. Silver Ticket forges a TGS for ONE specific service using the service account hash — doesn't touch the DC (stealthier).",["One is universal, one is targeted"]),
q("vq-ad-09","active_directory","command","hard","What command uses certipy to find vulnerable AD CS templates?",["certipy find","certipy find -vulnerable","-vulnerable"],"contains_any",[],"certipy find -u user@domain -p pass -dc-ip DC -vulnerable identifies exploitable certificate templates.",["certipy find with -vulnerable flag"]),
q("vq-ad-10","active_directory","scenario","hard","You're on an internal network with no credentials. How do you get your first domain account?",["responder","llmnr","mitm6","ntlm","poison","relay"],"contains_any",[],"Run Responder to poison LLMNR/NBT-NS and capture NTLMv2 hashes from Windows machines making typo'd network requests. Crack or relay the hashes.",["Poison name resolution"]),
q("vq-ad-11","active_directory","command","medium","What hashcat mode cracks Kerberos 5 TGS-REP (Kerberoast) hashes?",["13100","hashcat -m 13100"],"contains_any",[],"hashcat -m 13100 for Kerberos 5 TGS-REP etype 23 (RC4). Use -m 19700 for etype 17/18 (AES).",["13100"]),
q("vq-ad-12","active_directory","theory","medium","What is NTLM relay and what conditions must be met for it to work?",["smb signing disabled","forward auth","no signing","relay to another target"],"contains_any",[],"NTLM relay forwards captured authentication to another target. Requirements: SMB signing must be disabled on the target, and the relayed user must have admin rights on the target.",["Signing disabled + admin rights on target"]),
q("vq-ad-13","active_directory","scenario","hard","After compromising a workstation, you find the user is a member of 'Backup Operators'. How can you escalate to Domain Admin?",["backup sam","ntds","shadow copy","backup privilege","diskshadow"],"contains_any",[],"Backup Operators can read any file including NTDS.dit. Use diskshadow/wbadmin to create a shadow copy of the DC's C: drive, then extract NTDS.dit and SYSTEM hive to dump all domain hashes.",["Backup privilege = read anything"]),
q("vq-ad-14","active_directory","command","medium","What netexec command sprays a password across domain users?",["netexec smb","--continue-on-success","nxc smb","-u users.txt -p"],"contains_any",[],"netexec smb DC_IP -u users.txt -p 'Password1!' --continue-on-success sprays one password against all users.",["netexec smb with user list and password"]),
q("vq-ad-15","active_directory","theory","hard","What is PetitPotam and why is it dangerous?",["coerce","force authentication","ntlm","dc authenticates","relay to adcs"],"contains_any",[],"PetitPotam coerces a DC to authenticate to an attacker-controlled server via EFS RPC. Combined with NTLM relay to AD CS, it gives instant Domain Admin by obtaining a DC certificate.",["Force DC to authenticate to you"]),
q("vq-ad-16","active_directory","command","hard","What impacket tool gives you a shell using only an NTLM hash (pass-the-hash)?",["psexec.py","wmiexec.py","smbexec.py","-hashes"],"contains_any",[],"psexec.py -hashes :NTLM_HASH domain/user@target or wmiexec.py with -hashes flag for pass-the-hash.",["impacket tools with -hashes flag"]),
q("vq-ad-17","active_directory","scenario","hard","You have Domain Admin but the client wants you to demonstrate persistence. What technique survives a password reset of all accounts?",["golden ticket","skeleton key","dsrm","dcsync","krbtgt"],"contains_any",[],"A Golden Ticket (using krbtgt hash) persists until krbtgt is reset TWICE. Skeleton Key patches LSASS on the DC. DSRM backdoor uses the DC's local admin. All survive normal password resets.",["krbtgt-based persistence"]),
q("vq-ad-18","active_directory","command","medium","What tool enumerates AD users via Kerberos without triggering lockouts?",["kerbrute","kerbrute userenum"],"contains_any",[],"kerbrute userenum --dc DC_IP -d domain.local users.txt enumerates valid users via Kerberos pre-auth without lockout risk.",["kerbrute"]),
q("vq-ad-19","active_directory","theory","medium","What is the difference between Pass-the-Hash and Pass-the-Ticket?",["ntlm vs kerberos","hash vs ticket","pth vs ptt"],"contains_any",[],"Pass-the-Hash uses NTLM hash for authentication (works when NTLM is allowed). Pass-the-Ticket uses a Kerberos ticket (TGT/TGS) — works even when NTLM is disabled.",["NTLM vs Kerberos authentication"]),
q("vq-ad-20","active_directory","scenario","hard","BloodHound shows your compromised user has 'WriteDACL' on another user who is a Domain Admin. How do you exploit this?",["modify acl","grant dcsync","add genericall","change permissions","give yourself rights"],"contains_any",[],"WriteDACL lets you modify the target's ACL. Grant yourself GenericAll or DCSync rights on that user, then reset their password or perform DCSync.",["Modify their permissions to give yourself access"]),
]

if __name__ == "__main__":
    with open(OUTPUT_DIR / "recon_quiz.json", 'w') as f:
        json.dump(RECON, f, indent=2)
    print(f"Recon: {len(RECON)}")
    with open(OUTPUT_DIR / "ad_quiz.json", 'w') as f:
        json.dump(AD, f, indent=2)
    print(f"AD: {len(AD)}")
    print(f"\nTotal VAPT questions: {len(RECON) + len(AD)}")
